"""Maintenance script smoke tests: 確保基本 help / error path 不會 crash。

不需要 Ollama 或任何外部服務即可通過。
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


def test_aicode_prepares_opencode_mcp_wrapper(tmp_path):
    """`aicode` should create the local MCP wrapper expected by opencode.json."""
    if not shutil.which("git"):
        pytest.skip("git is required for the aicode wrapper smoke test")

    project = tmp_path / "project"
    project.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=project, check=True)
    subdir = project / "src"
    subdir.mkdir()
    home = tmp_path / "home"
    home.mkdir()
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    stub_opencode = bin_dir / "opencode"
    stub_opencode.write_text("#!/usr/bin/env bash\nexit 0\n", encoding="utf-8")
    stub_opencode.chmod(0o700)

    aicode_link = bin_dir / "aicode"
    aicode_link.symlink_to(REPO_ROOT / "aicode")

    env = {
        **os.environ,
        "HOME": str(home),
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "PYTHONIOENCODING": "utf-8",
        # aicode 啟動會跑 ctx 安全閘,在 CI / 沒 GPU / inherited AICODE_MODEL
        # 的環境下會 refuse to start。這個 smoke test 只關心 MCP wrapper
        # 生成,不該被安全閘擋下。
        "AICODE_CTX_SAFETY_DISABLE": "1",
        # CodeTrail 不再內建預設主模型, 啟動時要先解析。給個假值讓 resolve_main_model
        # 通過; 真正的主模型解析邏輯有自己的單元測試覆蓋。
        "AICODE_MODEL": "qwen3-coder:30b",
    }
    r = subprocess.run(
        [str(aicode_link)],
        cwd=subdir,
        capture_output=True,
        text=True,
        timeout=15,
        stdin=subprocess.DEVNULL,
        env=env,
    )

    assert r.returncode == 0, f"exit={r.returncode}\nstdout={r.stdout}\nstderr={r.stderr}"
    wrapper = project / ".opencode" / "run-codetrail-mcp"
    assert wrapper.is_file()
    assert os.access(wrapper, os.X_OK)
    content = wrapper.read_text(encoding="utf-8")
    assert "generated by CodeTrail aicode" in content
    assert f'exec python3 "{REPO_ROOT}/mcp_server.py"' in content
    assert f'exec python "{REPO_ROOT}/mcp_server.py"' in content


def test_rag_help_exits_zero():
    """`python RAG.py --help` 必須能 cheap return 0。"""
    r = subprocess.run(
        [sys.executable, str(REPO_ROOT / "RAG.py"), "--help"],
        capture_output=True, text=True, timeout=15,
        stdin=subprocess.DEVNULL,
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    assert r.returncode == 0, f"exit={r.returncode}\n{r.stderr}"
    assert "用法" in r.stdout or "usage" in r.stdout.lower()
    assert "Traceback" not in r.stderr


def test_rag_help_lists_binary_and_image_types():
    """`python RAG.py --help` 要列出 binary/ELF/圖片副檔名,避免使用者誤以為只支援 PDF。"""
    r = subprocess.run(
        [sys.executable, str(REPO_ROOT / "RAG.py"), "--help"],
        capture_output=True, text=True, timeout=15,
        stdin=subprocess.DEVNULL,
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    assert r.returncode == 0
    out = r.stdout
    assert ".bin" in out, "RAG.py --help should mention .bin support"
    assert ".elf" in out, "RAG.py --help should mention .elf support"
    assert ".png" in out, "RAG.py --help should mention .png support"


def test_rag_rejects_unknown_extension_with_supported_list(tmp_path):
    """副檔名不支援時,error 訊息要列出支援清單(包含 binary/ELF),不能只說 pdf/md/txt。"""
    bad_file = tmp_path / "garbage.xyz"
    bad_file.write_text("hi")
    kb_file = tmp_path / "kb.json"
    r = subprocess.run(
        [sys.executable, str(REPO_ROOT / "RAG.py"), str(bad_file), str(kb_file)],
        capture_output=True, text=True, timeout=15,
        stdin=subprocess.DEVNULL,
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    assert r.returncode != 0
    out = r.stdout + r.stderr
    assert "不支援" in out, out
    # error 訊息要提到三類副檔名
    assert ".pdf" in out, out
    assert ".bin" in out, out
    assert ".elf" in out, out
    assert "Traceback" not in r.stderr


def test_run_eval_help_exits_zero():
    """`python eval/run_eval.py --help` 必須能 cheap return 0,不需要 Ollama。"""
    r = subprocess.run(
        [sys.executable, str(REPO_ROOT / "eval" / "run_eval.py"), "--help"],
        capture_output=True, text=True, timeout=15,
        stdin=subprocess.DEVNULL,
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    assert r.returncode == 0, f"exit={r.returncode}\n{r.stderr}"
    assert "usage" in r.stdout.lower() or "用法" in r.stdout
    assert "Traceback" not in r.stderr
