"""`aicode` wrapper 的離線 CLI 契約:MCP wrapper 生成、舊設定自動修復、--model 轉發。

從 test_cli.py 拆出(2026-08-20):原檔 43 條測試 14.07s,是全套件最慢的單檔,
分片再多也被它卡住。行為與 assertion 未變,只是換檔案。
"""

from __future__ import annotations

import json
import os
import subprocess

import pytest

from tests._harness import (
    OFFLINE_CTX,
    REPO_ROOT,
    bash_compatible_path,
    read_stub_args,
    require_git,
    require_working_bash,
    run_aicode_with_stub,
)


def test_aicode_prepares_opencode_mcp_wrapper(tmp_path):
    """`aicode` should create the local MCP wrapper expected by opencode.json."""
    require_git()
    bash = require_working_bash()
    aicode_script = bash_compatible_path(bash, REPO_ROOT / "aicode")

    project = tmp_path / "project"
    project.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=project, check=True)
    subdir = project / "src"
    subdir.mkdir()
    home = tmp_path / "home"
    home.mkdir()
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    stub_opencode = bin_dir / "opencode"
    stub_opencode.write_text("#!/usr/bin/env bash\nexit 0\n", encoding="utf-8")
    stub_opencode.chmod(0o700)

    env = {
        **os.environ,
        "HOME": str(home),
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "PYTHONIOENCODING": "utf-8",
        "AICODE_N_CTX": OFFLINE_CTX,
        # aicode 啟動會跑 ctx 安全閘,在 CI / 沒 GPU / inherited AICODE_MODEL
        # 的環境下會 refuse to start。這個 smoke test 只關心 MCP wrapper
        # 生成,不該被安全閘擋下。
        "AICODE_CTX_SAFETY_DISABLE": "1",
        "AICODE_REQUIRED_MODELS_CHECK_SKIP": "1",
        "AICODE_TOOL_CANARY_SKIP": "1",
        # CodeTrail 不再內建預設主模型, 啟動時要先解析。給個假值讓 resolve_main_model
        # 通過; 真正的主模型解析邏輯有自己的單元測試覆蓋。
        "AICODE_MODEL": "example-code-model:30b",
    }
    r = subprocess.run(
        [bash, aicode_script],
        cwd=subdir,
        capture_output=True,
        text=True,
        timeout=15,
        stdin=subprocess.DEVNULL,
        env=env,
    )

    assert r.returncode == 0, f"exit={r.returncode}\nstdout={r.stdout}\nstderr={r.stderr}"
    assert "[tool-health] SKIP" in r.stdout
    wrapper = project / ".opencode" / "run-codetrail-mcp"
    assert wrapper.is_file()
    assert os.access(wrapper, os.X_OK)
    content = wrapper.read_text(encoding="utf-8")
    assert "generated by CodeTrail aicode" in content
    assert "exec python3" in content and "mcp_server.py" in content
    assert "exec python" in content and "mcp_server.py" in content


def test_aicode_repairs_short_codetrail_timeout_before_starting_opencode(tmp_path):
    """更新 repo 後直接跑 aicode:舊的 10 秒 timeout 要在 client 啟動前修好,
    契約遷移(opencode_contract_check)也要接著補上寫入工具的 ask 核准閘與
    lessons instructions —— 這是舊安裝 git pull 後的無感升級路徑。"""
    config_path = tmp_path / "opencode.json"
    original = {
        "model": "llamacpp/local-model",
        "mcp": {
            "codetrail": {
                "type": "local",
                "enabled": True,
                "timeout": 10_000,
            }
        },
        "permission": {"*": "deny"},
    }
    config_path.write_text(
        json.dumps(original, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    result, args_file = run_aicode_with_stub(
        tmp_path,
        [],
        env_extra={
            "OPENCODE_CONFIG": str(config_path),
            "AICODE_MCP_TIMEOUT_CHECK_SKIP": "0",
        },
    )

    assert result.returncode == 0, (
        f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    updated = json.loads(config_path.read_text(encoding="utf-8"))
    assert updated["mcp"]["codetrail"]["timeout"] == 660_000
    # 原有 permission 保留;缺少的 ask 核准閘與 lessons instructions 被補上
    assert updated["permission"]["*"] == "deny"
    assert updated["permission"]["codetrail_record_lesson"] == "ask"
    assert updated["instructions"] == [".codetrail/lessons.md"]
    # 第一份備份是 timeout 修復前的原檔(契約遷移的備份接續編號)
    backup = config_path.with_name(config_path.name + ".codetrail.bak")
    assert json.loads(backup.read_text(encoding="utf-8")) == original
    assert "FIXED" in result.stdout
    assert read_stub_args(args_file) == []


def test_aicode_passes_through_bare_model_arg(tmp_path):
    """新版 aicode 不再強加 provider prefix,使用者傳什麼就轉發什麼。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "bare-model"],
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["--model", "bare-model"]


def test_aicode_rejects_external_ollama_provider_in_model_arg(tmp_path):
    """ollama/ openai/ 等已知外部 provider prefix 必須被 resolve_main_model 攔下。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "ollama/bare-model"],
    )

    assert result.returncode != 0
    assert ("外部 provider" in result.stderr) or ("provider prefix" in result.stderr)


def test_aicode_passes_through_custom_provider_model_arg(tmp_path):
    """自定 provider (例如 llamacpp/foo) 原樣轉發給 OpenCode;CodeTrail 自己會 strip 出 bare。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["-m", "llamacpp/some-model"],
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["-m", "llamacpp/some-model"]


def test_aicode_passes_through_equals_model_arg(tmp_path):
    """--model=foo 形式也原樣轉發。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model=bare-model"],
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["--model=bare-model"]


@pytest.mark.parametrize("args", [["--model"], ["-m"], ["--model", "--foo"]])
def test_aicode_missing_model_arg_value_fails_without_opencode_fallback(tmp_path, args):
    result, args_file = run_aicode_with_stub(tmp_path, args)

    assert result.returncode != 0
    assert "requires a model value" in result.stderr
    assert not args_file.exists()


def test_aicode_env_and_cli_model_conflict_fails_loud(tmp_path):
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "bar:baz"],
        {"AICODE_MODEL": "foo:bar"},
    )

    assert result.returncode != 0
    assert "different models" in result.stderr
    assert not args_file.exists()


def test_aicode_env_and_cli_same_model_passes_through(tmp_path):
    """env 和 CLI 解析到同一個 bare model 時不衝突,CLI 值原樣轉發給 OpenCode。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "foo-bar"],
        {"AICODE_MODEL": "foo-bar"},
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["--model", "foo-bar"]
