"""set_config 的產出物:~/start.sh、deployment.json、opencode.json 合併、備份與 restore。

從 tests/test_set_config.py 拆出(2026-08-20)。
"""

from __future__ import annotations

import json
import stat
import subprocess
from pathlib import Path

from tests._set_config_harness import (
    SCRIPT,
    TWO_GPUS,
    YES_TWO_GPU,
    build_env,
    make_models,
    read_deployment,
    run,
    write_fake_nvidia_smi,
)


def test_yes_run_generates_all_artifacts(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    proc = run(tmp_path, *YES_TWO_GPU, "--models-dir", str(models))

    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert "初步判定 OK" in proc.stdout
    home = tmp_path / "home"

    registry = json.loads((home / ".config/codetrail/models.json").read_text(encoding="utf-8"))
    main_path = str(models / "big-chat" / "big-chat-ud-q4_k_xl-00001-of-00002.gguf")
    assert registry["big-chat-ud-q4-k-xl"] == main_path

    deployment = json.loads((home / ".config/codetrail/deployment.json").read_text(encoding="utf-8"))
    services = deployment["services"]
    assert services["main"]["model"] == "big-chat-ud-q4-k-xl"
    assert services["main"]["ctx"] == 65536
    assert services["main"]["parameters"]["jinja"] is True
    # 沒給 --threads → 不寫 -t,交給 llama.cpp 自己的預設
    assert "threads" not in services["main"]["parameters"]
    assert services["main"]["parameters"]["gpu_layers"] == 99
    assert services["embedding"]["model"] == str(models / "bge-m3" / "bge-m3-f16.gguf")
    assert services["reranker"]["model"].endswith("bge-reranker-v2-m3-Q8_0.gguf")
    assert services["vl"]["model"] == str(models / "vl" / "vl-model-q6.gguf")
    assert services["vl"]["mmproj"] == str(models / "vl" / "mmproj-F16.gguf")
    assert services["embedding"]["parameters"] == {"parallel": 1, "cache_ram": 0}
    assert services["reranker"]["ctx"] == 8192
    assert services["reranker"]["batch"] == 8192
    assert services["reranker"]["ubatch"] == 8192
    assert services["reranker"]["parameters"] == {"parallel": 1, "cache_ram": 0}
    assert services["vl"]["parameters"] == {
        "gpu_layers": "auto",
        "parallel": 1,
        "fit": "on",
        "fit_target": 3072,
    }
    # 未給 --allow-remote → 不寫 bind(profile 預設 local)
    assert "bind" not in services["main"]

    opencode = json.loads((home / ".config/opencode/opencode.json").read_text(encoding="utf-8"))
    assert opencode["model"] == "llamacpp/big-chat-ud-q4-k-xl"
    limit = opencode["provider"]["llamacpp"]["models"]["big-chat-ud-q4-k-xl"]["limit"]
    assert limit["context"] == 65536
    mcp = opencode["mcp"]["codetrail"]
    assert mcp["timeout"] == 660000
    assert "mcp_server.py" in mcp["command"][2]
    assert opencode["permission"]["bash"] == "deny"

    start = home / "start.sh"
    content = start.read_text(encoding="utf-8")
    assert "generated by CodeTrail set_config.sh" in content
    assert "export MAIN_GPU=GPU-aaaa-5090" in content
    assert "export AUX_GPU=GPU-bbbb-2000" in content
    assert 'launch_servers.py --scope all "$@" || rc=$?' in content
    assert content.rstrip().endswith('exit "$rc"')
    assert start.stat().st_mode & stat.S_IXUSR

    # 結尾預覽 = start-all --dry-run 的完整指令
    assert "main_command=" in proc.stdout
    assert proc.stdout.count("CUDA_VISIBLE_DEVICES=GPU-bbbb-2000") == 3
    # 三層狀態:設定完成 ≠ 已可使用
    assert "第 1 層" in proc.stdout
    assert "待執行" in proc.stdout
    # 不再有容量預估字樣
    assert "容量預估" not in proc.stdout
    assert "建議配置" not in proc.stdout

def test_generated_start_sh_dry_run_pins_gpus_and_binds_loopback(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0

    proc = subprocess.run(
        ["bash", str(tmp_path / "home" / "start.sh"), "--dry-run"],
        env=build_env(tmp_path),
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr
    for port in ("8080", "8081", "8082", "8083"):
        assert f"_port={port}" in proc.stdout
    assert proc.stdout.count("CUDA_VISIBLE_DEVICES=GPU-aaaa-5090") == 1
    assert proc.stdout.count("CUDA_VISIBLE_DEVICES=GPU-bbbb-2000") == 3
    # 安全預設:只綁 127.0.0.1,不暴露 0.0.0.0
    assert "main_bind_host=127.0.0.1" in proc.stdout
    assert "0.0.0.0" not in proc.stdout
    # --dry-run 沒有真的啟動 → 不印 nvidia-smi 監控提醒
    assert "稍微監控" not in proc.stdout

def test_generated_start_sh_ends_with_nvidia_smi_reminder(tmp_path):
    """啟動成功後的最後輸出 = 提醒使用者用 nvidia-smi 稍微監控(set_config 不做容量估算)。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    content = (tmp_path / "home" / "start.sh").read_text(encoding="utf-8")
    assert "watch -n 1 nvidia-smi" in content
    assert "稍微監控" in content
    # 提醒在啟動流程之後、只在成功(rc=0)且非 --dry-run 時印出
    assert 'launch_servers.py --scope all "$@" || rc=$?' in content
    assert '*" --dry-run "*' in content
    assert content.index('launch_servers.py --scope all "$@"') < content.index("稍微監控")

def test_allow_remote_binds_all_interfaces_with_warning(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--allow-remote",
                "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr
    assert "0.0.0.0" in proc.stdout  # 警告文字

    deployment = read_deployment(tmp_path)
    for role in ("main", "embedding", "reranker", "vl"):
        assert deployment["services"][role]["bind"] == "all-interfaces"

    dry = subprocess.run(
        ["bash", str(tmp_path / "home" / "start.sh"), "--dry-run"],
        env=build_env(tmp_path),
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    assert dry.returncode == 0, dry.stderr
    assert "main_bind_host=0.0.0.0" in dry.stdout

def test_generated_start_sh_clears_legacy_env_overrides(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0

    env = build_env(tmp_path)
    env["EMBED_MODEL"] = "/bogus/does-not-exist.gguf"   # 模擬 .bashrc 殘留的舊 override
    env["MAIN_CTX"] = "1234"
    env["AICODE_N_CTX"] = "2048"
    proc = subprocess.run(
        ["bash", str(tmp_path / "home" / "start.sh"), "--dry-run"],
        env=env,
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr
    assert "/bogus/does-not-exist.gguf" not in proc.stdout
    assert "-c 65536" in proc.stdout  # 不被 MAIN_CTX=1234 蓋掉

def test_existing_configs_are_backed_up_and_registry_merged(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/codetrail").mkdir(parents=True)
    (home / ".config/codetrail/models.json").write_text(
        json.dumps({"old-key": "/somewhere/old.gguf"}), encoding="utf-8"
    )
    (home / ".config/opencode").mkdir(parents=True)
    (home / ".config/opencode/opencode.json").write_text("{}", encoding="utf-8")

    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr

    registry = json.loads((home / ".config/codetrail/models.json").read_text(encoding="utf-8"))
    assert registry["old-key"] == "/somewhere/old.gguf"
    assert "big-chat-ud-q4-k-xl" in registry
    assert list((home / ".config/codetrail").glob("models.json.bak-setconfig-*"))
    assert list((home / ".config/opencode").glob("opencode.json.bak-setconfig-*"))

def test_opencode_merge_preserves_user_config_and_respects_permission(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/opencode").mkdir(parents=True)
    existing = {
        "theme": "dark",
        "model": "openrouter/some-cloud-model",
        "enabled_providers": ["openrouter"],
        "provider": {
            "openrouter": {"npm": "@ai-sdk/openai", "options": {"apiKey": "sk-keep"}},
            "llamacpp": {
                "npm": "@ai-sdk/openai-compatible",
                "options": {"baseURL": "http://localhost:8080/v1", "apiKey": "dummy"},
                "models": {"my-old-local": {"name": "my-old-local"}},
            },
        },
        "mcp": {"other-server": {"type": "local", "command": ["echo"], "enabled": True}},
        "permission": {"*": "deny", "bash": "allow"},
    }
    (home / ".config/opencode/opencode.json").write_text(json.dumps(existing), encoding="utf-8")

    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr

    merged = json.loads((home / ".config/opencode/opencode.json").read_text(encoding="utf-8"))
    assert merged["theme"] == "dark"                                   # 使用者設定保留
    assert merged["model"] == "llamacpp/big-chat-ud-q4-k-xl"           # CodeTrail 欄位覆蓋
    assert "openrouter" in merged["provider"]                          # 其他 provider 保留
    assert merged["provider"]["openrouter"]["options"]["apiKey"] == "sk-keep"
    assert "my-old-local" in merged["provider"]["llamacpp"]["models"]  # 舊本機模型項保留
    assert "big-chat-ud-q4-k-xl" in merged["provider"]["llamacpp"]["models"]
    assert "other-server" in merged["mcp"]                             # 其他 MCP 保留
    assert "codetrail" in merged["mcp"]
    assert merged["permission"]["bash"] == "allow"                     # 尊重使用者顯式設定…
    assert "已尊重你的設定" in proc.stdout                              # …但要警告
    assert "llamacpp" in merged["enabled_providers"]
    assert "openrouter" in merged["enabled_providers"]

def test_restore_last_backup_round_trips_whole_transaction(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/codetrail").mkdir(parents=True)
    (home / ".config/codetrail/models.json").write_text('{"marker": "/old.gguf"}', encoding="utf-8")

    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    registry = json.loads((home / ".config/codetrail/models.json").read_text(encoding="utf-8"))
    assert "big-chat-ud-q4-k-xl" in registry
    assert (home / ".config/codetrail/setconfig-last-transaction.json").is_file()

    proc = run(tmp_path, "--restore-last-backup")
    assert proc.returncode == 0, proc.stderr
    # manifest 整批還原:當時存在的檔案回到備份內容…
    restored = json.loads((home / ".config/codetrail/models.json").read_text(encoding="utf-8"))
    assert restored == {"marker": "/old.gguf"}
    # …當時不存在的檔案被移除,不會殘留半套設定
    assert not (home / ".config/codetrail/deployment.json").exists()
    assert not (home / ".config/opencode/opencode.json").exists()
    assert not (home / "start.sh").exists()

def test_start_sh_pins_validated_llama_bin(tmp_path):
    """set_config 用 LLAMA_BIN 驗證旗標 → 產生的 start.sh 必須寫死同一顆 binary,
    否則新 shell 啟動的是另一顆(可能沒 --fit 的)llama-server。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    content = (tmp_path / "home" / "start.sh").read_text(encoding="utf-8")
    assert f"export LLAMA_BIN={tmp_path / 'llama-server'}" in content

def test_rerun_has_no_carryover_current_answers_win(tmp_path):
    """新契約:重跑不沿用任何舊值 —— 每次的設定完全來自本次作答/旗標。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    first = run(
        tmp_path, "--yes", "--no-preview", "--models-dir", str(models),
        "--main-model", "1", "--rerank-model", "1",
        "--main-gpu", "0", "--embed-gpu", "1", "--rerank-gpu", "1", "--vl-gpu", "1",
        "--ctx", "32768", "--threads", "12", "--rerank-ctx", "4096",
    )
    assert first.returncode == 0, first.stderr
    assert read_deployment(tmp_path)["services"]["main"]["ctx"] == 32768
    assert read_deployment(tmp_path)["services"]["main"]["parameters"]["threads"] == 12

    rerun = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert rerun.returncode == 0, rerun.stderr + rerun.stdout
    assert "沿用" not in rerun.stdout
    deployment = read_deployment(tmp_path)
    assert deployment["services"]["main"]["ctx"] == 65536      # 本次旗標值,不是舊值
    # 這次沒給 --threads → 舊值不沿用,直接不寫 -t
    assert "threads" not in deployment["services"]["main"]["parameters"]
    assert deployment["services"]["reranker"]["ctx"] == 8192

    opencode = json.loads(
        (tmp_path / "home" / ".config/opencode/opencode.json").read_text(encoding="utf-8")
    )
    limit = opencode["provider"]["llamacpp"]["models"]["big-chat-ud-q4-k-xl"]["limit"]
    assert limit["context"] == 65536

def test_symlinked_config_files_are_written_through(tmp_path):
    """dotfiles 使用者的 opencode.json 是 symlink → 寫穿到目標,保留連結。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    dotfiles = tmp_path / "dotfiles"
    dotfiles.mkdir()
    real = dotfiles / "opencode.json"
    real.write_text("{}", encoding="utf-8")
    (home / ".config/opencode").mkdir(parents=True)
    (home / ".config/opencode/opencode.json").symlink_to(real)

    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr
    link = home / ".config/opencode/opencode.json"
    assert link.is_symlink()  # 連結還在,沒被換成一般檔
    merged = json.loads(real.read_text(encoding="utf-8"))
    assert merged["model"] == "llamacpp/big-chat-ud-q4-k-xl"  # 內容寫到目標
    assert "symlink" in proc.stdout

def test_invalid_registry_entries_are_dropped_with_warning(tmp_path):
    """models.json 有格式非法的手寫項目時要剔除並警告,
    否則啟動時整份 registry 會被 loader 拒絕。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/codetrail").mkdir(parents=True)
    (home / ".config/codetrail/models.json").write_text(
        json.dumps({
            "good-key": "/somewhere/model.gguf",
            "bad key with spaces": "/somewhere/other.gguf",
            "relative-path": "not/absolute.gguf",
        }),
        encoding="utf-8",
    )

    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr
    assert "格式不合法的項目已剔除" in proc.stdout
    registry = json.loads((home / ".config/codetrail/models.json").read_text(encoding="utf-8"))
    assert "good-key" in registry
    assert "bad key with spaces" not in registry
    assert "relative-path" not in registry

def test_rerun_preserves_hand_added_sampling_params_and_warns_on_dropped(tmp_path):
    """工具自己教使用者把取樣參數加進 deployment.json → 重跑必須保留;
    no_mmap 已不由工具管理,手動設定同樣保留;工具管理鍵(n_cpu_moe 等)每次
    依作答重寫、安靜淘汰;其他未涵蓋鍵要警告已捨棄,不能靜默消失。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    deployment_path = tmp_path / "home" / ".config/codetrail/deployment.json"
    config = json.loads(deployment_path.read_text(encoding="utf-8"))
    config["services"]["main"]["parameters"]["temperature"] = 0.6
    config["services"]["main"]["parameters"]["top_p"] = 0.95
    config["services"]["main"]["parameters"]["no_mmap"] = True
    config["services"]["main"]["parameters"]["n_cpu_moe"] = 90
    config["services"]["main"]["parameters"]["custom_flag"] = 123
    deployment_path.write_text(json.dumps(config, ensure_ascii=False), encoding="utf-8")

    rerun = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert rerun.returncode == 0, rerun.stderr + rerun.stdout
    assert "保留你手動加在 deployment.json 的 main 參數" in rerun.stdout
    assert "temperature=0.6" in rerun.stdout
    assert "已捨棄:custom_flag=123" in rerun.stdout
    assert "n_cpu_moe=90" not in rerun.stdout  # 工具管理鍵:安靜淘汰,不當成使用者鍵警告

    merged = json.loads(deployment_path.read_text(encoding="utf-8"))
    parameters = merged["services"]["main"]["parameters"]
    assert parameters["temperature"] == 0.6
    assert parameters["top_p"] == 0.95
    assert parameters["no_mmap"] is True
    assert "n_cpu_moe" not in parameters
    assert "custom_flag" not in parameters

def test_generated_start_sh_subcommand_guard_and_logs_validation(tmp_path):
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    start = tmp_path / "home" / "start.sh"

    def run_start(*args: str):
        return subprocess.run(
            ["bash", str(start), *args],
            env=build_env(tmp_path),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )

    helped = run_start("help")
    assert helped.returncode == 0, helped.stderr
    assert "用法" in helped.stdout
    assert "logs [role]" in helped.stdout

    typo = run_start("stauts")  # 拼錯不得直接進入啟動流程
    assert typo.returncode == 2
    assert "未知子命令" in typo.stderr

    bad_role = run_start("logs", "gpu")
    assert bad_role.returncode == 2
    assert "未知 role" in bad_role.stderr

    never_started = run_start("logs", "main")
    assert never_started.returncode == 1
    assert "尚未啟動過" in never_started.stderr

def test_generated_start_sh_exports_before_subcommand_dispatch(tmp_path):
    """GPU/模型 exports 必須在 case dispatch 之前:status --strict 的 wrong-GPU
    檢查唯一來源是這些環境變數,放在 case 之後 status 路徑會拿不到期望值。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    content = (tmp_path / "home" / "start.sh").read_text(encoding="utf-8")
    dispatch = content.index('case "${1:-}"')
    assert content.index("unset ") < content.index("export AICODE_MODEL=") < dispatch
    assert content.index("export MAIN_GPU=") < dispatch
    assert content.index("export LLAMA_BIN=") < dispatch

def test_opencode_json_written_owner_only_and_dry_run_redacts_api_keys(tmp_path):
    """opencode.json 合併後帶著使用者 provider 的 apiKey:檔案必須 0600
    (不得把原本的 0600 重跑成 0644),--dry-run 印出的內容也不得出現金鑰原文。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/opencode").mkdir(parents=True)
    secret = "sk-live-super-secret-123"
    opencode_path = home / ".config/opencode/opencode.json"
    opencode_path.write_text(
        json.dumps({"provider": {"openrouter": {"options": {"apiKey": secret}}}}),
        encoding="utf-8",
    )
    opencode_path.chmod(0o600)

    dry = run(tmp_path, *YES_TWO_GPU, "--dry-run", "--models-dir", str(models))
    assert dry.returncode == 0, dry.stderr + dry.stdout
    assert secret not in dry.stdout
    assert "***redacted***" in dry.stdout
    assert "憑證類欄位值已遮罩" in dry.stdout
    assert stat.S_IMODE(opencode_path.stat().st_mode) == 0o600  # dry-run 不動檔案

    real = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert real.returncode == 0, real.stderr + real.stdout
    assert stat.S_IMODE(opencode_path.stat().st_mode) == 0o600
    merged = json.loads(opencode_path.read_text(encoding="utf-8"))
    # 遮罩只影響顯示,實際寫入的金鑰原樣保留
    assert merged["provider"]["openrouter"]["options"]["apiKey"] == secret

def test_restart_subprocess_env_is_sanitized(monkeypatch):
    """[R] 自動重啟的 quit/start 子程序不得繼承泛用 SESSION/override env:
    桌面環境的 SESSION 會讓 stop 殺錯無關 session、漏掉真正的 codetrail-rag。"""
    from scripts import set_config as sc

    monkeypatch.setenv("SESSION", "unrelated-desktop-session")
    monkeypatch.setenv("MAIN_SESSION", "custom-main")
    monkeypatch.setenv("AUX_SESSION", "custom-aux")
    monkeypatch.setenv("MAIN_GPU", "GPU-x")
    monkeypatch.setenv("KEEP_ME", "1")
    env = sc._sanitized_subprocess_env()
    assert "SESSION" not in env
    assert "MAIN_SESSION" not in env
    assert "AUX_SESSION" not in env
    assert "MAIN_GPU" not in env
    assert env.get("KEEP_ME") == "1"

    calls = []

    class _Result:
        returncode = 0

    def fake_run(cmd, check=False, env=None, **_kwargs):
        calls.append((list(cmd), env))
        return _Result()

    monkeypatch.setattr(sc.subprocess, "run", fake_run)
    rc = sc._restart_servers(Path("/fake/home/start.sh"))
    assert rc == 0
    assert len(calls) == 2
    assert calls[0][0][1].endswith("stop_servers.py")
    assert calls[0][0][2:4] == ["--scope", "all"]
    assert calls[1][0][1] == "/fake/home/start.sh"
    for _cmd, env in calls:
        assert env is not None
        assert "SESSION" not in env and "MAIN_GPU" not in env

def test_rerun_keeps_hand_edited_port_and_base_url(tmp_path):
    """port/base_url 屬使用者領域(本工具從不寫)→ 手改過的值重跑要原樣保留。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    deployment_path = tmp_path / "home" / ".config/codetrail/deployment.json"
    config = json.loads(deployment_path.read_text(encoding="utf-8"))
    config["services"]["main"]["port"] = 18080
    config["services"]["main"]["base_url"] = "http://127.0.0.1:18080"
    deployment_path.write_text(json.dumps(config, ensure_ascii=False), encoding="utf-8")

    rerun = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert rerun.returncode == 0, rerun.stderr + rerun.stdout
    assert "保留你手動設定的 services.main.port=18080" in rerun.stdout
    merged = json.loads(deployment_path.read_text(encoding="utf-8"))
    assert merged["services"]["main"]["port"] == 18080
    assert merged["services"]["main"]["base_url"] == "http://127.0.0.1:18080"
    # OpenCode 的 baseURL 必須跟著保留下來的 main endpoint,不能仍寫死 8080
    opencode = json.loads(
        (tmp_path / "home" / ".config/opencode/opencode.json").read_text(encoding="utf-8")
    )
    options = opencode["provider"]["llamacpp"]["options"]
    assert options["baseURL"] == "http://127.0.0.1:18080/v1"
    assert "對齊 deployment 的 main endpoint" in rerun.stdout

def test_opencode_config_env_var_is_honored(tmp_path):
    """OpenCode 與 config.py/aicode 都先讀 OPENCODE_CONFIG;set_config 寫死預設
    路徑會做出「顯示 PASS 但完全沒生效」的設定。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    custom = tmp_path / "custom" / "oc.json"
    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models),
                env_overrides={"OPENCODE_CONFIG": str(custom)})
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert "OPENCODE_CONFIG 已設定" in proc.stdout
    written = json.loads(custom.read_text(encoding="utf-8"))
    assert written["model"] == "llamacpp/big-chat-ud-q4-k-xl"
    assert not (tmp_path / "home" / ".config/opencode/opencode.json").exists()

def test_relative_models_dir_and_llama_bin_are_stored_absolute(tmp_path):
    """相對路徑立刻轉絕對:--models-dir ./models 不得走到最後 schema 驗證才爆;
    相對 LLAMA_BIN 不得原樣寫進 ~/start.sh(換目錄執行就找不到)。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    env = build_env(tmp_path)
    env["LLAMA_BIN"] = "./llama-server"
    proc = subprocess.run(
        ["bash", str(SCRIPT), "--skip-deps-check", *YES_TWO_GPU, "--no-preview",
         "--models-dir", "./models"],
        cwd=tmp_path,
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr + proc.stdout
    registry = json.loads(
        (tmp_path / "home" / ".config/codetrail/models.json").read_text(encoding="utf-8")
    )
    expected = str(models / "big-chat" / "big-chat-ud-q4_k_xl-00001-of-00002.gguf")
    assert registry["big-chat-ud-q4-k-xl"] == expected
    content = (tmp_path / "home" / "start.sh").read_text(encoding="utf-8")
    assert f"export LLAMA_BIN={tmp_path / 'llama-server'}" in content
    assert "export LLAMA_BIN=./llama-server" not in content

def test_opencode_merge_rebuilds_wrong_typed_sections_without_traceback(tmp_path):
    """合法 JSON 但 provider/mcp/models 型別錯誤:降級重建+變更說明,不得 traceback。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/opencode").mkdir(parents=True)
    opencode_path = home / ".config/opencode/opencode.json"
    opencode_path.write_text(
        json.dumps({"provider": [], "mcp": "not-an-object", "theme": "dark"}),
        encoding="utf-8",
    )
    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert "Traceback" not in proc.stderr
    assert "不是 JSON object" in proc.stdout
    merged = json.loads(opencode_path.read_text(encoding="utf-8"))
    assert merged["theme"] == "dark"
    assert isinstance(merged["provider"], dict) and "llamacpp" in merged["provider"]
    assert isinstance(merged["mcp"], dict) and "codetrail" in merged["mcp"]

    # provider.llamacpp.models 是 list 的變體同樣不得當機
    opencode_path.write_text(
        json.dumps({"provider": {"llamacpp": {"models": []}}}), encoding="utf-8"
    )
    proc = run(tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models))
    assert proc.returncode == 0, proc.stderr + proc.stdout
    merged = json.loads(opencode_path.read_text(encoding="utf-8"))
    assert "big-chat-ud-q4-k-xl" in merged["provider"]["llamacpp"]["models"]

def test_restore_last_backup_dry_run_previews_without_touching_files(tmp_path):
    """--restore-last-backup --dry-run 只預覽會做什麼,絕不動檔案。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    home = tmp_path / "home"
    (home / ".config/codetrail").mkdir(parents=True)
    (home / ".config/codetrail/models.json").write_text('{"marker": "/old.gguf"}', encoding="utf-8")
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0

    after_setup = (home / ".config/codetrail/models.json").read_text(encoding="utf-8")
    proc = run(tmp_path, "--restore-last-backup", "--dry-run")
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert "[dry-run]" in proc.stdout
    assert "會還原" in proc.stdout
    assert "會移除" in proc.stdout
    # 檔案完全沒動:還原目標仍是設定後內容,產物一個都沒消失
    assert (home / ".config/codetrail/models.json").read_text(encoding="utf-8") == after_setup
    assert (home / ".config/codetrail/deployment.json").exists()
    assert (home / ".config/opencode/opencode.json").exists()
    assert (home / "start.sh").exists()

def test_deployment_env_override_split_brain_warns(tmp_path):
    """AICODE_DEPLOYMENT_CONFIG 等 override 有設時要警告:aicode 會讀自訂檔、
    ~/start.sh 卻刻意 unset,兩邊將各用一份設定。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    proc = run(
        tmp_path, *YES_TWO_GPU, "--no-preview", "--models-dir", str(models),
        env_overrides={"AICODE_DEPLOYMENT_CONFIG": str(tmp_path / "custom-deploy.json")},
    )
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert "偵測到環境變數 AICODE_DEPLOYMENT_CONFIG" in proc.stdout
    assert "各用一份設定" in proc.stdout

def test_logs_accepts_count_and_follow_shorthand(tmp_path):
    """logs 依說明允許省略 role:logs 3 / logs -f 都要能用;多餘參數不得靜默忽略。"""
    write_fake_nvidia_smi(tmp_path / "bin", TWO_GPUS)
    models = make_models(tmp_path)
    assert run(tmp_path, *YES_TWO_GPU, "--no-preview",
                "--models-dir", str(models)).returncode == 0
    home = tmp_path / "home"
    start = home / "start.sh"
    state = home / ".local" / "state"
    log_dir = state / "codetrail" / "logs"
    log_dir.mkdir(parents=True)
    (log_dir / "main.log").write_text("line1\nline2\n", encoding="utf-8")
    env = build_env(tmp_path)
    env["XDG_STATE_HOME"] = str(state)

    def run_start(*args: str, timeout: float = 30):
        return subprocess.run(
            ["bash", str(start), *args],
            env=env, capture_output=True, text=True, timeout=timeout, check=False,
        )

    shorthand = run_start("logs", "3")   # 省略 role,數字當行數
    assert shorthand.returncode == 0, shorthand.stderr
    assert "line2" in shorthand.stdout

    extra = run_start("logs", "main", "5", "x")
    assert extra.returncode == 2
    assert "參數過多" in extra.stderr

    still_bad = run_start("logs", "gpu")  # 未知 role 仍要拒絕
    assert still_bad.returncode == 2
    assert "未知 role" in still_bad.stderr

    tail_args = tmp_path / "tail_args.txt"
    fake_tail = tmp_path / "bin" / "tail"
    fake_tail.write_text(
        "#!/usr/bin/env bash\n"
        "printf '%s\\n' \"$@\" > \"$AICODE_TEST_TAIL_ARGS\"\n",
        encoding="utf-8",
    )
    fake_tail.chmod(0o700)
    env["AICODE_TEST_TAIL_ARGS"] = str(tail_args)
    follow = run_start("logs", "-f")
    assert follow.returncode == 0, follow.stderr
    assert tail_args.read_text(encoding="utf-8").splitlines()[0] == "-f"
