"""`aicode` wrapper 的離線 CLI 契約:MCP wrapper 生成、舊設定自動修復、--model 轉發,
以及 `aicode attach` / `aicode web` 子指令(存取控制與參數轉發)。

合併自 tests/test_aicode_wrapper.py、tests/test_aicode_attach.py、
tests/test_aicode_web_access.py、tests/test_aicode_web_forwarding.py(2026-09-02)。
這四份原本都是 2026-08-20 從 test_cli.py / test_aicode_web.py 拆出來的:當時
test_cli.py 43 條 14.07s 是全套件最慢的單檔,每條測試都真的跑一次 aicode preflight
(約 0.4s),拆檔是為了讓分片能同時吃。行為與 assertion 未變;近似重複的案例改成
parametrize。

- wrapper:MCP wrapper 生成、舊 timeout 自動修復、--model 轉發、Code Mode fail-loud 閘。
- attach:純 client 子指令,以及「沒有子指令時不得誤觸 web/attach」的回歸。
- web 存取控制:root safety、非本機 hostname 的密碼閘、Tailscale 例外——全是
  「拒絕/放行」判斷,是 web 模式對外暴露面的守門測試。
- web 參數轉發:port / hostname 注入、額外參數直通、preflight-only 早退。
"""

from __future__ import annotations

import json
import os
import subprocess

import pytest

from tests._harness import (
    OFFLINE_CTX,
    OPENCODE_WEB_OLD_STUB,
    REPO_ROOT,
    bash_compatible_path,
    contains_subsequence,
    read_stub_args,
    require_git,
    require_working_bash,
    run_aicode_subcmd_with_stub,
    run_aicode_with_stub,
)

# ── 原 test_aicode_wrapper.py:MCP wrapper 生成、舊設定自動修復、--model 轉發 ──


def test_aicode_prepares_opencode_mcp_wrapper(tmp_path):
    """`aicode` should create the local MCP wrapper expected by opencode.json."""
    require_git()
    bash = require_working_bash()
    aicode_script = bash_compatible_path(bash, REPO_ROOT / "aicode")

    project = tmp_path / "project"
    project.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=project, check=True)
    subdir = project / "src"
    subdir.mkdir()
    home = tmp_path / "home"
    home.mkdir()
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    stub_opencode = bin_dir / "opencode"
    stub_opencode.write_text(
        "#!/usr/bin/env bash\n"
        'if [ "${1:-}" = "--version" ]; then printf \'1.18.21\\n\'; exit 0; fi\n'
        'if [ "${1:-}" = "debug" ] && [ "${2:-}" = "config" ]; then\n'
        "  printf '{}\\n'\n"
        "  exit 0\n"
        "fi\n"
        "exit 0\n",
        encoding="utf-8",
    )
    stub_opencode.chmod(0o700)

    env = {
        **os.environ,
        "HOME": str(home),
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "PYTHONIOENCODING": "utf-8",
        "AICODE_N_CTX": OFFLINE_CTX,
        # aicode 啟動會跑 ctx 安全閘,在 CI / 沒 GPU / inherited AICODE_MODEL
        # 的環境下會 refuse to start。這個 smoke test 只關心 MCP wrapper
        # 生成,不該被安全閘擋下。
        "AICODE_CTX_SAFETY_DISABLE": "1",
        "AICODE_REQUIRED_MODELS_CHECK_SKIP": "1",
        "AICODE_TOOL_CANARY_SKIP": "1",
        # CodeTrail 不再內建預設主模型, 啟動時要先解析。給個假值讓 resolve_main_model
        # 通過; 真正的主模型解析邏輯有自己的單元測試覆蓋。
        "AICODE_MODEL": "example-code-model:30b",
    }
    r = subprocess.run(
        [bash, aicode_script],
        cwd=subdir,
        capture_output=True,
        text=True,
        timeout=15,
        stdin=subprocess.DEVNULL,
        env=env,
    )

    assert r.returncode == 0, f"exit={r.returncode}\nstdout={r.stdout}\nstderr={r.stderr}"
    assert "[tool-health] SKIP" in r.stdout
    wrapper = project / ".opencode" / "run-codetrail-mcp"
    assert wrapper.is_file()
    assert os.access(wrapper, os.X_OK)
    content = wrapper.read_text(encoding="utf-8")
    assert "generated by CodeTrail aicode" in content
    assert "exec python3" in content and "mcp_server.py" in content
    assert "exec python" in content and "mcp_server.py" in content


@pytest.mark.smoke
def test_aicode_refuses_experimental_opencode_code_mode(tmp_path):
    """CodeTrail 的權限與 canary 契約要求 MCP tools 直接暴露。

    OpenCode Code Mode 會把它們收進單一 ``execute`` tool；若 wrapper 繼續啟動，
    使用者只會在較晚的 model canary 看到難以定位的 tool-call 失敗。
    """
    result, args_file = run_aicode_with_stub(
        tmp_path,
        [],
        env_extra={
            "AICODE_MODEL": "example-code-model:30b",
            "OPENCODE_EXPERIMENTAL_CODE_MODE": "true",
        },
    )

    assert result.returncode == 2
    assert "experimental Code Mode" in result.stderr
    assert "OPENCODE_EXPERIMENTAL_CODE_MODE=false" in result.stderr
    assert not args_file.exists()


def test_aicode_repairs_short_codetrail_timeout_before_starting_opencode(tmp_path):
    """更新 repo 後直接跑 aicode:舊的 10 秒 timeout 要在 client 啟動前修好,
    契約遷移(opencode_contract_check)也要接著補上寫入工具的 ask 核准閘與
    lessons instructions —— 這是舊安裝 git pull 後的無感升級路徑。"""
    config_path = tmp_path / "opencode.json"
    original = {
        "model": "llamacpp/local-model",
        "mcp": {
            "codetrail": {
                "type": "local",
                "enabled": True,
                "timeout": 10_000,
            }
        },
        "permission": {"*": "deny"},
    }
    config_path.write_text(
        json.dumps(original, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    result, args_file = run_aicode_with_stub(
        tmp_path,
        [],
        env_extra={
            "OPENCODE_CONFIG": str(config_path),
            "AICODE_MCP_TIMEOUT_CHECK_SKIP": "0",
        },
    )

    assert result.returncode == 0, (
        f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    updated = json.loads(config_path.read_text(encoding="utf-8"))
    assert updated["mcp"]["codetrail"]["timeout"] == 660_000
    # 原有 permission 保留;缺少的 ask 核准閘與 lessons instructions 被補上
    assert updated["permission"]["*"] == "deny"
    assert updated["permission"]["codetrail_record_lesson"] == "ask"
    assert updated["instructions"] == [".codetrail/lessons.md"]
    # 第一份備份是 timeout 修復前的原檔(契約遷移的備份接續編號)
    backup = config_path.with_name(config_path.name + ".codetrail.bak")
    assert json.loads(backup.read_text(encoding="utf-8")) == original
    assert "FIXED" in result.stdout
    assert read_stub_args(args_file) == []


@pytest.mark.parametrize(
    ("args", "env_extra", "expected"),
    [
        pytest.param(
            ["--model", "bare-model"], None, ["--model", "bare-model"], id="bare"
        ),
        pytest.param(
            ["-m", "llamacpp/some-model"], None, ["-m", "llamacpp/some-model"],
            id="custom_provider",
        ),
        pytest.param(["--model=bare-model"], None, ["--model=bare-model"], id="equals"),
        pytest.param(
            ["--model", "foo-bar"], {"AICODE_MODEL": "foo-bar"}, ["--model", "foo-bar"],
            id="env_and_cli_same",
        ),
    ],
)
def test_aicode_passes_through_model_arg(tmp_path, args, env_extra, expected):
    """新版 aicode 不再強加 provider prefix,使用者傳什麼就轉發什麼。

    - bare:`--model bare-model` 原樣轉發。
    - custom_provider:自定 provider(例如 llamacpp/foo)原樣轉發給 OpenCode;
      CodeTrail 自己會 strip 出 bare。
    - equals:`--model=foo` 形式也原樣轉發。
    - env_and_cli_same:env 和 CLI 解析到同一個 bare model 時不衝突,CLI 值原樣
      轉發給 OpenCode。
    """
    result, args_file = run_aicode_with_stub(tmp_path, args, env_extra)

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == expected


def test_aicode_rejects_external_ollama_provider_in_model_arg(tmp_path):
    """ollama/ openai/ 等已知外部 provider prefix 必須被 resolve_main_model 攔下。"""
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "ollama/bare-model"],
    )

    assert result.returncode != 0
    assert ("外部 provider" in result.stderr) or ("provider prefix" in result.stderr)


@pytest.mark.parametrize("args", [["--model"], ["-m"], ["--model", "--foo"]])
def test_aicode_missing_model_arg_value_fails_without_opencode_fallback(tmp_path, args):
    result, args_file = run_aicode_with_stub(tmp_path, args)

    assert result.returncode != 0
    assert "requires a model value" in result.stderr
    assert not args_file.exists()


def test_aicode_env_and_cli_model_conflict_fails_loud(tmp_path):
    result, args_file = run_aicode_with_stub(
        tmp_path,
        ["--model", "bar:baz"],
        {"AICODE_MODEL": "foo:bar"},
    )

    assert result.returncode != 0
    assert "different models" in result.stderr
    assert not args_file.exists()


def test_direct_contract_gate_precedes_launcher_writers_and_canaries():
    source = (REPO_ROOT / "aicode").read_text(encoding="utf-8")
    # 這一行同時是「相容性閘」與「把量到的 OpenCode 版本交給壓縮 plugin」的
    # 唯一入口(--print-version-env)。順序契約不變:任何 writer / canary 之前。
    gate = source.index(
        'if ! DIRECT_CONTRACT_OUT="$("$PYBIN" "$DIRECT_CONTRACT_CHECK" '
        '--root "$ROOT" --print-version-env)"; then'
    )
    first_wrapper_write = source.index("\nprepare_opencode_mcp_wrapper\n")
    first_config_fix = source.index("opencode_ctx_check.py\" --fix")
    model_canary = source.index('TOOL_CANARY="$CODETRAIL_HOME/scripts/tool_call_canary.py"')
    assert gate < first_wrapper_write < first_config_fix < model_canary
    assert source.index("  attach)") < gate
    assert source.index('SUBCMD="web"') < gate



@pytest.mark.parametrize("value,expected", [
    ("08", 8), ("010", 10), ("007", 7), ("3", 3), ("0", 0), ("x", 3), ("", 3),
])
def test_launch_delay_is_read_as_base_ten(value, expected):
    """倒數秒數帶前導零時,bash 會把它當八進位。

    `AICODE_LAUNCH_DELAY=08` 通得過 `[ "$x" -gt 0 ]`(test 用的是另一個
    parser),下一行 `$((launch_delay - 1))` 卻以 "value too great for base"
    失敗 —— 而 aicode 是 `set -e`,於是 wrapper 在 `exec opencode` 之前就結束:
    使用者只看到倒數的第一行,然後沒有 TUI。`010` 不會爆,但倒數 8 秒。

    這裡直接跑 `aicode` 裡那段正規化,不抄一份。
    """
    bash = require_working_bash()
    source = (REPO_ROOT / "aicode").read_text(encoding="utf-8")
    start = source.index('launch_delay="${AICODE_LAUNCH_DELAY:-3}"')
    snippet = source[start:source.index("esac", start) + len("esac")]
    proc = subprocess.run(
        [bash, "-euo", "pipefail", "-c",
         snippet + '\nprintf "%s %s\\n" "$launch_delay" "$((launch_delay - 1))"'],
        env={**os.environ, "AICODE_LAUNCH_DELAY": value},
        capture_output=True, text=True,
    )
    assert proc.returncode == 0, proc.stderr
    assert proc.stdout.split() == [str(expected), str(expected - 1)]

# ── 原 test_aicode_attach.py:`aicode attach` 子指令,以及沒有子指令時不得誤觸 web/attach ──

# ---- aicode attach -------------------------------------------------------


@pytest.mark.parametrize(
    ("args", "env_extra", "expected"),
    [
        pytest.param(["attach"], None, ["attach", "http://127.0.0.1:4096"], id="default_url"),
        pytest.param(
            ["attach"], {"AICODE_WEB_PORT": "5000"}, ["attach", "http://127.0.0.1:5000"],
            id="aicode_web_port_env",
        ),
        pytest.param(
            ["attach", "-c"], None, ["attach", "http://127.0.0.1:4096", "-c"], id="flag_only"
        ),
    ],
)
def test_aicode_attach_resolves_url(tmp_path, args, env_extra, expected):
    """attach 的 url 解析:
    - default_url:沒給 url → 預設 http://127.0.0.1:4096。
    - aicode_web_port_env:AICODE_WEB_PORT 改寫預設 port。
    - flag_only:第一個參數是 flag(非 url)時,用預設 url 並把 flag 轉發。
    """
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, args, env_extra=env_extra, set_model=False
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == expected


def test_aicode_attach_explicit_url_and_flags_forwarded(tmp_path):
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["attach", "http://host:9000", "-s", "SID", "-c"], set_model=False
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["attach", "http://host:9000", "-s", "SID", "-c"]


def test_aicode_attach_is_thin_no_wrapper_no_sandbox(tmp_path):
    """attach 是純 client:不做沙箱 root 檢查(AICODE_ROOT=/ 也不擋)、不準備 MCP wrapper。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["attach"], env_extra={"AICODE_ROOT": "/"}, set_model=False
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["attach", "http://127.0.0.1:4096"]
    # 純 client 不應建立 .opencode/run-codetrail-mcp launcher
    assert not (tmp_path / "project" / ".opencode" / "run-codetrail-mcp").exists()

# ---- regression: 既有 standalone TUI 路徑不受影響 -------------------------


def test_aicode_no_subcommand_does_not_trigger_web_or_attach(tmp_path):
    """spec E.4:無參數 → exec 純 opencode,不含 web/attach 子指令。"""
    result, args_file = run_aicode_subcmd_with_stub(tmp_path, [])

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    args = read_stub_args(args_file)
    assert args == []
    assert "web" not in args and "attach" not in args


def test_aicode_non_subcommand_first_arg_forwarded_verbatim(tmp_path):
    """第一個位置參數不是 web/attach(例如專案路徑)→ 完全走現行語義,原樣轉發。"""
    result, args_file = run_aicode_subcmd_with_stub(tmp_path, ["somedir"])

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["somedir"]


# ── 原 test_aicode_web_access.py:aicode web 的存取控制 ──


@pytest.mark.parametrize(
    ("aicode_root", "needle"),
    [
        pytest.param("/", "refusing AICODE_ROOT=/", id="root_slash"),
        pytest.param("__HOME__", "refusing AICODE_ROOT=$HOME", id="home_root"),
    ],
)
def test_aicode_web_rejects_unsafe_root(tmp_path, aicode_root, needle):
    """spec E.1:aicode web 從 /(root_slash)或 $HOME(home_root)啟動被拒
    (沿用既有沙箱 root 檢查)。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web"], env_extra={"AICODE_ROOT": aicode_root}
    )

    assert result.returncode != 0
    assert needle in result.stderr
    assert not args_file.exists()

def test_aicode_web_non_local_hostname_without_password_refused(tmp_path):
    """spec E.2:hostname 非 local 且未設密碼 → 拒絕啟動。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web", "--hostname", "0.0.0.0"]
    )

    assert result.returncode != 0
    assert "OPENCODE_SERVER_PASSWORD" in result.stderr
    assert not args_file.exists()

def test_aicode_web_non_local_hostname_with_password_allowed(tmp_path):
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path,
        ["web", "--hostname", "0.0.0.0"],
        env_extra={"OPENCODE_SERVER_PASSWORD": "s3cret"},
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    args = read_stub_args(args_file)
    assert args[0] == "web"
    assert contains_subsequence(args, ["--hostname", "0.0.0.0"])

def test_aicode_web_verified_tailscale_ip_without_password_allowed(tmp_path):
    """aicode_web 的窄例外:env、hostname、tailscale CLI 三者完全一致才放行。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path,
        ["web", "--hostname", "100.100.10.20"],
        env_extra={"AICODE_WEB_TAILSCALE_IP": "100.100.10.20"},
        tailscale_ip="100.100.10.20",
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert contains_subsequence(
        read_stub_args(args_file), ["--hostname", "100.100.10.20"]
    )
    assert "已驗證並只綁本機 Tailscale IPv4" in result.stdout

@pytest.mark.parametrize(
    ("hostname_ip", "tailscale_ip"),
    [
        pytest.param("100.100.10.20", "100.100.10.21", id="env_cannot_spoof_current_ip"),
        pytest.param("192.168.1.50", "192.168.1.50", id="non_cgnat_ip"),
    ],
)
def test_aicode_web_tailscale_exception_is_not_bypassable(tmp_path, hostname_ip, tailscale_ip):
    """Tailscale 例外的兩個反向案例,沒密碼都要拒絕:
    - env_cannot_spoof_current_ip:env 與 hostname 一致,但 tailscale CLI 回報的
      現行 IP 不同 → env 不能冒充現行 IP。
    - non_cgnat_ip:三者一致但不在 Tailscale CGNAT 範圍 → 不能套用例外。
    """
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path,
        ["web", "--hostname", hostname_ip],
        env_extra={"AICODE_WEB_TAILSCALE_IP": hostname_ip},
        tailscale_ip=tailscale_ip,
    )

    assert result.returncode != 0
    assert "OPENCODE_SERVER_PASSWORD" in result.stderr
    assert not args_file.exists()

@pytest.mark.parametrize(
    "mdns_flag",
    [pytest.param("--mdns", id="bare_flag"), pytest.param("--mdns=true", id="equals_form")],
)
def test_aicode_web_mdns_without_password_refused(tmp_path, mdns_flag):
    """--mdns 會翻成 0.0.0.0 廣播,視為非 loopback 暴露,未設密碼也要拒絕。
    yargs 也接受 --mdns=true(equals_form);不能靠 spelling 繞過非 loopback 密碼硬規則。"""
    result, args_file = run_aicode_subcmd_with_stub(tmp_path, ["web", mdns_flag])

    assert result.returncode != 0
    assert "OPENCODE_SERVER_PASSWORD" in result.stderr
    assert "mdns" in result.stderr.lower()
    assert not args_file.exists()

def test_aicode_web_localhost_hostname_allowed_without_password(tmp_path):
    """明確 --hostname localhost 仍屬 loopback,不需要密碼。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web", "--hostname", "localhost"]
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert contains_subsequence(read_stub_args(args_file), ["--hostname", "localhost"])


# ── 原 test_aicode_web_forwarding.py:aicode web 的參數轉發 ──


def test_aicode_web_default_port_and_hostname(tmp_path):
    """`aicode web` 注入固定 port 4096 + loopback hostname,並沿用既有前置(備好 MCP launcher)。"""
    result, args_file = run_aicode_subcmd_with_stub(tmp_path, ["web"])

    assert result.returncode == 0, f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["web", "--port", "4096", "--hostname", "127.0.0.1"]
    # web 沿用既有前置:CodeTrail MCP launcher 要被備好(對照 attach 的純 client)
    assert (tmp_path / "project" / ".opencode" / "run-codetrail-mcp").is_file()

def test_aicode_web_respects_aicode_web_port_env(tmp_path):
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web"], env_extra={"AICODE_WEB_PORT": "5000"}
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert read_stub_args(args_file) == ["web", "--port", "5000", "--hostname", "127.0.0.1"]

def test_aicode_web_forwards_extra_args_and_user_port(tmp_path):
    """使用者自帶 --port 覆寫預設;其餘參數原樣轉發 opencode web。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web", "--port", "7000", "--cors", "https://example.test"]
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    args = read_stub_args(args_file)
    assert args[0] == "web"
    assert contains_subsequence(args, ["--port", "7000"])
    assert contains_subsequence(args, ["--hostname", "127.0.0.1"])
    assert contains_subsequence(args, ["--cors", "https://example.test"])
    # 不應重複注入 --port(使用者已給)
    assert args.count("--port") == 1

def test_aicode_web_missing_port_value_fails(tmp_path):
    result, args_file = run_aicode_subcmd_with_stub(tmp_path, ["web", "--port"])

    assert result.returncode != 0
    assert "--port" in result.stderr
    assert not args_file.exists()

@pytest.mark.parametrize(
    "args",
    [pytest.param(["web"], id="web"), pytest.param([], id="tui")],
)
def test_aicode_preflight_only_exits_before_exec(tmp_path, args):
    """AICODE_PREFLIGHT_ONLY=1(aicode_web 前景預檢用):跑完全部前置後退出,不 exec OpenCode。
    web 路徑與 standalone TUI 路徑(tui)都要在 exec 之前退出。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, args, env_extra={"AICODE_PREFLIGHT_ONLY": "1"}
    )

    assert result.returncode == 0, f"exit={result.returncode}\nstderr={result.stderr}"
    assert "preflight-only" in result.stdout
    # 只有 web 能力偵測(web --help)會碰 stub;真正的 exec 不能發生
    assert not args_file.exists()

def test_aicode_web_old_opencode_prints_upgrade_and_exits(tmp_path):
    """spec E.3:舊版 opencode(web --help 無 synopsis)→ 印升級指引後退出,不 exec。"""
    result, args_file = run_aicode_subcmd_with_stub(
        tmp_path, ["web"], opencode_stub=OPENCODE_WEB_OLD_STUB
    )

    assert result.returncode != 0
    assert "opencode-ai@latest" in result.stderr
    assert not args_file.exists()
