#!/usr/bin/env python3
"""CodeTrail 一鍵設定精靈(`./set_config.sh` 的實作)。

流程(對應 README「Quick Start」step 6):
  1. 偵測 NVIDIA GPU(nvidia-smi)與 ~/models 內的 GGUF 模型並分類
     (主聊天 / embedding / reranker / VL+mmproj);偵測失敗會明確通知。
  2. 背景初步判定:GPU 數量與四類模型是否齊全,缺什麼直接列出。
  3.-6. 逐一詢問「主聊天模型、embedding、reranker、VL(+mmproj)」各用哪個檔案、
     放哪顆 GPU;並補上容易遺漏的重要參數(ctx、threads、offload 策略、
     OpenCode limit.context / MCP timeout / Python 直譯器路徑)。
  7. 產生:
     - ~/.config/codetrail/models.json     (主模型 registry key → GGUF 路徑,合併既有)
     - ~/.config/codetrail/deployment.json (deployment profile local override)
     - ~/.config/opencode/opencode.json    (OpenCode provider + MCP + 權限範本)
     - ~/start.sh                          (帶著推薦啟動參數呼叫 scripts/start-all.sh)
     既有檔案一律先備份成 *.bak-setconfig-<時間戳>,不會靜默覆蓋。

安全性:純 stdlib、不 eval / source 任何內容;所有寫入都是結構化 JSON 或
固定模板;GPU / 模型選擇沿用 deployment_profile.py 的封閉 allowlist 驗證。
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from deployment_profile import ProfileError, load_effective_profile  # noqa: E402

GIB = 1024**3
MIB = 1024**2
GENERATED_MARKER = "generated by CodeTrail set_config.sh"
DEFAULT_MAIN_CTX = 65536
DEFAULT_FIT_TARGET_MIB = 5120
OPENCODE_TIMEOUT_FALLBACK_MS = 660_000

_SHARD_RE = re.compile(r"^(?P<stem>.+)-(?P<idx>\d{5})-of-(?P<total>\d{5})\.gguf$", re.IGNORECASE)
_EMBED_TOKENS = (
    "embed",
    "bge-m3",
    "bge-large",
    "e5-",
    "gte-",
    "nomic-embed",
    "jina-embed",
    "snowflake-arctic-embed",
)
# 排序提示:偵測清單把符合 deployment profile 預設 key 的檔案排最前面當預設選項。
_DEFAULT_HINTS = {
    "embedding": ("bge-m3",),
    "reranker": ("qwen3-reranker",),
    "vl": ("qwen3.5-9b", "qwen3-vl"),
    "main": (),
}


class SetupError(RuntimeError):
    """偵測或驗證失敗;訊息會原樣通知使用者。"""


@dataclass(frozen=True)
class Gpu:
    index: int
    name: str
    total_mib: int
    free_mib: int
    uuid: str

    @property
    def selector(self) -> str:
        """啟動時綁 GPU 用的識別:UUID 比 index 穩(PCI 順序可能變)。"""
        return self.uuid if self.uuid and self.uuid != "N/A" else str(self.index)

    def describe(self) -> str:
        return f"GPU {self.index}: {self.name} | VRAM {self.total_mib} MiB(free {self.free_mib} MiB)"


@dataclass(frozen=True)
class ModelCandidate:
    path: Path            # 多 shard 模型固定指向第 1 片
    total_bytes: int      # 含所有 shard
    shards: int
    mmproj: Path | None = None

    def describe(self) -> str:
        size = f"{self.total_bytes / GIB:.1f} GB"
        extra = f",{self.shards} shards" if self.shards > 1 else ""
        mm = f" + mmproj: {self.mmproj.name}" if self.mmproj else ""
        return f"{self.path.name}({size}{extra}){mm}"


@dataclass
class Selection:
    role: str
    candidate: ModelCandidate
    gpu: Gpu
    mmproj: Path | None = None


@dataclass
class Plan:
    gpus: list[Gpu]
    main: Selection
    embedding: Selection
    reranker: Selection
    vl: Selection
    main_key: str
    ctx: int
    threads: int
    batch: int
    ubatch: int
    parameters: dict = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# 偵測
# ---------------------------------------------------------------------------

def detect_gpus() -> list[Gpu]:
    smi = shutil.which("nvidia-smi")
    if not smi:
        raise SetupError(
            "偵測失敗:找不到 nvidia-smi。請確認 NVIDIA 驅動已安裝,"
            "且 nvidia-smi 在 PATH 上(README §1)。"
        )
    proc = subprocess.run(
        [smi, "--query-gpu=index,name,memory.total,memory.free,uuid",
         "--format=csv,noheader,nounits"],
        capture_output=True,
        text=True,
        check=False,
        timeout=30,
    )
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip()
        raise SetupError(f"偵測失敗:nvidia-smi 執行失敗:{detail or '無輸出'}")
    gpus: list[Gpu] = []
    for line in proc.stdout.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 5 or not parts[0].isdecimal():
            continue
        try:
            total = int(parts[2])
            free = int(parts[3])
        except ValueError:
            total, free = 0, 0
        gpus.append(Gpu(index=int(parts[0]), name=parts[1], total_mib=total,
                        free_mib=free, uuid=parts[4]))
    if not gpus:
        raise SetupError("偵測失敗:nvidia-smi 沒有回報任何可用的 NVIDIA GPU。")
    return gpus


def _shard_info(path: Path) -> tuple[Path, int, int] | None:
    """多 shard GGUF:回傳 (第 1 片路徑, 總大小, shard 數);非 shard 回 None。"""
    match = _SHARD_RE.match(path.name)
    if not match:
        return None
    stem, total = match.group("stem"), match.group("total")
    siblings = sorted(
        sib
        for sib in path.parent.glob("*.gguf")
        if (m := _SHARD_RE.match(sib.name)) and m.group("stem") == stem and m.group("total") == total
    )
    first = path.parent / f"{stem}-00001-of-{total}.gguf"
    if not first.is_file():
        first = siblings[0]
    return first, sum(sib.stat().st_size for sib in siblings), len(siblings)


def scan_models(models_dir: Path) -> dict[str, list[ModelCandidate]]:
    if not models_dir.is_dir():
        raise SetupError(
            f"偵測失敗:找不到模型目錄 {models_dir}。"
            "請先依 README §2 下載 GGUF,或用 --models-dir 指定位置。"
        )
    ggufs = sorted(p for p in models_dir.rglob("*.gguf") if p.is_file())
    if not ggufs:
        raise SetupError(f"偵測失敗:{models_dir} 內沒有任何 .gguf 模型檔(README §2)。")

    mmprojs = [p for p in ggufs if "mmproj" in p.name.lower()]
    seen: set[Path] = set()
    candidates: dict[str, list[ModelCandidate]] = {
        "main": [], "embedding": [], "reranker": [], "vl": []
    }
    for path in ggufs:
        if "mmproj" in path.name.lower():
            continue
        shard = _shard_info(path)
        if shard:
            first, total_bytes, shards = shard
            if first in seen:
                continue
            seen.add(first)
            candidate = ModelCandidate(path=first, total_bytes=total_bytes, shards=shards)
        else:
            if path in seen:
                continue
            seen.add(path)
            candidate = ModelCandidate(path=path, total_bytes=path.stat().st_size, shards=1)

        haystack = f"{path.parent.name}/{path.name}".lower()
        sibling_mmproj = sorted(
            (mp for mp in mmprojs if mp.parent == path.parent),
            # 偏好 f16 mmproj(README §2.4 的預設下載)。
            key=lambda mp: (0 if "f16" in mp.name.lower() else 1, mp.name),
        )
        if "rerank" in haystack:
            candidates["reranker"].append(candidate)
        elif any(token in haystack for token in _EMBED_TOKENS):
            candidates["embedding"].append(candidate)
        else:
            if sibling_mmproj:
                candidates["vl"].append(
                    ModelCandidate(
                        path=candidate.path,
                        total_bytes=candidate.total_bytes,
                        shards=candidate.shards,
                        mmproj=sibling_mmproj[0],
                    )
                )
            candidates["main"].append(candidate)

    for role, entries in candidates.items():
        hints = _DEFAULT_HINTS[role]

        def sort_key(cand: ModelCandidate) -> tuple:
            hinted = 0 if any(h in str(cand.path).lower() for h in hints) else 1
            size = -cand.total_bytes if role == "main" else cand.total_bytes
            return (hinted, size, str(cand.path))

        entries.sort(key=sort_key)
    return candidates


def precheck(gpus: list[Gpu], candidates: dict[str, list[ModelCandidate]]) -> list[str]:
    """背景初步判定;不 OK 直接 SetupError 通知,可過但要注意的回傳 warning 清單。"""
    warnings: list[str] = []
    missing = {
        "main": "主聊天模型",
        "embedding": "embedding 模型(如 bge-m3)",
        "reranker": "reranker 模型(如 qwen3-reranker-0.6b)",
        "vl": "VL 模型 + mmproj(如 qwen3.5-9b)",
    }
    lacking = [label for role, label in missing.items() if not candidates[role]]
    if lacking:
        raise SetupError(
            "初步判定不通過:~/models 缺少必要模型類別 → " + "、".join(lacking)
            + "。下載方式見 README §2;四類模型都是硬性需求。"
        )
    if len(gpus) < 2:
        warnings.append(
            "只偵測到 1 顆 GPU:主模型與三顆附屬模型將共用同一顆卡(可以跑,"
            "但雙卡分工更穩;RTX 5090 單卡實測見 docs/verified-reference-5090.md)。"
        )
    return warnings


# ---------------------------------------------------------------------------
# 互動選擇
# ---------------------------------------------------------------------------

def _candidate_from_path(path: Path) -> ModelCandidate:
    """使用者直接給路徑時也要正確聚合多 shard 的總大小。"""
    shard = _shard_info(path)
    if shard:
        first, total_bytes, shards = shard
        return ModelCandidate(path=first, total_bytes=total_bytes, shards=shards)
    return ModelCandidate(path=path, total_bytes=path.stat().st_size, shards=1)


def _input(prompt: str) -> str:
    try:
        return input(prompt)
    except EOFError as exc:
        raise SetupError(
            "無互動輸入環境。請改用旗標(--main-model/--main-gpu/... 或 --yes 全用預設),"
            "見 ./set_config.sh --help。"
        ) from exc


def choose_candidate(
    role_label: str,
    entries: list[ModelCandidate],
    override: str | None,
    assume_yes: bool,
) -> ModelCandidate:
    if override is not None:
        if override.isdecimal():
            pick = int(override)
            if not 1 <= pick <= len(entries):
                raise SetupError(f"{role_label}:選項編號 {pick} 不在 1..{len(entries)}。")
            return entries[pick - 1]
        path = Path(override).expanduser()
        if not path.is_file() or path.suffix.lower() != ".gguf":
            raise SetupError(f"{role_label}:{override} 不是存在的 .gguf 檔。")
        return _candidate_from_path(path)
    if assume_yes:
        return entries[0]

    print(f"\n{role_label} — 偵測到的候選:")
    for pos, cand in enumerate(entries, start=1):
        marker = "(預設)" if pos == 1 else ""
        print(f"  [{pos}] {cand.describe()} {marker}")
    while True:
        raw = _input("請輸入編號(Enter 用預設,或直接貼 .gguf 絕對路徑): ").strip()
        if not raw:
            return entries[0]
        if raw.isdecimal() and 1 <= int(raw) <= len(entries):
            return entries[int(raw) - 1]
        path = Path(raw).expanduser()
        if path.is_file() and path.suffix.lower() == ".gguf":
            return _candidate_from_path(path)
        print(f"  無效輸入:{raw}(要嘛編號 1..{len(entries)},要嘛存在的 .gguf 路徑)")


def choose_gpu(
    role_label: str,
    gpus: list[Gpu],
    default: Gpu,
    override: str | None,
    assume_yes: bool,
) -> Gpu:
    by_index = {gpu.index: gpu for gpu in gpus}
    if override is not None:
        if not override.isdecimal() or int(override) not in by_index:
            raise SetupError(
                f"{role_label}:GPU index '{override}' 不在偵測結果中"
                f"(可用:{sorted(by_index)})。"
            )
        return by_index[int(override)]
    if assume_yes or len(gpus) == 1:
        return default

    print(f"{role_label} — 要放哪顆 GPU?")
    for gpu in gpus:
        marker = "(預設)" if gpu.index == default.index else ""
        print(f"  [{gpu.index}] {gpu.describe()} {marker}")
    while True:
        raw = _input(f"請輸入 GPU index(Enter 用預設 {default.index}): ").strip()
        if not raw:
            return default
        if raw.isdecimal() and int(raw) in by_index:
            return by_index[int(raw)]
        print(f"  無效的 GPU index:{raw}")


def choose_int(label: str, default: int, override: int | None, assume_yes: bool) -> int:
    if override is not None:
        if override < 1:
            raise SetupError(f"{label} 必須是正整數。")
        return override
    if assume_yes:
        return default
    while True:
        raw = _input(f"{label}(Enter 用預設 {default}): ").strip()
        if not raw:
            return default
        if raw.isdecimal() and int(raw) >= 1:
            return int(raw)
        print("  請輸入正整數。")


# ---------------------------------------------------------------------------
# 推薦參數
# ---------------------------------------------------------------------------

def _mem_total_bytes() -> int:
    try:
        with open("/proc/meminfo", encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("MemTotal:"):
                    return int(line.split()[1]) * 1024
    except (OSError, ValueError, IndexError):
        pass
    return 0


def _llama_bin() -> Path:
    return Path(os.environ.get("LLAMA_BIN") or (Path.home() / "llama.cpp" / "build" / "bin" / "llama-server"))


def _llama_supports_fit(notes: list[str]) -> bool:
    """探測 llama-server 是否支援 `--fit`(新版自動 VRAM 配置)。"""
    binary = _llama_bin()
    if not binary.is_file():
        notes.append(
            f"找不到 llama-server({binary});先假設是支援 --fit 的新版。"
            "若尚未 build,見 README §1.5。"
        )
        return True
    try:
        proc = subprocess.run(
            [str(binary), "--help"], capture_output=True, text=True, timeout=30, check=False
        )
    except (OSError, subprocess.TimeoutExpired):
        return True
    return "--fit" in (proc.stdout + proc.stderr)


def recommend_main(plan_gpu: Gpu, candidate: ModelCandidate, ctx: int, threads: int,
                   fit_target: int, notes: list[str]) -> tuple[dict, int, int]:
    """依主模型大小 vs 所選 GPU VRAM 推薦 offload 策略與 batch。"""
    parameters: dict = {
        "jinja": True,
        "flash_attention": "on",
        "cache_type_k": "q8_0",
        "cache_type_v": "q8_0",
        "threads": threads,
    }
    fits_in_vram = candidate.total_bytes <= plan_gpu.total_mib * MIB * 0.85
    if fits_in_vram:
        parameters["gpu_layers"] = 99
        batch, ubatch = 2048, 512
        notes.append(
            f"主模型 {candidate.total_bytes / GIB:.0f} GB 可整顆放進 "
            f"{plan_gpu.name}({plan_gpu.total_mib} MiB)→ 全 GPU offload(-ngl 99)。"
        )
    else:
        batch, ubatch = 1024, 256
        if _llama_supports_fit(notes):
            parameters.update(
                {"gpu_layers": "auto", "fit": "on", "fit_target": fit_target, "parallel": 1}
            )
            notes.append(
                f"主模型 {candidate.total_bytes / GIB:.0f} GB 超過 {plan_gpu.name} 的 VRAM → "
                f"用 llama.cpp 自動配置(-ngl auto --fit on --fit-target {fit_target}),"
                "由 server 自行決定 GPU/CPU 層分配。"
            )
        else:
            parameters["gpu_layers"] = 99
            notes.append(
                "⚠ 你的 llama-server 不支援 --fit,且主模型大於 VRAM —— 這樣啟動很可能 OOM。"
                "建議更新並重新 build llama.cpp(README §1.5),"
                "或自行在 ~/.config/codetrail/deployment.json 調 n_cpu_moe。"
            )
    mem_total = _mem_total_bytes()
    if mem_total and mem_total > candidate.total_bytes + 32 * GIB:
        parameters["no_mmap"] = True
        notes.append("系統 RAM 足夠 → 加 --no-mmap(啟動載入較慢,但首次回應不再等 page-in)。")
    else:
        notes.append("系統 RAM 不寬裕 → 不加 --no-mmap(維持 mmap 懶載入,首次回應可能較慢)。")
    notes.append("取樣參數(temp/top-p/top-k)刻意不寫死:各模型官方建議不同,"
                 "需要時自行加進 ~/.config/codetrail/deployment.json 的 services.main.parameters。")
    return parameters, batch, ubatch


def sanitize_registry_key(path: Path) -> str:
    """檔名 → 合法 registry key(deployment_profile 的 _BARE_MODEL_RE:不含底線)。"""
    stem = _SHARD_RE.match(path.name)
    name = stem.group("stem") if stem else path.stem
    key = re.sub(r"[^A-Za-z0-9.+:-]+", "-", name).strip("-").lower()
    key = re.sub(r"-{2,}", "-", key)
    if not key or not key[0].isalnum():
        key = f"model-{key.lstrip('-.')}" if key else "main-model"
    return key[:64]


# ---------------------------------------------------------------------------
# 產生設定檔
# ---------------------------------------------------------------------------

def _backup(path: Path, notes: list[str]) -> None:
    if path.exists():
        stamp = time.strftime("%Y%m%d-%H%M%S")
        backup = path.with_name(f"{path.name}.bak-setconfig-{stamp}")
        shutil.copy2(path, backup)
        notes.append(f"已備份原有 {path} → {backup.name}")


def _write_json(path: Path, data: dict, notes: list[str], dry_run: bool) -> None:
    payload = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=False) + "\n"
    if dry_run:
        print(f"\n--- [dry-run] 將寫入 {path} ---\n{payload}", end="")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    _backup(path, notes)
    tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}")
    tmp.write_text(payload, encoding="utf-8")
    tmp.replace(path)


def build_models_registry(plan: Plan, registry_path: Path, notes: list[str]) -> dict:
    existing: dict = {}
    if registry_path.is_file():
        try:
            loaded = json.loads(registry_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                existing = loaded
            else:
                notes.append(f"{registry_path} 不是 JSON object,將重建(原檔已備份)。")
        except (OSError, json.JSONDecodeError):
            notes.append(f"{registry_path} 無法解析,將重建(原檔已備份)。")
    existing[plan.main_key] = str(plan.main.candidate.path)
    return existing


def build_deployment_config(plan: Plan) -> dict:
    return {
        "schema_version": 1,
        "profile": "defaults",
        "services": {
            "main": {
                "model": plan.main_key,
                "ctx": plan.ctx,
                "batch": plan.batch,
                "ubatch": plan.ubatch,
                "parameters": plan.parameters,
            },
            "embedding": {"model": str(plan.embedding.candidate.path)},
            "reranker": {"model": str(plan.reranker.candidate.path)},
            "vl": {
                "model": str(plan.vl.candidate.path),
                "mmproj": str(plan.vl.mmproj),
            },
        },
    }


def _opencode_timeout_ms() -> int:
    config_text = (REPO_ROOT / "config.py").read_text(encoding="utf-8")
    match = re.search(r"^OPENCODE_MCP_TIMEOUT_MIN_MS\s*=\s*([0-9_]+)", config_text, re.MULTILINE)
    return int(match.group(1).replace("_", "")) if match else OPENCODE_TIMEOUT_FALLBACK_MS


def build_opencode_config(plan: Plan, python_bin: str) -> dict:
    mcp_command = (
        'root="${AICODE_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)}"; '
        f'AICODE_ROOT="$root" exec {shlex.quote(python_bin)} '
        f'{shlex.quote(str(REPO_ROOT / "mcp_server.py"))}'
    )
    return {
        "$schema": "https://opencode.ai/config.json",
        "share": "disabled",
        "autoupdate": False,
        "enabled_providers": ["llamacpp"],
        "model": f"llamacpp/{plan.main_key}",
        "small_model": f"llamacpp/{plan.main_key}",
        "provider": {
            "llamacpp": {
                "npm": "@ai-sdk/openai-compatible",
                "name": "llama.cpp local",
                "options": {"baseURL": "http://localhost:8080/v1", "apiKey": "dummy"},
                "models": {
                    plan.main_key: {
                        "name": plan.main_key,
                        "limit": {"context": plan.ctx, "output": 8192},
                    }
                },
            }
        },
        "mcp": {
            "codetrail": {
                "type": "local",
                "command": ["bash", "-lc", mcp_command],
                "enabled": True,
                "timeout": _opencode_timeout_ms(),
            }
        },
        "permission": {
            "*": "deny",
            "question": "allow",
            "todowrite": "allow",
            "codetrail_*": "allow",
            "codetrail_apply_patch": "ask",
            "codetrail_run_lint": "ask",
            "codetrail_run_command": "ask",
            "codetrail_import_external_file": "allow",
            "webfetch": "deny",
            "websearch": "deny",
            "bash": "deny",
            "read": "deny",
            "grep": "deny",
            "glob": "deny",
            "edit": "deny",
            "write": "deny",
            "apply_patch": "deny",
            "external_directory": "deny",
            "task": "deny",
            "skill": "deny",
            "lsp": "deny",
        },
    }


def _gpu_exports(plan: Plan) -> list[str]:
    aux = {plan.embedding.gpu.selector, plan.reranker.gpu.selector, plan.vl.gpu.selector}
    lines = [f"export MAIN_GPU={shlex.quote(plan.main.gpu.selector)}"]
    if len(aux) == 1:
        lines.append(f"export AUX_GPU={shlex.quote(next(iter(aux)))}")
    else:
        lines.append(f"export EMBED_GPU={shlex.quote(plan.embedding.gpu.selector)}")
        lines.append(f"export RERANK_GPU={shlex.quote(plan.reranker.gpu.selector)}")
        lines.append(f"export VL_GPU={shlex.quote(plan.vl.gpu.selector)}")
    return lines


def build_start_sh(plan: Plan) -> str:
    gpu_lines = "\n".join(f"#   {gpu.describe()}" for gpu in plan.gpus)
    offload = (
        "-ngl auto --fit on(自動 VRAM 配置)"
        if plan.parameters.get("fit") == "on"
        else "-ngl 99(全 GPU offload)"
    )
    exports = "\n".join(_gpu_exports(plan))
    return f"""#!/usr/bin/env bash
# {GENERATED_MARKER} — {time.strftime("%Y-%m-%d %H:%M:%S")}
# 重新設定:cd {REPO_ROOT} && ./set_config.sh
#
# 偵測到的 GPU:
{gpu_lines}
#
# 配置(模型 @ GPU index):
#   main      = {plan.main_key} @ GPU {plan.main.gpu.index}
#   embedding = {plan.embedding.candidate.path.name} @ GPU {plan.embedding.gpu.index}
#   reranker  = {plan.reranker.candidate.path.name} @ GPU {plan.reranker.gpu.index}
#   vl        = {plan.vl.candidate.path.name} @ GPU {plan.vl.gpu.index}
#
# 推薦啟動參數:ctx={plan.ctx}, threads={plan.parameters.get("threads")}, {offload}
#   完整參數在 ~/.config/codetrail/deployment.json;實際指令預覽:~/start.sh --dry-run
# 停止全部 server:{REPO_ROOT}/scripts/quit.sh
set -euo pipefail

export AICODE_MODEL={shlex.quote(plan.main_key)}
{exports}

exec {shlex.quote(str(REPO_ROOT / "scripts" / "start-all.sh"))} "$@"
"""


def write_start_sh(plan: Plan, start_path: Path, notes: list[str], dry_run: bool) -> None:
    content = build_start_sh(plan)
    if dry_run:
        print(f"\n--- [dry-run] 將寫入 {start_path} ---\n{content}", end="")
        return
    if start_path.exists() and GENERATED_MARKER not in start_path.read_text(
        encoding="utf-8", errors="replace"
    ):
        notes.append(f"{start_path} 已存在且不是 set_config 產生的;原檔已備份後才覆寫。")
    _backup(start_path, notes)
    tmp = start_path.with_name(f"{start_path.name}.tmp.{os.getpid()}")
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(0o755)
    tmp.replace(start_path)


# ---------------------------------------------------------------------------
# 驗證與預覽
# ---------------------------------------------------------------------------

def _detect_python(skip_deps_check: bool, notes: list[str]) -> str:
    """MCP server 要跑在哪個 Python:用執行 set_config 的這一顆,並驗證依賴齊全。

    把絕對路徑寫死進 opencode.json 的 MCP command,新 shell 不 activate venv
    也能啟動 MCP server(舊安裝流程最常踩的坑)。
    """
    python_bin = sys.executable or "python3"
    proc = subprocess.run(
        [python_bin, "-c", "import mcp, numpy, requests"],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    if proc.returncode != 0:
        message = (
            f"這顆 Python({python_bin})缺少 CodeTrail 依賴(mcp/numpy/requests)。\n"
            f"  安裝:{python_bin} -m pip install --user --break-system-packages -r "
            f"{REPO_ROOT / 'requirements.txt'}\n"
            "  (或先 activate 你的 venv 再重跑 ./set_config.sh)"
        )
        if skip_deps_check:
            notes.append("⚠ 已用 --skip-deps-check 跳過依賴檢查:" + message)
        else:
            raise SetupError("偵測失敗:" + message)
    return python_bin


# 這些 env 會蓋過剛寫好的設定檔;驗證/預覽時剔除,模擬「全新 shell 跑 ~/start.sh」。
_OVERRIDE_ENV_KEYS = (
    "AICODE_PROFILE", "AICODE_DEPLOYMENT_CONFIG", "AICODE_MODEL",
    "AICODE_MODEL_REGISTRY", "AICODE_MODEL_REGISTRY_FILE",
    "EMBED_MODEL", "RERANK_MODEL", "VL_GGUF", "VL_MMPROJ",
    "AICODE_EMBED_MODEL", "AICODE_RERANK_MODEL", "AICODE_VL_MODEL", "AICODE_VL_MMPROJ",
    "MAIN_GPU", "AUX_GPU", "EMBED_GPU", "RERANK_GPU", "VL_GPU", "CUDA_VISIBLE_DEVICES",
    "MAIN_CTX", "MAIN_BATCH", "MAIN_UBATCH",
)


def _fresh_env(plan: Plan) -> dict[str, str]:
    env = {key: value for key, value in os.environ.items() if key not in _OVERRIDE_ENV_KEYS}
    env["AICODE_MODEL"] = plan.main_key
    return env


def validate_effective_profile(plan: Plan, dry_run: bool) -> None:
    """寫檔後用 deployment_profile 真正載入一次,確保產物自洽。"""
    if dry_run:
        return
    try:
        load_effective_profile(_fresh_env(plan))
    except ProfileError as exc:
        raise SetupError(f"產生的設定未通過 deployment profile 驗證:{exc}") from exc


def preview_start_commands(plan: Plan) -> int:
    """跑 start-all.sh --dry-run,把最終 llama-server 指令(推薦參數)印給使用者。"""
    env = _fresh_env(plan)
    env["MAIN_GPU"] = plan.main.gpu.selector
    env["EMBED_GPU"] = plan.embedding.gpu.selector
    env["RERANK_GPU"] = plan.reranker.gpu.selector
    env["VL_GPU"] = plan.vl.gpu.selector
    proc = subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "start-all.sh"), "--dry-run"],
        env=env,
        capture_output=True,
        text=True,
        check=False,
        timeout=120,
    )
    print("\n=== 推薦啟動參數(~/start.sh 實際會執行的指令)===")
    if proc.stdout:
        print(proc.stdout, end="")
    if proc.returncode != 0:
        print(proc.stderr, end="", file=sys.stderr)
        print("⚠ 啟動參數預覽失敗(見上方訊息);請修正後重跑 ./set_config.sh。",
              file=sys.stderr)
    return proc.returncode


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="CodeTrail 一鍵設定:偵測 GPU/模型 → 互動選擇 → 產生設定檔與 ~/start.sh",
    )
    parser.add_argument("--models-dir", help="模型目錄(預設 $MODELS_DIR 或 ~/models)")
    parser.add_argument("--yes", action="store_true", help="全部採用偵測到的預設值,不互動")
    parser.add_argument("--dry-run", action="store_true", help="只顯示會寫入的內容,不動任何檔案")
    parser.add_argument("--skip-deps-check", action="store_true", help="跳過 Python 依賴檢查")
    for role in ("main", "embed", "rerank", "vl"):
        parser.add_argument(f"--{role}-model", help=f"{role} 模型:候選編號(從 1 起)或 .gguf 絕對路徑")
        parser.add_argument(f"--{role}-gpu", help=f"{role} 要綁的 GPU index")
    parser.add_argument("--vl-mmproj", help="VL mmproj .gguf 絕對路徑(預設自動配對同目錄 mmproj)")
    parser.add_argument("--ctx", type=int, help=f"主模型 context(-c),預設 {DEFAULT_MAIN_CTX}")
    parser.add_argument("--threads", type=int, help="主模型 CPU threads(-t),預設 nproc/2")
    parser.add_argument("--fit-target", type=int, default=DEFAULT_FIT_TARGET_MIB,
                        help=f"--fit-target MiB(預設 {DEFAULT_FIT_TARGET_MIB})")
    parser.add_argument("--no-preview", action="store_true", help="結尾不跑 start-all.sh --dry-run 預覽")
    return parser


def run(args: argparse.Namespace) -> int:
    notes: list[str] = []
    home = Path(os.path.expanduser("~"))
    models_dir = Path(args.models_dir or os.environ.get("MODELS_DIR") or (home / "models")).expanduser()

    print("=== CodeTrail set_config ===")
    python_bin = _detect_python(args.skip_deps_check, notes)
    print(f"[1/4] Python(MCP server 用):{python_bin}")

    gpus = detect_gpus()
    print(f"[2/4] 偵測到 {len(gpus)} 顆 NVIDIA GPU:")
    for gpu in gpus:
        print(f"      {gpu.describe()}")

    candidates = scan_models(models_dir)
    print(f"[3/4] 掃描 {models_dir}:main={len(candidates['main'])}、"
          f"embedding={len(candidates['embedding'])}、reranker={len(candidates['reranker'])}、"
          f"vl={len(candidates['vl'])} 個候選")

    warnings = precheck(gpus, candidates)
    print("[4/4] 初步判定 OK:GPU 與四類模型(main / embedding / reranker / vl+mmproj)齊全")
    for warning in warnings:
        print(f"      ⚠ {warning}")

    # GPU 預設:main 給 VRAM 最大那顆;三顆附屬模型共用「另一顆」VRAM 最大者(單卡則同顆)。
    main_gpu_default = max(gpus, key=lambda gpu: gpu.total_mib)
    others = [gpu for gpu in gpus if gpu.index != main_gpu_default.index]
    aux_gpu_default = max(others, key=lambda gpu: gpu.total_mib) if others else main_gpu_default

    main_cand = choose_candidate("【主聊天模型】", candidates["main"], args.main_model, args.yes)
    main_gpu = choose_gpu("【主聊天模型】", gpus, main_gpu_default, args.main_gpu, args.yes)
    embed_cand = choose_candidate("【embedding 模型】", candidates["embedding"], args.embed_model, args.yes)
    embed_gpu = choose_gpu("【embedding 模型】", gpus, aux_gpu_default, args.embed_gpu, args.yes)
    rerank_cand = choose_candidate("【reranker 模型】", candidates["reranker"], args.rerank_model, args.yes)
    rerank_gpu = choose_gpu("【reranker 模型】", gpus, aux_gpu_default, args.rerank_gpu, args.yes)
    vl_cand = choose_candidate("【VL 模型】", candidates["vl"], args.vl_model, args.yes)
    vl_gpu = choose_gpu("【VL 模型】", gpus, aux_gpu_default, args.vl_gpu, args.yes)

    if args.vl_mmproj:
        vl_mmproj = Path(args.vl_mmproj).expanduser()
        if not vl_mmproj.is_file() or vl_mmproj.suffix.lower() != ".gguf":
            raise SetupError(f"VL mmproj:{args.vl_mmproj} 不是存在的 .gguf 檔。")
    else:
        vl_mmproj = vl_cand.mmproj
        if vl_mmproj is None:
            sibling = sorted(vl_cand.path.parent.glob("*mmproj*.gguf"))
            if not sibling:
                raise SetupError(
                    f"VL 模型 {vl_cand.path.name} 同目錄找不到 mmproj *.gguf;"
                    "請用 --vl-mmproj 指定(README §2.4)。"
                )
            vl_mmproj = sibling[0]
    print(f"      VL mmproj:{vl_mmproj}")

    default_threads = max(4, (os.cpu_count() or 8) // 2)
    ctx = choose_int("主模型 context(-c)", DEFAULT_MAIN_CTX, args.ctx, args.yes)
    threads = choose_int("主模型 CPU threads(-t)", default_threads, args.threads, args.yes)

    parameters, batch, ubatch = recommend_main(
        main_gpu, main_cand, ctx, threads, args.fit_target, notes
    )
    plan = Plan(
        gpus=gpus,
        main=Selection("main", main_cand, main_gpu),
        embedding=Selection("embedding", embed_cand, embed_gpu),
        reranker=Selection("reranker", rerank_cand, rerank_gpu),
        vl=Selection("vl", vl_cand, vl_gpu, mmproj=vl_mmproj),
        main_key=sanitize_registry_key(main_cand.path),
        ctx=ctx,
        threads=threads,
        batch=batch,
        ubatch=ubatch,
        parameters=parameters,
    )

    codetrail_dir = home / ".config" / "codetrail"
    opencode_path = home / ".config" / "opencode" / "opencode.json"
    start_path = home / "start.sh"

    registry = build_models_registry(plan, codetrail_dir / "models.json", notes)
    _write_json(codetrail_dir / "models.json", registry, notes, args.dry_run)
    _write_json(codetrail_dir / "deployment.json", build_deployment_config(plan), notes, args.dry_run)
    _write_json(opencode_path, build_opencode_config(plan, python_bin), notes, args.dry_run)
    write_start_sh(plan, start_path, notes, args.dry_run)
    validate_effective_profile(plan, args.dry_run)

    print("\n=== 設定摘要 ===")
    print(f"  main      : {plan.main.candidate.path}(key={plan.main_key})@ GPU {main_gpu.index}")
    print(f"  embedding : {embed_cand.path} @ GPU {embed_gpu.index}")
    print(f"  reranker  : {rerank_cand.path} @ GPU {rerank_gpu.index}")
    print(f"  vl        : {vl_cand.path} + {vl_mmproj.name} @ GPU {vl_gpu.index}")
    print(f"  ctx={ctx}、threads={threads}、batch={batch}、ubatch={ubatch}")
    for note in notes:
        print(f"  - {note}")
    if not args.dry_run:
        print("\n已產生:")
        print(f"  {codetrail_dir / 'models.json'}")
        print(f"  {codetrail_dir / 'deployment.json'}")
        print(f"  {opencode_path}(OpenCode limit.context 已對齊 -c {ctx};MCP timeout 已設)")
        print(f"  {start_path}")

    preview_rc = 0
    if not args.dry_run and not args.no_preview:
        preview_rc = preview_start_commands(plan)

    print("\n下一步:")
    print("  ~/start.sh                        # 啟動四個 llama-server(tmux)")
    print(f"  {REPO_ROOT}/scripts/check-status.sh --strict")
    print("  cd <你要分析的專案> && aicode      # 進 TUI;/status 應顯示 codetrail Connected")
    print(f"  {REPO_ROOT}/scripts/quit.sh       # 收工:關掉全部 tmux server 視窗")
    return 1 if preview_rc != 0 else 0


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        return run(args)
    except SetupError as exc:
        print(f"\n[set_config] {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\n[set_config] 已取消。(已寫入的檔案都有 .bak-setconfig-* 備份可還原)", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
