#!/usr/bin/env python3
"""CodeTrail 一鍵設定精靈(`./set_config.sh` 的實作)。

純問答式設定:不做容量估算、不推薦主模型數值；使用者選擇題由
使用者作答,工具只驗證輸入在合理範圍(例如選項只有 1..2 卻輸入 3 會重問)。
VRAM 塞不塞得下以啟動後實測為準(產生的 ~/start.sh 啟動完會提醒用
nvidia-smi 稍微監控)。

  1. 前置檢查:Python 依賴、tmux、nvidia-smi、llama-server 與必要旗標
     (--reranking / --mmproj / --fit),缺什麼就給可直接複製的修復指令。
  2. 偵測:GPU 種類/VRAM、~/models 的 GGUF 自動分類(main / embedding /
     reranker / VL+mmproj);多 shard 聚合並驗證齊全性(缺片直接列出)。
  3. 背景初步判定:GPU 數與四類模型是否齊全,缺什麼通知什麼。
  4. 互動問答:各角色模型與 GPU、主模型 CPU-MoE / 一般模式(MoE 主模型
     才詢問;CPU-MoE 之下可再輸入 --n-cpu-moe 檔位)、主模型 ctx / threads。
     reranker internal buffer 自動 8192(進階才用 --rerank-ctx 覆寫)。
     只有一個候選(或一顆 GPU)時自動選用;
     其餘必答。最後顯示摘要一頁(Enter 寫入 / q 離開)。
  5. 非互動:`--yes` 跳過提問與確認,但所有使用者選擇題的值必須由旗標提供
     (--main-model / --ctx / ...),缺哪個就明確報錯。
  6. 產物(先寫 staging、全部就緒才原子替換;既有檔備份 *.bak-setconfig-*):
     - ~/.config/codetrail/models.json     主模型 registry(合併既有)
     - ~/.config/codetrail/deployment.json deployment local override
     - ~/.config/opencode/opencode.json    只合併 CodeTrail 管的欄位,
                                           保留使用者既有 provider / mcp / 其他設定
     - ~/start.sh                          啟動腳本(支援 status / stop / logs 子命令)
  7. 安全預設:llama-server 只綁 127.0.0.1;要讓其他機器連線必須明確
     `--allow-remote`(或 deployment.json 的 bind: "all-interfaces")。

`--restore-last-backup` 可把四個產物還原到最近一次備份。
純 stdlib;不 eval / source 任何內容;產物經 deployment_profile 的封閉 schema 驗證。
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import struct
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from deployment_profile import (  # noqa: E402
    _BARE_MODEL_RE,  # registry key 合法性的唯一定義處(避免本檔複製一份造成分叉)
    RUNTIME_OVERRIDE_ENV_KEYS,
    ProfileError,
    load_effective_profile,
)

GIB = 1024**3
MIB = 1024**2
GENERATED_MARKER = "generated by CodeTrail set_config.sh"
# CLI 與互動輸入共用同一組上下限:兩邊不一致會讓互動寫入 CLI 明令拒絕的值。
# 上限對齊 deployment schema;本工具只做範圍驗證,不做容量估算。
MIN_MAIN_CTX = 1024
MAX_MAIN_CTX = 1_048_576
MIN_RERANKER_CTX = 128
MAX_RERANKER_CTX = 1_048_576
DEFAULT_RERANKER_CTX = 8192
MAX_THREADS = 1024
MAX_N_CPU_MOE = 1024
OPENCODE_TIMEOUT_FALLBACK_MS = 660_000

_SHARD_RE = re.compile(r"^(?P<stem>.+)-(?P<idx>\d{5})-of-(?P<total>\d{5})\.gguf$", re.IGNORECASE)
_EMBED_TOKENS = (
    "embed",
    "bge-m3",
    "bge-large",
    "e5-",
    "gte-",
    "nomic-embed",
    "jina-embed",
    "snowflake-arctic-embed",
)
# 排序提示:維護者驗證過的檔案排在候選清單前面(只影響列出順序;
# 沒有預設值,選哪個仍由使用者輸入編號決定)。附屬模型的提示也用來標記
# 「維護者驗證過」(選了其他檔會提示未驗證)。
_VERIFIED_HINTS = {
    "embedding": ("bge-m3",),
    "reranker": ("bge-reranker-v2-m3", "qwen3-reranker"),
    "vl": ("qwen3.5-9b", "qwen3-vl"),
    # docs/verified-reference-5090.md 的實測主模型。
    "main": ("qwen3-235b-a22b-thinking-2507",),
}

# 這些 env 會蓋過設定檔;驗證/預覽時剔除,產生的 ~/start.sh 也會先 unset,
# 模擬「全新 shell」行為,避免 .bashrc 裡的舊 override 讓新設定看似無效。
# 唯一來源是 deployment_profile.RUNTIME_OVERRIDE_ENV_KEYS(loader 讀哪些就清哪些)。
_OVERRIDE_ENV_KEYS = RUNTIME_OVERRIDE_ENV_KEYS
# tmux session 名稱不屬於 deployment 設定,但 start.sh 內也要一併清掉,
# 確保 launch / stop 兩條路看到同一組 session 名。
_SESSION_ENV_KEYS = ("MAIN_SESSION", "AUX_SESSION", "SESSION")

AUX_PARALLEL = 1                        # 本地單使用者服務不預留四個同時 request slot
VL_FIT_TARGET_MIB = 3 * 1024            # VL 最後啟動後仍保留給 mmproj / inference transient

# llama.cpp --cpu-moe 使用的 expert tensor 命名規則。這裡刻意對齊
# common/arg.cpp::llm_ffn_exps_cpu_override(),不靠模型檔名猜是不是 MoE。
_CPU_MOE_TENSOR_RE = re.compile(
    r"(?:^|\.)ffn_(?:up|down|gate_up|gate)_(?:ch)?exps(?:\.|$)"
)
# --n-cpu-moe 以 block 編號劃界(blk.0..N-1 的 experts 留 CPU),
# 推薦值因此需要 per-layer 的 expert storage。
_BLK_INDEX_RE = re.compile(r"(?:^|\.)blk\.(\d+)\.")
_GGUF_FIXED_TYPES: dict[int, tuple[str, int]] = {
    0: ("<B", 1),   # UINT8
    1: ("<b", 1),   # INT8
    2: ("<H", 2),   # UINT16
    3: ("<h", 2),   # INT16
    4: ("<I", 4),   # UINT32
    5: ("<i", 4),   # INT32
    6: ("<f", 4),   # FLOAT32
    7: ("<?", 1),   # BOOL
    10: ("<Q", 8),  # UINT64
    11: ("<q", 8),  # INT64
    12: ("<d", 8),  # FLOAT64
}


class SetupError(RuntimeError):
    """偵測或驗證失敗;訊息會原樣通知使用者(含修復指令)。"""


# commit_files 完成實際寫入後設為 True;Ctrl-C 的訊息依此區分
# 「設定未寫入」與「設定已寫完、只是中斷了後續預覽/重啟」兩種情境。
_COMMITTED = False


@dataclass(frozen=True)
class Gpu:
    index: int
    name: str
    total_mib: int
    free_mib: int
    uuid: str

    @property
    def selector(self) -> str:
        """啟動時綁 GPU 用的識別:UUID 比 index 穩(PCI 順序可能變)。"""
        return self.uuid if self.uuid and self.uuid != "N/A" else str(self.index)

    def describe(self) -> str:
        return f"GPU {self.index}: {self.name} | VRAM {self.total_mib} MiB(free {self.free_mib} MiB)"


@dataclass(frozen=True)
class ModelCandidate:
    path: Path            # 多 shard 模型固定指向第 1 片
    total_bytes: int      # 含所有 shard
    shards: int
    mmproj: Path | None = None            # 目錄內唯一 mmproj 時的自動配對
    mmproj_choices: tuple[Path, ...] = () # 目錄內有多個 mmproj 時的候選(需使用者選)
    vl_paired: bool = False               # 有 mmproj 配對的 VL 模型(不自動當 main)
    mmproj_ambiguous: bool = False        # 混放目錄:多顆模型共用 mmproj,歸屬需明確確認

    def describe(self) -> str:
        size = f"{self.total_bytes / GIB:.1f} GB"
        extra = f",{self.shards} shards" if self.shards > 1 else ""
        mm = f" + mmproj: {self.mmproj.name}" if self.mmproj else ""
        if not self.mmproj and self.mmproj_ambiguous:
            mm = "(混放目錄:mmproj 歸屬需明確確認)"
        elif not self.mmproj and self.mmproj_choices:
            mm = f"(同目錄有 {len(self.mmproj_choices)} 個 mmproj,需選擇)"
        vl = "(VL 模型)" if self.vl_paired and not mm else ""
        return f"{self.path.name}({size}{extra}){mm}{vl}"


@dataclass(frozen=True)
class ModelLayout:
    """從 GGUF tensor table 取得的 placement 資訊(不讀 tensor 內容)。"""

    tensor_bytes: int
    expert_bytes: int
    # (block 編號, 該層 expert storage bytes),block 編號由小到大;
    # 供 --n-cpu-moe 提問顯示層數範圍與「超過最大編號=全放 RAM」判斷,非 MoE 為空。
    expert_layer_bytes: tuple[tuple[int, int], ...] = ()

    @property
    def is_moe(self) -> bool:
        return self.expert_bytes > 0


@dataclass
class Selection:
    role: str
    candidate: ModelCandidate
    gpu: Gpu
    mmproj: Path | None = None


@dataclass
class Plan:
    gpus: list[Gpu]
    main: Selection
    embedding: Selection
    reranker: Selection
    vl: Selection
    main_key: str
    ctx: int
    threads: int
    batch: int
    ubatch: int
    reranker_ctx: int
    cpu_moe: bool = False
    # 部分 CPU-MoE 檔位(僅 CPU-MoE 模式有意義):使用者輸入的值
    # (互動題或 --n-cpu-moe 旗標);None = 全部 experts 放 RAM(--cpu-moe)。
    n_cpu_moe: int | None = None
    main_layout: ModelLayout | None = None
    allow_remote: bool = False
    parameters: dict = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# 前置檢查(缺什麼 → 可複製的修復指令)
# ---------------------------------------------------------------------------

def _pip_fix_hint(python_bin: str) -> str:
    """缺依賴時可直接複製的修復指令;venv 的 pip 會拒絕 --user,兩種環境分開建議。"""
    requirements = REPO_ROOT / "requirements.txt"
    if sys.prefix != getattr(sys, "base_prefix", sys.prefix):
        return (
            f"{python_bin} -m pip install -r {requirements}\n"
            "  (這顆 Python 在 venv 內:直接裝進 venv,不要加 --user)"
        )
    return (
        f"{python_bin} -m pip install --user --break-system-packages -r {requirements}\n"
        "  (或先 activate 你的 venv 再重跑 ./set_config.sh)"
    )


def _detect_python(skip_deps_check: bool, notes: list[str]) -> str:
    """MCP server 要跑在哪個 Python:用執行 set_config 的這一顆,並驗證依賴齊全。

    把絕對路徑寫死進 opencode.json 的 MCP command,新 shell 不 activate venv
    也能啟動 MCP server(舊安裝流程最常踩的坑)。
    """
    python_bin = sys.executable or "python3"
    try:
        proc = subprocess.run(
            [python_bin, "-c", "import mcp, numpy, requests"],
            capture_output=True,
            text=True,
            check=False,
            timeout=60,
        )
    except subprocess.TimeoutExpired as exc:
        message = (
            f"Python 依賴檢查逾時(60 秒):{python_bin}\n"
            "  可能是 NFS/磁碟卡住或 site-packages 損壞;"
            "先在終端手動執行一次上述 Python 確認,再重跑 ./set_config.sh"
        )
        if skip_deps_check:
            notes.append("⚠ 已用 --skip-deps-check 跳過依賴檢查:" + message)
            return python_bin
        raise SetupError("[FAIL] " + message) from exc
    if proc.returncode != 0:
        message = (
            f"這顆 Python({python_bin})缺少 CodeTrail 依賴(mcp/numpy/requests)。\n"
            f"  修復:{_pip_fix_hint(python_bin)}"
        )
        if skip_deps_check:
            notes.append("⚠ 已用 --skip-deps-check 跳過依賴檢查:" + message)
        else:
            raise SetupError("[FAIL] Python 依賴檢查未通過:\n" + message)
    return python_bin


def _check_tmux(skip: bool, notes: list[str]) -> None:
    if shutil.which("tmux"):
        return
    message = (
        "[FAIL] 找不到 tmux(啟動器用它把四個 server 放到背景)。\n"
        "  Ubuntu / Debian 修復:sudo apt install -y tmux\n"
        "  修復後重新執行:./set_config.sh"
    )
    if skip:
        notes.append("⚠ 已用 --skip-binary-check 跳過 tmux 檢查。")
        return
    raise SetupError(message)


def _llama_bin() -> Path:
    """LLAMA_BIN 一律轉成絕對路徑:相對路徑在這裡驗證會過(對 set_config 的 cwd),
    但寫進 ~/start.sh 後從別的目錄執行就找不到 binary。"""
    raw = os.environ.get("LLAMA_BIN")
    if raw:
        return Path(os.path.abspath(os.path.expanduser(raw)))
    return Path.home() / "llama.cpp" / "build" / "bin" / "llama-server"


def check_llama_binary(skip: bool, notes: list[str]) -> dict[str, bool]:
    """llama-server 存在性 + 必要旗標探測;回傳 fit / cpu_moe capabilities。"""
    binary = _llama_bin()
    if not binary.is_file() or not os.access(binary, os.X_OK):
        message = (
            f"[FAIL] 找不到可執行的 llama-server:{binary}\n"
            "  尚未 build 的話照 README §1.5:\n"
            "    git clone https://github.com/ggerganov/llama.cpp ~/llama.cpp\n"
            "    cd ~/llama.cpp && cmake -B build -DGGML_CUDA=ON -DLLAMA_CURL=OFF && "
            "cmake --build build --config Release -j\n"
            "  放在別處的話:export LLAMA_BIN=/path/to/llama-server 後重跑 ./set_config.sh"
        )
        if skip:
            notes.append("⚠ 已用 --skip-binary-check 跳過 llama-server 檢查(假設為支援 --fit 的新版)。")
            return {"fit": True, "cpu_moe": True, "n_cpu_moe": True}
        raise SetupError(message)
    try:
        proc = subprocess.run(
            [str(binary), "--help"], capture_output=True, text=True, timeout=30, check=False
        )
        help_text = proc.stdout + proc.stderr
    except (OSError, subprocess.TimeoutExpired) as exc:
        # 連 --help 都跑不動的 binary 不能假定支援任何旗標:非明確 skip 一律硬停,
        # 否則會在 [2/5] 顯示 PASS、到 ~/start.sh 才發現整組啟動不了。
        message = (
            f"[FAIL] llama-server --help 無法執行:{binary}\n"
            f"    {exc}\n"
            "  可能是 binary 損壞、架構不符或執行環境問題(動態庫/權限)。\n"
            f"  先在終端執行 {binary} --help 確認,再重跑 ./set_config.sh"
        )
        if skip:
            notes.append(
                "⚠ 已用 --skip-binary-check 跳過 llama-server 執行檢查"
                f"(--help 無法執行:{exc};假設支援全部旗標)。"
            )
            return {"fit": True, "cpu_moe": True, "n_cpu_moe": True}
        raise SetupError(message) from exc

    # --help 跑不起來(常見:動態庫找不到)時,help_text 是 loader 錯誤而不是旗標清單。
    # 這種情況不能誤診成「build 不支援 --reranking」,要指向真正的執行環境問題。
    recognized = any(
        flag in help_text for flag in ("--reranking", "--mmproj", "--fit", "--port", "usage:")
    )
    if proc.returncode != 0 and not recognized:
        detail = "\n    ".join(
            line for line in (proc.stderr or proc.stdout).strip().splitlines()[:5]
        )
        message = (
            f"[FAIL] llama-server 無法執行(--help 失敗,exit {proc.returncode}):{binary}\n"
            f"    {detail or '(無輸出)'}\n"
            "  這通常不是旗標支援問題,而是執行環境問題:\n"
            "  - 動態庫找不到(例如 libcudart / libcublas):把 CUDA lib 目錄加進 LD_LIBRARY_PATH\n"
            "  - binary 損壞或架構不符:重新 build llama.cpp(README §1.5)\n"
            f"  修好後先在終端執行 {binary} --help 確認,再重跑 ./set_config.sh"
        )
        if skip:
            notes.append("⚠ 已用 --skip-binary-check 跳過 llama-server 執行檢查(--help 失敗)。")
            return {"fit": True, "cpu_moe": True, "n_cpu_moe": True}
        raise SetupError(message)

    missing = [flag for flag in ("--reranking", "--mmproj") if flag not in help_text]
    if missing:
        message = (
            f"[FAIL] 這個 llama-server 不支援 {' / '.join(missing)}"
            "(reranker / VL 角色必要)。\n"
            "  修復:更新並重新 build llama.cpp(README §1.5):\n"
            "    cd ~/llama.cpp && git pull && rm -rf build && "
            "cmake -B build -DGGML_CUDA=ON -DLLAMA_CURL=OFF && cmake --build build --config Release -j"
        )
        if skip:
            notes.append("⚠ 已跳過 llama-server 旗標檢查:" + " / ".join(missing) + " 不支援。")
        else:
            raise SetupError(message)
    caps = {
        "fit": bool(re.search(r"(?<![\w-])--fit(?![\w-])", help_text)),
        # 不把 --cpu-moe-draft 誤認成主模型用的 --cpu-moe。
        "cpu_moe": bool(re.search(r"(?<![\w-])--cpu-moe(?![\w-])", help_text)),
        # 手動 n_cpu_moe(部分 experts 留 GPU)寫入前先確認 build 支援。
        "n_cpu_moe": bool(re.search(r"(?<![\w-])--n-cpu-moe(?![\w-])", help_text)),
    }
    if not caps["fit"]:
        # VL 固定用 --fit 在 embedding/reranker 啟動後保留推論 VRAM,這是硬需求。
        # 在前置檢查就擋下,不讓使用者答完所有互動題才發現白忙一場。
        message = (
            "[FAIL] 安全的 VL placement 需要 llama-server --fit,才能在 embedding/reranker"
            " 啟動後保留推論用 VRAM;這個 build 不支援 --fit。\n"
            "  修復:更新並重新 build llama.cpp(README §1.5):\n"
            "    cd ~/llama.cpp && git pull && rm -rf build && "
            "cmake -B build -DGGML_CUDA=ON -DLLAMA_CURL=OFF && cmake --build build --config Release -j"
        )
        if skip:
            notes.append("⚠ 已跳過 --fit 檢查(假設為支援 --fit 的新版)。")
            caps["fit"] = True
        else:
            raise SetupError(message)
    ldd = shutil.which("ldd")
    if ldd:
        link = subprocess.run([ldd, str(binary)], capture_output=True, text=True, check=False)
        if link.returncode == 0 and "cuda" not in link.stdout.lower():
            notes.append("⚠ llama-server 看起來是純 CPU build(未連結 CUDA);能跑但會非常慢。")
    return caps


def detect_gpus() -> list[Gpu]:
    smi = shutil.which("nvidia-smi")
    if not smi:
        raise SetupError(
            "偵測失敗:找不到 nvidia-smi。請確認 NVIDIA 驅動已安裝,"
            "且 nvidia-smi 在 PATH 上(README §1)。"
        )
    try:
        proc = subprocess.run(
            [smi, "--query-gpu=index,name,memory.total,memory.free,uuid",
             "--format=csv,noheader,nounits"],
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
    except subprocess.TimeoutExpired as exc:
        raise SetupError(
            "偵測失敗:nvidia-smi 執行逾時(30 秒)。GPU driver 可能卡住:"
            "先在終端手動執行 nvidia-smi 確認,必要時重載驅動或重開機後重跑。"
        ) from exc
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip()
        raise SetupError(f"偵測失敗:nvidia-smi 執行失敗:{detail or '無輸出'}")
    gpus: list[Gpu] = []
    for line in proc.stdout.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 5 or not parts[0].isdecimal():
            continue
        try:
            total = int(parts[2])
            free = int(parts[3])
        except ValueError:
            total, free = 0, 0
        gpus.append(Gpu(index=int(parts[0]), name=parts[1], total_mib=total,
                        free_mib=free, uuid=parts[4]))
    if not gpus:
        raise SetupError("偵測失敗:nvidia-smi 沒有回報任何可用的 NVIDIA GPU。")
    return gpus


# ---------------------------------------------------------------------------
# 模型掃描與齊全性驗證
# ---------------------------------------------------------------------------

def _shard_info(path: Path) -> tuple[Path, int, int] | None:
    """多 shard GGUF:回傳 (第 1 片路徑, 總大小, shard 數);非 shard 回 None。"""
    match = _SHARD_RE.match(path.name)
    if not match:
        return None
    stem, total = match.group("stem"), match.group("total")
    siblings = sorted(
        sib
        for sib in path.parent.glob("*.gguf")
        if (m := _SHARD_RE.match(sib.name)) and m.group("stem") == stem and m.group("total") == total
    )
    first = path.parent / f"{stem}-00001-of-{total}.gguf"
    if not first.is_file():
        first = siblings[0]
    return first, sum(sib.stat().st_size for sib in siblings), len(siblings)


def _shard_issues(path: Path) -> list[str]:
    """檢查多 shard 模型是否齊全:缺片、零大小、殘留 incomplete/lock 檔。"""
    match = _SHARD_RE.match(path.name)
    issues: list[str] = []
    if not match:
        try:
            if path.stat().st_size == 0:
                issues.append(f"{path.name} 是零大小檔案(下載未完成?)")
        except OSError as exc:
            issues.append(f"{path.name} 無法讀取:{exc}")
        return issues

    stem, total_str = match.group("stem"), match.group("total")
    expected = int(total_str)
    present: dict[int, Path] = {}
    for sib in path.parent.glob("*.gguf"):
        m = _SHARD_RE.match(sib.name)
        if m and m.group("stem") == stem and m.group("total") == total_str:
            present[int(m.group("idx"))] = sib
    missing = [f"{stem}-{idx:05d}-of-{total_str}.gguf" for idx in range(1, expected + 1)
               if idx not in present]
    if missing:
        issues.append("缺少 shard:" + "、".join(missing))
    for idx, sib in sorted(present.items()):
        try:
            if sib.stat().st_size == 0:
                issues.append(f"{sib.name} 是零大小檔案(下載未完成?)")
        except OSError as exc:
            issues.append(f"{sib.name} 無法讀取:{exc}")
    leftovers = sorted(
        leftover.name
        for pattern in (f"{stem}*.incomplete", f"{stem}*.lock", f"{stem}*.part")
        for leftover in path.parent.glob(pattern)
    )
    if leftovers:
        issues.append("殘留未完成下載檔:" + "、".join(leftovers))
    return issues


def _candidate_files(candidate: ModelCandidate) -> list[Path]:
    """回傳單檔或依編號排序的完整 shard 路徑。"""
    match = _SHARD_RE.match(candidate.path.name)
    if not match:
        return [candidate.path]
    stem = match.group("stem")
    total_text = match.group("total")
    return [
        candidate.path.parent / f"{stem}-{index:05d}-of-{total_text}.gguf"
        for index in range(1, int(total_text) + 1)
    ]


def _gguf_exact(handle, size: int, path: Path) -> bytes:
    data = handle.read(size)
    if len(data) != size:
        raise SetupError(f"GGUF metadata 截斷:{path.name}")
    return data


def _gguf_u32(handle, path: Path) -> int:
    return struct.unpack("<I", _gguf_exact(handle, 4, path))[0]


def _gguf_u64(handle, path: Path) -> int:
    return struct.unpack("<Q", _gguf_exact(handle, 8, path))[0]


def _gguf_string(handle, path: Path, *, capture: bool) -> str | None:
    length = _gguf_u64(handle, path)
    if length > GIB:
        raise SetupError(f"GGUF string 長度異常:{path.name} ({length} bytes)")
    if capture:
        raw = _gguf_exact(handle, length, path)
        try:
            return raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise SetupError(f"GGUF string 不是 UTF-8:{path.name}") from exc
    handle.seek(length, os.SEEK_CUR)
    return None


def _consume_gguf_value(handle, value_type: int, path: Path, *, capture: bool = False,
                        depth: int = 0) -> object | None:
    """讀/略過一個 GGUF metadata value；只在 capture 時回傳 scalar/string。"""
    if depth > 2:
        raise SetupError(f"GGUF metadata array 巢狀過深:{path.name}")
    fixed = _GGUF_FIXED_TYPES.get(value_type)
    if fixed:
        fmt, size = fixed
        raw = _gguf_exact(handle, size, path)
        return struct.unpack(fmt, raw)[0] if capture else None
    if value_type == 8:  # STRING
        return _gguf_string(handle, path, capture=capture)
    if value_type == 9:  # ARRAY
        element_type = _gguf_u32(handle, path)
        count = _gguf_u64(handle, path)
        if count > 100_000_000:
            raise SetupError(f"GGUF metadata array 長度異常:{path.name} ({count})")
        element_fixed = _GGUF_FIXED_TYPES.get(element_type)
        if element_fixed:
            handle.seek(element_fixed[1] * count, os.SEEK_CUR)
        else:
            for _ in range(count):
                _consume_gguf_value(handle, element_type, path, depth=depth + 1)
        return None
    raise SetupError(f"GGUF metadata type 不支援:{path.name} (type={value_type})")


def _inspect_gguf_file(path: Path) -> ModelLayout:
    """只走 GGUF header/tensor table，以 offset 差計算 expert storage bytes。"""
    try:
        file_size = path.stat().st_size
        with path.open("rb") as handle:
            if _gguf_exact(handle, 4, path) != b"GGUF":
                raise SetupError(f"不是有效 GGUF(magic 不符):{path.name}")
            version = _gguf_u32(handle, path)
            if version not in {2, 3}:
                raise SetupError(f"GGUF version 不支援:{path.name} (v{version})")
            tensor_count = _gguf_u64(handle, path)
            metadata_count = _gguf_u64(handle, path)
            # split GGUF 允許某一片只帶 metadata、tensor_count=0。
            if tensor_count > 10_000_000:
                raise SetupError(f"GGUF tensor 數量異常:{path.name} ({tensor_count})")
            if metadata_count > 10_000_000:
                raise SetupError(f"GGUF metadata 數量異常:{path.name} ({metadata_count})")

            alignment = 32
            for _ in range(metadata_count):
                key = _gguf_string(handle, path, capture=True)
                value_type = _gguf_u32(handle, path)
                value = _consume_gguf_value(
                    handle, value_type, path, capture=key == "general.alignment"
                )
                if key == "general.alignment" and isinstance(value, int):
                    alignment = value
            if alignment < 1 or alignment > MIB or alignment & (alignment - 1):
                raise SetupError(f"GGUF alignment 異常:{path.name} ({alignment})")

            tensors: list[tuple[int, str]] = []
            for _ in range(tensor_count):
                name = _gguf_string(handle, path, capture=True)
                n_dims = _gguf_u32(handle, path)
                if n_dims > 16:
                    raise SetupError(f"GGUF tensor 維度異常:{path.name} ({n_dims})")
                _gguf_exact(handle, n_dims * 8, path)  # dimensions
                _gguf_u32(handle, path)                # ggml tensor type
                offset = _gguf_u64(handle, path)
                tensors.append((offset, name or ""))

            data_start = (handle.tell() + alignment - 1) // alignment * alignment
    except OSError as exc:
        raise SetupError(f"無法讀取 GGUF metadata:{path} ({exc})") from exc

    if not tensors:
        return ModelLayout(tensor_bytes=0, expert_bytes=0)
    tensors.sort()
    data_bytes = file_size - data_start
    if data_bytes <= 0:
        raise SetupError(f"GGUF 沒有 tensor data:{path.name}")
    total = 0
    expert = 0
    per_layer: dict[int, int] = {}
    for index, (offset, name) in enumerate(tensors):
        end = tensors[index + 1][0] if index + 1 < len(tensors) else data_bytes
        if offset < 0 or end <= offset or end > data_bytes:
            raise SetupError(f"GGUF tensor offset 異常:{path.name} ({name})")
        storage = end - offset
        total += storage
        if _CPU_MOE_TENSOR_RE.search(name):
            expert += storage
            blk = _BLK_INDEX_RE.search(name)
            if blk:
                layer = int(blk.group(1))
                per_layer[layer] = per_layer.get(layer, 0) + storage
    return ModelLayout(
        tensor_bytes=total,
        expert_bytes=expert,
        expert_layer_bytes=tuple(sorted(per_layer.items())),
    )


def inspect_model_layout(candidate: ModelCandidate) -> ModelLayout:
    """聚合所有 GGUF shards 的 tensor/expert bytes。"""
    total = 0
    expert = 0
    per_layer: dict[int, int] = {}
    for path in _candidate_files(candidate):
        layout = _inspect_gguf_file(path)
        total += layout.tensor_bytes
        expert += layout.expert_bytes
        for layer, size in layout.expert_layer_bytes:
            per_layer[layer] = per_layer.get(layer, 0) + size
    if total <= 0:
        raise SetupError(f"GGUF 沒有可分析的 tensor table:{candidate.path.name}")
    if expert > candidate.total_bytes:
        raise SetupError(f"GGUF expert tensor 容量異常:{candidate.path.name}")
    return ModelLayout(
        tensor_bytes=total,
        expert_bytes=expert,
        expert_layer_bytes=tuple(sorted(per_layer.items())),
    )


def scan_models(
    models_dir: Path, *, notes: list[str] | None = None
) -> tuple[dict[str, list[ModelCandidate]], list[str]]:
    if not models_dir.is_dir():
        raise SetupError(
            f"偵測失敗:找不到模型目錄 {models_dir}。"
            "請先依 README §2 下載 GGUF,或用 --models-dir 指定位置。"
        )
    try:
        ggufs = sorted(p for p in models_dir.rglob("*.gguf") if p.is_file())
    except PermissionError as exc:
        raise SetupError(f"偵測失敗:模型目錄無法讀取(權限不足):{exc}") from exc
    if not ggufs:
        raise SetupError(f"偵測失敗:{models_dir} 內沒有任何 .gguf 模型檔(README §2)。")

    mmprojs = [p for p in ggufs if "mmproj" in p.name.lower()]
    seen: set[Path] = set()
    broken: list[str] = []
    candidates: dict[str, list[ModelCandidate]] = {
        "main": [], "embedding": [], "reranker": [], "vl": []
    }

    # 先聚合成候選(shard 去重、剔除不完整),分類延後:mmproj 歸屬需要知道
    # 「同目錄還有幾顆模型」,平鋪目錄(所有 GGUF 混放)時不能把每顆主模型都當 VL。
    raw_candidates: list[ModelCandidate] = []
    for path in ggufs:
        if "mmproj" in path.name.lower():
            continue
        shard = _shard_info(path)
        if shard:
            first, total_bytes, shards = shard
            if first in seen:
                continue
            seen.add(first)
            candidate = ModelCandidate(path=first, total_bytes=total_bytes, shards=shards)
        else:
            if path in seen:
                continue
            seen.add(path)
            candidate = ModelCandidate(path=path, total_bytes=path.stat().st_size, shards=1)

        issues = _shard_issues(candidate.path)
        if issues:
            broken.append(f"{candidate.path.parent.name}/{candidate.path.name}:" + ";".join(issues))
            continue
        raw_candidates.append(candidate)

    def _haystack(cand: ModelCandidate) -> str:
        return f"{cand.path.parent.name}/{cand.path.name}".lower()

    # 每個目錄有幾顆「main/VL 類」模型(embedding/reranker 檔名可辨識,不參與計數)。
    mainlike_per_dir: dict[Path, int] = {}
    for cand in raw_candidates:
        haystack = _haystack(cand)
        if "rerank" in haystack or any(token in haystack for token in _EMBED_TOKENS):
            continue
        mainlike_per_dir[cand.path.parent] = mainlike_per_dir.get(cand.path.parent, 0) + 1

    ambiguous_dirs: list[Path] = []
    for candidate in raw_candidates:
        haystack = _haystack(candidate)
        sibling_mmproj = sorted(
            (mp for mp in mmprojs if mp.parent == candidate.path.parent),
            # 偏好 f16 mmproj(README §2.4 的預設下載)。
            key=lambda mp: (0 if "f16" in mp.name.lower() else 1, mp.name),
        )
        if "rerank" in haystack:
            candidates["reranker"].append(candidate)
        elif any(token in haystack for token in _EMBED_TOKENS):
            candidates["embedding"].append(candidate)
        else:
            if sibling_mmproj:
                ambiguous = mainlike_per_dir.get(candidate.path.parent, 0) > 1
                candidates["vl"].append(
                    ModelCandidate(
                        path=candidate.path,
                        total_bytes=candidate.total_bytes,
                        shards=candidate.shards,
                        # 混放目錄不得自動配對:mmproj 可能屬於同目錄的另一顆模型,
                        # 自動吞下去會讓錯的模型配 mmproj 當 VL(圖片分析輸出錯亂)。
                        mmproj=None if ambiguous
                        else (sibling_mmproj[0] if len(sibling_mmproj) == 1 else None),
                        mmproj_choices=tuple(sibling_mmproj),
                        mmproj_ambiguous=ambiguous,
                    )
                )
                if not ambiguous:
                    # 一目錄一模型(README §2 慣例)→ mmproj 配對明確:
                    # 標記 vl_paired,排序永遠在非 VL 之後,不會被自動選成 main。
                    candidate = ModelCandidate(
                        path=candidate.path,
                        total_bytes=candidate.total_bytes,
                        shards=candidate.shards,
                        vl_paired=True,
                    )
                elif candidate.path.parent not in ambiguous_dirs:
                    ambiguous_dirs.append(candidate.path.parent)
            candidates["main"].append(candidate)

    if notes is not None:
        for directory in ambiguous_dirs:
            notes.append(
                f"⚠ {directory} 內有多顆模型與 mmproj 混放,無法確定 mmproj 屬於哪顆模型:"
                "這些模型不會被自動視為 VL 專用。建議每顆模型一個目錄、"
                "mmproj 與它的 VL 模型放同一目錄(README §2.4)。"
            )

    for role, entries in candidates.items():
        hints = _VERIFIED_HINTS[role]

        def sort_key(cand: ModelCandidate) -> tuple:
            path_text = str(cand.path).lower()
            # tuple 的先後就是維護者 preference；不能只做 bool 命中後再按大小，
            # 否則同時裝有 qwen3.5-9b / qwen3-vl 時會讓較小的舊模型蓋過首選。
            hint_rank = next(
                (rank for rank, hint in enumerate(hints) if hint in path_text),
                len(hints),
            )
            size = -cand.total_bytes if role == "main" else cand.total_bytes
            return (cand.vl_paired, hint_rank, size, str(cand.path))

        entries.sort(key=sort_key)
    return candidates, broken


def precheck(gpus: list[Gpu], candidates: dict[str, list[ModelCandidate]],
             broken: list[str],
             overrides: dict[str, str | None] | None = None) -> list[str]:
    """背景初步判定;不 OK 直接 SetupError 通知,可過但要注意的回傳 warning 清單。

    使用者用 --main-model / --embed-model / ... 直接給 .gguf 路徑時,該類別
    即使掃描不到也算滿足(模型分散存放在 models-dir 之外是合法情境)。
    """
    warnings: list[str] = []
    overrides = overrides or {}

    def satisfied(role: str) -> bool:
        if candidates[role]:
            return True
        value = overrides.get(role)
        # 數字是「候選編號」,沒有候選就沒意義;路徑才可救援缺類別。
        return value is not None and not value.isdecimal()

    missing = {
        "main": "主聊天模型",
        "embedding": "embedding 模型(如 bge-m3)",
        "reranker": "reranker 模型(如 bge-reranker-v2-m3)",
        "vl": "VL 模型 + mmproj(如 qwen3.5-9b)",
    }
    lacking = [label for role, label in missing.items() if not satisfied(role)]
    if lacking:
        detail = ""
        if broken:
            detail = "\n以下模型因不完整被剔除(修復後重跑):\n  - " + "\n  - ".join(broken)
        raise SetupError(
            "初步判定不通過:~/models 缺少必要模型類別 → " + "、".join(lacking)
            + "。下載方式見 README §2;四類模型都是硬性需求。" + detail
        )
    for report in broken:
        warnings.append(f"模型不完整已剔除:{report}(重新執行原本的 hf download 即可補齊)")
    if len(gpus) < 2:
        warnings.append(
            "只偵測到 1 顆 GPU:主模型與三顆附屬模型將共用同一顆卡(可以跑,"
            "但雙卡分工更穩;RTX 5090 單卡實測見 docs/verified-reference-5090.md)。"
        )
    return warnings


# ---------------------------------------------------------------------------
# 互動選擇
# ---------------------------------------------------------------------------

def _candidate_from_path(path: Path) -> ModelCandidate:
    """使用者直接給路徑時也要正確聚合多 shard 的總大小,並驗證齊全性。"""
    issues = _shard_issues(path)
    if issues:
        raise SetupError(f"{path.name} 不完整:" + ";".join(issues))
    shard = _shard_info(path)
    if shard:
        first, total_bytes, shards = shard
        return ModelCandidate(path=first, total_bytes=total_bytes, shards=shards)
    return ModelCandidate(path=path, total_bytes=path.stat().st_size, shards=1)


def _input(prompt: str) -> str:
    try:
        return input(prompt)
    except EOFError as exc:
        raise SetupError(
            "無互動輸入環境。請加 --yes 並用旗標提供所有必要值"
            "(--main-model/--ctx/...),見 ./set_config.sh --help。"
        ) from exc


def _input_optional(prompt: str, default: str = "") -> str:
    """非必要的收尾提問:沒有互動輸入(EOF)時採預設值,不中斷流程。"""
    try:
        return input(prompt)
    except EOFError:
        return default


def choose_candidate(
    role_label: str,
    entries: list[ModelCandidate],
    override: str | None,
    assume_yes: bool,
    *,
    flag_name: str,
) -> ModelCandidate:
    """模型選擇:沒有預設值。唯一候選自動選用;多候選必須輸入編號或路徑。"""
    if override is not None:
        if override.isdecimal():
            if not entries:
                raise SetupError(
                    f"{role_label}:掃描不到任何候選,無法用編號 {override} 指定;"
                    "請改給 .gguf 絕對路徑。"
                )
            pick = int(override)
            if not 1 <= pick <= len(entries):
                raise SetupError(f"{role_label}:選項編號 {pick} 不在 1..{len(entries)}。")
            return entries[pick - 1]
        path = Path(override).expanduser()
        if not path.is_file() or path.suffix.lower() != ".gguf":
            raise SetupError(f"{role_label}:{override} 不是存在的 .gguf 檔。")
        return _candidate_from_path(path)
    if len(entries) == 1:
        print(f"{role_label} 只有一個候選,自動選用:{entries[0].describe()}")
        return entries[0]
    if assume_yes:
        raise SetupError(
            f"{role_label}:有 {len(entries)} 個候選;--yes 模式需要用 {flag_name} "
            f"指定編號(1..{len(entries)})或 .gguf 絕對路徑。"
        )

    print(f"\n{role_label} — 偵測到的候選:")
    for pos, cand in enumerate(entries, start=1):
        print(f"  [{pos}] {cand.describe()}")
    while True:
        raw = _input(f"請輸入編號 1..{len(entries)}(或直接貼 .gguf 絕對路徑): ").strip()
        if raw.isdecimal():
            if 1 <= int(raw) <= len(entries):
                return entries[int(raw) - 1]
            print(f"  無效輸入:{raw}(編號只有 1..{len(entries)})")
            continue
        path = Path(raw).expanduser()
        if raw and path.is_file() and path.suffix.lower() == ".gguf":
            return _candidate_from_path(path)
        print(f"  無效輸入:{raw!r}(要嘛編號 1..{len(entries)},要嘛存在的 .gguf 路徑)")


def choose_gpu(
    role_label: str,
    gpus: list[Gpu],
    override: str | None,
    assume_yes: bool,
    *,
    flag_name: str,
) -> Gpu:
    """GPU 選擇:沒有預設值。單卡自動選用;多卡必須輸入偵測到的 index。"""
    by_index = {gpu.index: gpu for gpu in gpus}
    if override is not None:
        if not override.isdecimal() or int(override) not in by_index:
            raise SetupError(
                f"{role_label}:GPU index '{override}' 不在偵測結果中"
                f"(可用:{sorted(by_index)})。"
            )
        return by_index[int(override)]
    if len(gpus) == 1:
        return gpus[0]
    if assume_yes:
        raise SetupError(
            f"{role_label}:偵測到多顆 GPU;--yes 模式需要用 {flag_name} 指定 GPU index"
            f"(可用:{sorted(by_index)})。"
        )

    print(f"\n{role_label} — 要放哪顆 GPU?")
    for gpu in gpus:
        print(f"  [{gpu.index}] {gpu.describe()}")
    while True:
        raw = _input(f"請輸入 GPU index(可用:{sorted(by_index)}): ").strip()
        if raw.isdecimal() and int(raw) in by_index:
            return by_index[int(raw)]
        print(f"  無效的 GPU index:{raw!r}(可用:{sorted(by_index)})")


def choose_int(label: str, override: int | None, assume_yes: bool, *,
               minimum: int, maximum: int, flag_name: str) -> int:
    """數值輸入:沒有預設值,只驗證範圍(選項外的輸入會重問)。
    互動與旗標共用同一組上下限:互動不得寫入 CLI/schema 明令拒絕的值。"""
    if override is not None:
        if not minimum <= override <= maximum:
            raise SetupError(f"{label} 必須在 {minimum}..{maximum}。")
        return override
    if assume_yes:
        raise SetupError(
            f"--yes 模式需要用 {flag_name} 指定 {label}({minimum}..{maximum})。"
        )
    while True:
        raw = _input(f"{label}({minimum}..{maximum}): ").strip()
        if raw.isdecimal() and minimum <= int(raw) <= maximum:
            return int(raw)
        print(f"  無效輸入:請輸入 {minimum}..{maximum} 的整數。")


def reranker_ctx_effect(ctx: int) -> str:
    return (
        f"reranker ctx={ctx} 會同步設為 -c/-b/-ub;每筆 query+passage 未超過此上限時,"
        "單純加大 ctx 不會提高排序精準度;超過時可能失敗或必須截斷,才可能漏掉關鍵證據。"
        "ctx 越大越吃顯存,真的送入更多 token 時也會更慢。"
    )


def choose_reranker_ctx(
    candidate: ModelCandidate,
    override: int | None,
    assume_yes: bool,
) -> int:
    """Return the reranker service's internal buffer size.

    This is not the main-model n_ctx and should not be another normal setup
    question.  Keep the CLI override for unusual long-passage/OOM tuning, but
    otherwise use the deployment default silently.
    """
    del candidate, assume_yes
    if override is None:
        return DEFAULT_RERANKER_CTX
    return choose_int(
        "reranker internal buffer(-c/-b/-ub)", override, True,
        minimum=MIN_RERANKER_CTX, maximum=MAX_RERANKER_CTX, flag_name="--rerank-ctx",
    )


def choose_cpu_moe_mode(
    override: bool | None,
    assume_yes: bool,
    candidate: ModelCandidate,
    layout: ModelLayout | None,
    supported: bool,
    notes: list[str],
) -> bool:
    """主模型唯一一次的模式分流;附屬三模型永遠不套 CPU-MoE。

    不做容量估算、沒有預設答案:只依 GGUF 是否有 expert tensors 決定要不要問,
    要不要開由使用者自己決定(VRAM 放不放得下以啟動後 nvidia-smi 實測為準)。
    """
    if override is not None:
        return override
    if layout is None:
        notes.append(
            "⚠ 無法讀取主模型 GGUF tensor 配置 → 使用一般模式"
            "(確定是 MoE 要強制啟用時用 --cpu-moe)。"
        )
        return False
    if not layout.is_moe:
        return False  # dense 模型:CPU-MoE 無意義,不詢問。
    if not supported:
        notes.append(
            "⚠ 主模型是 MoE,但這個 llama-server build 不支援 --cpu-moe → 一般模式。"
            "更新並重新 build llama.cpp(README §1.5)後重跑可啟用。"
        )
        return False
    if assume_yes:
        raise SetupError(
            "主模型是 MoE:--yes 模式需要用 --cpu-moe / --no-cpu-moe / --n-cpu-moe "
            "明確指定運行模式。"
        )

    print("\n【主聊天模型運行模式】CPU-MoE 只套用 main,不影響 embedding/reranker/VL。")
    print(f"  目前主模型: {candidate.describe()}")
    print(f"  已偵測到 MoE expert tensors 約 {layout.expert_bytes / GIB:.1f} GiB。")
    print("  y = experts 放 RAM、dense/KV 留 GPU(--cpu-moe / --n-cpu-moe);"
          "n = 一般模式(全 GPU offload)。")
    while True:
        raw = _input("主聊天模型啟用 CPU-MoE? [y/n]: ").strip().lower()
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print("  請輸入 y 或 n。")


def choose_n_cpu_moe(
    override: int | None,
    assume_yes: bool,
    layout: ModelLayout,
) -> int | None:
    """CPU-MoE 模式的部分 offload 檔位:純使用者輸入,只驗證範圍,不做容量估算。

    回傳 None = 全部 experts 留 RAM(--cpu-moe)。輸入超過最大 block 編號的值
    視同全部留 RAM(語意上等同 --cpu-moe,寫成布林鍵比較清楚)。
    """
    layers = layout.expert_layer_bytes
    max_index = layers[-1][0] if layers else 0
    if override is not None:
        return None if override > max_index else override
    if assume_yes:
        # _gather 保證 --yes 一定帶模式旗標:--cpu-moe 不會走到這裡,
        # --n-cpu-moe 則 override 非 None。防衛性維持全 CPU-MoE。
        return None

    print("\n【主模型 n-cpu-moe(部分 CPU-MoE)】")
    print("  --n-cpu-moe N = 前 N 層(blk 編號 < N)的 MoE experts 留 RAM,其餘塞回 GPU。")
    if layers:
        print(f"  這顆模型共 {len(layers)} 層 experts(blk.{layers[0][0]}..blk.{max_index});"
              f"輸入 ≥ {max_index + 1} = 全部 experts 留 RAM(等同 --cpu-moe)。")
    else:
        print("  這顆模型的 expert tensors 沒有 blk 編號;輸入 ≥ 1 = 全部 experts 留 RAM。")
    print("  N 越小 → 越多 experts 進 GPU、越吃顯存;塞不塞得下以啟動後 nvidia-smi 實測為準。")
    value = choose_int(
        "主模型 n-cpu-moe(--n-cpu-moe)", None, False,
        minimum=0, maximum=MAX_N_CPU_MOE, flag_name="--n-cpu-moe",
    )
    return None if value > max_index else value


def resolve_vl_mmproj(
    vl_cand: ModelCandidate,
    override: str | None,
    interactive: bool,
) -> Path:
    """mmproj 配對:唯一 → 自動;多個 → 必須選(不猜);沒有 → 停下並指路。"""
    if override:
        path = Path(override).expanduser()
        if not path.is_file() or path.suffix.lower() != ".gguf":
            raise SetupError(f"VL mmproj:{override} 不是存在的 .gguf 檔。")
        return path
    choices = list(vl_cand.mmproj_choices)
    if not choices:
        sibling = sorted(vl_cand.path.parent.glob("*mmproj*.gguf"))
        choices = sibling
    if not choices:
        raise SetupError(
            f"VL 模型 {vl_cand.path.name} 同目錄找不到 mmproj *.gguf;"
            "VL 模型與它的 mmproj 必須放在同一目錄(README §2.4),"
            "或用 --vl-mmproj 明確指定。"
        )
    if len(choices) == 1:
        return choices[0]
    if not interactive:
        listing = "、".join(p.name for p in choices)
        raise SetupError(
            f"VL 模型 {vl_cand.path.name} 同目錄有多個 mmproj({listing}),"
            "無法自動判斷相容配對(配錯會讓圖片分析輸出錯亂):"
            "請用 --vl-mmproj <絕對路徑> 明確指定,或互動重跑 ./set_config.sh 選擇。"
        )
    print(f"\n【VL mmproj】{vl_cand.path.name} 同目錄有多個 mmproj,請選擇相容的那個:")
    for pos, choice in enumerate(choices, start=1):
        print(f"  [{pos}] {choice.name}")
    while True:
        raw = _input(f"請輸入編號 1..{len(choices)}: ").strip()
        if raw.isdecimal() and 1 <= int(raw) <= len(choices):
            return choices[int(raw) - 1]
        print("  無效輸入。")


# ---------------------------------------------------------------------------
# 主模型啟動參數(依使用者選定的模式組裝;不做容量估算)
# ---------------------------------------------------------------------------

def build_main_parameters(candidate: ModelCandidate, ctx: int, threads: int,
                          fit_supported: bool, cpu_moe: bool, notes: list[str], *,
                          n_cpu_moe: int | None = None) -> tuple[dict, int, int]:
    """依使用者選定的模式組裝主模型參數;不做容量估算,一律 -ngl 99。

    VRAM 放不放得下由使用者以啟動後 nvidia-smi 實測確認(~/start.sh 結尾會提醒)。
    """
    parameters: dict = {
        "jinja": True,
        "flash_attention": "on",
        "cache_type_k": "q8_0",
        "cache_type_v": "q8_0",
        "threads": threads,
    }
    if cpu_moe and n_cpu_moe is not None:
        # 使用者的部分 offload:--n-cpu-moe 與 --cpu-moe 互斥,同樣不與 --fit 混用。
        parameters.update({"gpu_layers": 99, "n_cpu_moe": n_cpu_moe})
        notes.append(
            f"主模型 {candidate.total_bytes / GIB:.0f} GB 採 CPU-MoE(部分)模式 → "
            f"前 {n_cpu_moe} 層 expert tensors 固定在 RAM(--n-cpu-moe {n_cpu_moe}),"
            "其餘 experts 與 dense 層全 GPU offload(-ngl 99);只影響 main。"
        )
    elif cpu_moe:
        parameters.update({"gpu_layers": 99, "cpu_moe": True})
        notes.append(
            f"主模型 {candidate.total_bytes / GIB:.0f} GB 採 CPU-MoE 模式 → "
            "全部 expert tensors 固定在 RAM(--cpu-moe),dense/其他層全 GPU offload(-ngl 99);"
            "只影響 main。"
        )
    else:
        parameters["gpu_layers"] = 99
        notes.append(
            f"主模型 {candidate.total_bytes / GIB:.0f} GB 採一般模式 → 全 GPU offload(-ngl 99);"
            "VRAM 用量請啟動後以 nvidia-smi 確認。"
        )
    if fit_supported:
        # 新版 llama.cpp 的 --fit 預設可能是 on;明確關閉才不會重寫使用者選定的
        # -ngl 99 / CPU-MoE placement。
        parameters["fit"] = "off"
    # schema 規定 ubatch ≤ batch ≤ ctx;小 ctx(CLI 允許到 1024)不夾限的話,
    # 使用者答完全部問題才會被自己的驗證打死。
    batch = min(2048, ctx)
    ubatch = min(512, batch)
    notes.append("取樣參數(temp/top-p/top-k)刻意不寫死:各模型官方建議不同,"
                 "需要時自行加進 ~/.config/codetrail/deployment.json 的 services.main.parameters。")
    return parameters, batch, ubatch


def sanitize_registry_key(path: Path) -> str:
    """檔名 → 合法 registry key(deployment_profile 的 _BARE_MODEL_RE:不含底線)。"""
    stem = _SHARD_RE.match(path.name)
    name = stem.group("stem") if stem else path.stem
    key = re.sub(r"[^A-Za-z0-9.+:-]+", "-", name).strip("-").lower()
    key = re.sub(r"-{2,}", "-", key)
    if not key or not key[0].isalnum():
        key = f"model-{key.lstrip('-.')}" if key else "main-model"
    return key[:64]


def _warn_unverified_aux(plan: Plan) -> None:
    for selection in (plan.embedding, plan.reranker, plan.vl):
        hints = _VERIFIED_HINTS[selection.role]
        if hints and not any(h in str(selection.candidate.path).lower() for h in hints):
            plan.notes.append(
                f"⚠ {selection.role} 選了未經維護者驗證的模型 {selection.candidate.path.name}:"
                "server 可能正常啟動,但 pooling / reranking / 圖片分析行為不保證正確"
                "(維護者驗證組合見 deployment_profiles/defaults.json 與 README §2.3–§2.4)。"
            )


# ---------------------------------------------------------------------------
# 產物內容
# ---------------------------------------------------------------------------

def build_models_registry(plan: Plan, registry_path: Path, notes: list[str]) -> dict:
    existing: dict = {}
    if registry_path.is_file():
        try:
            loaded = json.loads(registry_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                existing = loaded
            else:
                notes.append(f"{registry_path} 不是 JSON object,將重建(原檔已備份)。")
        except (OSError, json.JSONDecodeError):
            notes.append(f"{registry_path} 無法解析,將重建(原檔已備份)。")

    # 既有項目先過 loader 同款格式驗證:一個壞 key 會讓啟動時整份 registry 被拒,
    # 與其留到 ~/start.sh 才爆,不如現在剔除並提醒(原檔有備份)。
    merged: dict = {}
    stale: list[str] = []
    for key, value in existing.items():
        valid = (
            isinstance(key, str)
            and _BARE_MODEL_RE.fullmatch(key)
            and isinstance(value, str)
            and value.strip()
        )
        if valid:
            try:
                expanded = Path(value).expanduser()
                valid = expanded.is_absolute() and expanded.suffix.lower() == ".gguf"
            except (OSError, RuntimeError):
                valid = False
        if not valid:
            notes.append(
                f"⚠ models.json 有格式不合法的項目已剔除:{key!r}"
                "(啟動時整份 registry 會因它被拒;原值在備份)"
            )
            continue
        merged[key] = value
        if key != plan.main_key and not Path(value).expanduser().is_file():
            stale.append(key)
    if stale:
        notes.append(
            "registry 內有項目指向已不存在的檔案:" + "、".join(sorted(stale))
            + "(不影響本次設定;TUI /models 殘留舊項目時可自行清理"
            " models.json 與 opencode.json 的 provider.llamacpp.models)"
        )
    merged[plan.main_key] = str(plan.main.candidate.path)
    return merged


def build_deployment_config(plan: Plan) -> dict:
    services: dict = {
        "main": {
            "model": plan.main_key,
            "ctx": plan.ctx,
            "batch": plan.batch,
            "ubatch": plan.ubatch,
            "parameters": plan.parameters,
        },
        "embedding": {
            "model": str(plan.embedding.candidate.path),
            "parameters": {"parallel": AUX_PARALLEL},
        },
        "reranker": {
            "model": str(plan.reranker.candidate.path),
            # /reranking 的每筆 query+passage 必須放進同一個 physical batch；
            # 三個值同步，使用者選 ctx 才會真的同時改變長度上限與 buffer。
            "ctx": plan.reranker_ctx,
            "batch": plan.reranker_ctx,
            "ubatch": plan.reranker_ctx,
            "parameters": {"parallel": AUX_PARALLEL},
        },
        "vl": {
            "model": str(plan.vl.candidate.path),
            "mmproj": str(plan.vl.mmproj),
            # VL 固定最後啟動。讓 llama.cpp 依 embedding/reranker 的實際占用
            # 自動決定 GPU layers；server 也會把 mmproj worst-case memory 加進
            # fit target，避免 health OK 後第一張圖片才 CUDA OOM。
            "parameters": {
                "gpu_layers": "auto",
                "parallel": AUX_PARALLEL,
                "fit": "on",
                "fit_target": VL_FIT_TARGET_MIB,
            },
        },
    }
    if plan.allow_remote:
        for role in services:
            services[role]["bind"] = "all-interfaces"
    return {"schema_version": 1, "profile": "defaults", "services": services}


# set_config 自己管理(每次重寫)的參數鍵:舊檔裡這些鍵缺席或不同屬正常,不警告。
# 舊版工具寫過的 fit_target(main 已不再產生)也列入,重跑時安靜淘汰。
_MANAGED_PARAMETER_KEYS = {
    "jinja", "flash_attention", "cache_type_k", "cache_type_v", "threads",
    "gpu_layers", "cpu_moe", "n_cpu_moe", "fit", "fit_target", "parallel",
    "embedding", "pooling", "reranking",
}
# 明確屬於使用者領域的主模型參數(本工具刻意不寫死)→ 重跑時原樣保留。
# no_mmap 已不由本工具自動判定,使用者(或舊版工具)設過就尊重。
_PRESERVED_MAIN_SAMPLING_KEYS = (
    "temperature", "top_p", "top_k", "min_p", "presence_penalty", "no_mmap",
)


def merge_existing_deployment(config: dict, existing_path: Path, notes: list[str]) -> None:
    """重跑時不清掉使用者手動加進 deployment.json 的東西。

    本工具的 note 就教人「取樣參數自行加進 services.main.parameters」——那麼重跑
    就必須保留它們。本工具管理的鍵(offload/模式等)每次依使用者作答重寫;
    其餘非本工具管理的鍵不能盲目帶入(可能與新模式衝突),改成明確警告已捨棄
    (原值在備份)。
    """
    try:
        existing = json.loads(existing_path.read_text(encoding="utf-8"))
    except OSError:
        return
    except ValueError:
        notes.append(f"⚠ 既有 {existing_path.name} 無法解析,將整份重建(原檔已備份)。")
        return
    if not isinstance(existing, dict) or not isinstance(existing.get("services"), dict):
        return
    old_services = existing["services"]
    for role, new_service in config["services"].items():
        old_service = old_services.get(role)
        if not isinstance(old_service, dict):
            continue
        # port/base_url 屬使用者領域(本工具從不產生這兩鍵)→ 手動改過就原樣保留,
        # 不能重跑一次就靜默退回預設 port。
        carried = [
            key for key in ("port", "base_url")
            if key in old_service and key not in new_service
        ]
        for key in carried:
            new_service[key] = old_service[key]
        if carried:
            notes.append(
                f"保留你手動設定的 services.{role}."
                + "、".join(f"{key}={old_service[key]}" for key in carried)
            )
        old_params = old_service.get("parameters")
        old_params = old_params if isinstance(old_params, dict) else {}
        new_params = new_service.setdefault("parameters", {})
        kept: list[str] = []
        dropped: list[str] = []
        for key, value in old_params.items():
            if key in new_params:
                continue
            if role == "main" and key in _PRESERVED_MAIN_SAMPLING_KEYS:
                new_params[key] = value
                kept.append(f"{key}={value}")
            elif key not in _MANAGED_PARAMETER_KEYS:
                dropped.append(f"{key}={value}")
        if kept:
            notes.append(f"保留你手動加在 deployment.json 的 {role} 取樣參數:{', '.join(kept)}")
        if dropped:
            notes.append(
                f"⚠ 既有 deployment.json 的 services.{role}.parameters 有本次未涵蓋的鍵,"
                f"已捨棄:{', '.join(dropped)}(原值在備份;需要的話手動加回)"
            )
        if old_service.get("bind") == "all-interfaces" and "bind" not in new_service:
            notes.append(
                "⚠ 既有設定開放區網連線(bind: all-interfaces),本次未加 --allow-remote"
                " → 回到僅本機 127.0.0.1。要維持開放請重跑 ./set_config.sh --allow-remote。"
            )


def _opencode_timeout_ms() -> int:
    config_text = (REPO_ROOT / "config.py").read_text(encoding="utf-8")
    match = re.search(r"^OPENCODE_MCP_TIMEOUT_MIN_MS\s*=\s*([0-9_]+)", config_text, re.MULTILINE)
    return int(match.group(1).replace("_", "")) if match else OPENCODE_TIMEOUT_FALLBACK_MS


_OPENCODE_PERMISSION_TEMPLATE = {
    "*": "deny",
    "question": "allow",
    "todowrite": "allow",
    "plan_enter": "allow",
    "plan_exit": "allow",
    "codetrail_*": "allow",
    "codetrail_apply_patch": "ask",
    "codetrail_run_lint": "ask",
    "codetrail_run_command": "ask",
    "codetrail_remove_document": "ask",
    "codetrail_import_external_file": "allow",
    "webfetch": "deny",
    "websearch": "deny",
    "bash": "deny",
    "read": "deny",
    "grep": "deny",
    "glob": "deny",
    "edit": "deny",
    "write": "deny",
    "apply_patch": "deny",
    "external_directory": "deny",
    "task": "deny",
    "skill": "deny",
    "lsp": "deny",
}


DEFAULT_MAIN_BASE_URL = "http://localhost:8080"


def _opencode_template(plan: Plan, python_bin: str,
                       main_base_url: str | None = None) -> dict:
    mcp_command = (
        'root="${AICODE_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)}"; '
        f'AICODE_ROOT="$root" exec {shlex.quote(python_bin)} '
        f'{shlex.quote(str(REPO_ROOT / "mcp_server.py"))}'
    )
    # OpenCode 連的必須是 deployment 實際的 main endpoint:使用者手改過 port/base_url
    # 時(merge_existing_deployment 會保留),baseURL 不能仍寫死 8080。
    base_url = (main_base_url or DEFAULT_MAIN_BASE_URL).rstrip("/")
    return {
        "$schema": "https://opencode.ai/config.json",
        "share": "disabled",
        "autoupdate": False,
        "enabled_providers": ["llamacpp"],
        "model": f"llamacpp/{plan.main_key}",
        "small_model": f"llamacpp/{plan.main_key}",
        "provider": {
            "llamacpp": {
                "npm": "@ai-sdk/openai-compatible",
                "name": "llama.cpp local",
                "options": {"baseURL": f"{base_url}/v1", "apiKey": "dummy"},
                "models": {
                    plan.main_key: {
                        "name": plan.main_key,
                        "limit": {"context": plan.ctx, "output": 8192},
                    }
                },
            }
        },
        "mcp": {
            "codetrail": {
                "type": "local",
                "command": ["bash", "-lc", mcp_command],
                "enabled": True,
                "timeout": _opencode_timeout_ms(),
            }
        },
        "permission": dict(_OPENCODE_PERMISSION_TEMPLATE),
    }


def build_opencode_config(
    plan: Plan, python_bin: str, existing_path: Path,
    main_base_url: str | None = None,
) -> tuple[dict, list[str]]:
    """只合併 CodeTrail 管的欄位;保留使用者既有 provider / mcp / 主題等設定。

    回傳 (config, 變更清單)。既有檔不存在或無法解析 → 用完整範本。
    main_base_url 是合併後 deployment 的 main endpoint(手改 port 時非預設),
    baseURL 跟著它走,deployment 與 OpenCode 才不會各連各的 port。
    """
    template = _opencode_template(plan, python_bin, main_base_url)
    changes: list[str] = []
    existing: dict | None = None
    if existing_path.is_file():
        try:
            loaded = json.loads(existing_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                existing = loaded
            else:
                changes.append("既有 opencode.json 不是 JSON object → 以完整範本重建(原檔已備份)")
        except (OSError, json.JSONDecodeError):
            changes.append("既有 opencode.json 無法解析 → 以完整範本重建(原檔已備份)")
    if existing is None:
        if not changes:
            changes.append("建立新的 opencode.json(完整範本)")
        return template, changes

    merged = json.loads(json.dumps(existing))  # 深拷貝

    providers = merged.get("enabled_providers")
    if isinstance(providers, list):
        if "llamacpp" not in providers:
            providers.append("llamacpp")
            changes.append("enabled_providers 加入 'llamacpp'(保留你原本啟用的 provider)")
        extra = [p for p in providers if p != "llamacpp"]
        if extra:
            changes.append(
                f"⚠ enabled_providers 仍包含其他 provider({', '.join(map(str, extra))});"
                "NDA 場景建議只留 llamacpp"
            )
    else:
        merged["enabled_providers"] = ["llamacpp"]
        changes.append("設定 enabled_providers = ['llamacpp']")

    for key in ("model", "small_model"):
        new_value = template[key]
        if merged.get(key) != new_value:
            old = merged.get(key)
            merged[key] = new_value
            changes.append(f"{key}: {old!r} → {new_value!r}")

    # 合法 JSON 但型別不對(provider/mcp/models 不是 object)也不能 traceback:
    # 換成範本區塊並在變更清單說明(原檔已備份),其餘使用者設定照常保留。
    provider = merged.get("provider")
    if not isinstance(provider, dict):
        if provider is not None:
            changes.append("⚠ 既有 provider 不是 JSON object → 以範本重建該區塊(原值在備份)")
        provider = {}
        merged["provider"] = provider
    llamacpp = provider.get("llamacpp")
    if not isinstance(llamacpp, dict):
        provider["llamacpp"] = template["provider"]["llamacpp"]
        changes.append("新增 provider.llamacpp(其他 provider 設定保留)")
    else:
        llamacpp["npm"] = template["provider"]["llamacpp"]["npm"]
        llamacpp["name"] = template["provider"]["llamacpp"]["name"]
        old_options = llamacpp.get("options")
        llamacpp["options"] = template["provider"]["llamacpp"]["options"]
        if isinstance(old_options, dict) and \
                old_options.get("baseURL") != llamacpp["options"]["baseURL"]:
            changes.append(
                f"provider.llamacpp.options.baseURL: {old_options.get('baseURL')!r} → "
                f"{llamacpp['options']['baseURL']!r}(對齊 deployment 的 main endpoint)"
            )
        models = llamacpp.get("models")
        if not isinstance(models, dict):
            if models is not None:
                changes.append(
                    "⚠ 既有 provider.llamacpp.models 不是 JSON object → 重建(原值在備份)"
                )
            models = {}
            llamacpp["models"] = models
        models[plan.main_key] = template["provider"]["llamacpp"]["models"][plan.main_key]
        changes.append(
            f"provider.llamacpp.models 加入/更新 '{plan.main_key}'"
            f"(limit.context={plan.ctx};你其他的本機模型項目保留)"
        )

    mcp = merged.get("mcp")
    if not isinstance(mcp, dict):
        if mcp is not None:
            changes.append("⚠ 既有 mcp 不是 JSON object → 以範本重建該區塊(原值在備份)")
        mcp = {}
        merged["mcp"] = mcp
    mcp["codetrail"] = template["mcp"]["codetrail"]
    changes.append("mcp.codetrail 更新為偵測到的 Python 與 mcp_server.py 路徑(其他 MCP server 保留)")

    permission = merged.get("permission")
    if not isinstance(permission, dict):
        merged["permission"] = dict(_OPENCODE_PERMISSION_TEMPLATE)
        changes.append("加入 CodeTrail 建議的 deny-all permission 範本")
    else:
        added, conflicts = [], []
        for key, value in _OPENCODE_PERMISSION_TEMPLATE.items():
            if key not in permission:
                permission[key] = value
                added.append(key)
            elif permission[key] != value:
                conflicts.append(f"{key}(你設 {permission[key]!r},建議 {value!r})")
        if added:
            changes.append(f"permission 補上缺少的 {len(added)} 個鍵(依 CodeTrail 範本)")
        if conflicts:
            changes.append(
                "⚠ permission 與 CodeTrail 建議不同、已尊重你的設定:" + "、".join(conflicts)
                + " —— 放寬這些會讓 OpenCode 內建工具繞過 CodeTrail 沙箱(docs/security.md)"
            )

    for key in ("share", "autoupdate"):
        if key not in merged:
            merged[key] = template[key]
        elif merged[key] != template[key]:
            changes.append(f"⚠ {key}={merged[key]!r} 與建議值 {template[key]!r} 不同,已保留你的設定")
    merged.setdefault("$schema", template["$schema"])
    return merged, changes


def _gpu_exports(plan: Plan) -> list[str]:
    aux = {plan.embedding.gpu.selector, plan.reranker.gpu.selector, plan.vl.gpu.selector}
    lines = [f"export MAIN_GPU={shlex.quote(plan.main.gpu.selector)}"]
    if len(aux) == 1:
        lines.append(f"export AUX_GPU={shlex.quote(next(iter(aux)))}")
    else:
        lines.append(f"export EMBED_GPU={shlex.quote(plan.embedding.gpu.selector)}")
        lines.append(f"export RERANK_GPU={shlex.quote(plan.reranker.gpu.selector)}")
        lines.append(f"export VL_GPU={shlex.quote(plan.vl.gpu.selector)}")
    return lines


def _offload_description(plan: Plan) -> str:
    suffix = " --fit off" if plan.parameters.get("fit") == "off" else ""
    if plan.parameters.get("n_cpu_moe") is not None:
        return (
            f"CPU-MoE(部分): -ngl 99 --n-cpu-moe {plan.parameters['n_cpu_moe']}"
            f"{suffix}(只套 main)"
        )
    if plan.parameters.get("cpu_moe"):
        return f"CPU-MoE: -ngl 99 --cpu-moe{suffix}(只套 main)"
    return f"一般模式: -ngl 99{suffix}(全 GPU offload)"


def build_start_sh(plan: Plan) -> str:
    gpu_lines = "\n".join(f"#   {gpu.describe()}" for gpu in plan.gpus)
    offload = _offload_description(plan)
    bind_note = (
        "0.0.0.0(--allow-remote:區網其他機器可連線,llama-server 無認證,務必只在可信網段)"
        if plan.allow_remote
        else "127.0.0.1(僅本機;要開放其他機器 → 重跑 ./set_config.sh --allow-remote)"
    )
    exports = "\n".join(_gpu_exports(plan))
    unset_line = " ".join((*_OVERRIDE_ENV_KEYS, *_SESSION_ENV_KEYS))
    quit_sh = shlex.quote(str(REPO_ROOT / "scripts" / "quit.sh"))
    status_sh = shlex.quote(str(REPO_ROOT / "scripts" / "check-status.sh"))
    return f"""#!/usr/bin/env bash
# {GENERATED_MARKER} — {time.strftime("%Y-%m-%d %H:%M:%S")}
# 重新設定:cd {REPO_ROOT} && ./set_config.sh
#
# 偵測到的 GPU:
{gpu_lines}
#
# 配置(模型 @ GPU index):
#   main      = {plan.main_key} @ GPU {plan.main.gpu.index}
#   embedding = {plan.embedding.candidate.path.name} @ GPU {plan.embedding.gpu.index}
#   reranker  = {plan.reranker.candidate.path.name} @ GPU {plan.reranker.gpu.index} (internal buffer={plan.reranker_ctx})
#   vl        = {plan.vl.candidate.path.name} @ GPU {plan.vl.gpu.index}
#
# 啟動參數(全部來自你在 set_config 的作答):ctx={plan.ctx}, threads={plan.parameters.get("threads")}, {offload}
#   reranker:-c/-b/-ub {plan.reranker_ctx};附屬服務:-np {AUX_PARALLEL}
#   VL:-ngl auto --fit on --fit-target {VL_FIT_TARGET_MIB}
#   綁定:{bind_note}
#   完整參數在 ~/.config/codetrail/deployment.json;實際指令預覽:~/start.sh --dry-run
#
# 子命令:
#   ~/start.sh                     啟動四個 llama-server(tmux 背景)
#   ~/start.sh status [--strict]   檢查四個 server 狀態(= scripts/check-status.sh)
#   ~/start.sh stop [--force]      全部停止,等到 process 退出、VRAM 釋放完畢才返回(= scripts/quit.sh)
#   ~/start.sh logs [role] [行數|-f] 看 server log(role 可省略,預設 main;啟動起即時寫入)
#   ~/start.sh help                顯示子命令說明
set -euo pipefail

# 先清掉會遮蔽 ~/.config/codetrail 設定檔的舊環境變數(例如寫在 ~/.bashrc 的
# EMBED_MODEL / MAIN_CTX / CUDA_VISIBLE_DEVICES / SESSION 名稱)。清單來自
# deployment_profile.RUNTIME_OVERRIDE_ENV_KEYS;進階覆寫請改 deployment.json。
# 放在子命令之前:launch / stop / status 三條路看到的 session 名與設定才一致。
unset {unset_line} 2>/dev/null || true

# 本設定的權威值,同樣放在子命令之前:launch 用它們啟動,
# status --strict 用 GPU selector 驗證各 role 沒跑錯卡(放在 case 之後
# status 會拿不到期望值,wrong-GPU 檢查等於沒開);stop 只看預設 session 名,不受影響。
export AICODE_MODEL={shlex.quote(plan.main_key)}
# set_config 驗證過的 llama-server(含 --fit/--cpu-moe/--n-cpu-moe 旗標探測)就是這顆;
# 換位置後請重跑 ./set_config.sh 重新偵測。
export LLAMA_BIN={shlex.quote(str(_llama_bin()))}
{exports}

case "${{1:-}}" in
  status)
    shift
    exec {status_sh} "$@"
    ;;
  stop|quit)
    shift
    exec {quit_sh} "$@"
    ;;
  logs)
    if [ "$#" -gt 3 ]; then
      echo "logs 參數過多(用法:~/start.sh logs [role] [行數|-f];role 可省略,預設 main)" >&2
      exit 2
    fi
    role="${{2:-main}}"
    tail_spec="${{3:-}}"
    case "$role" in
      main|embedding|reranker|vl) ;;
      *)
        # 允許省略 role:logs -f / logs 200 → role 用預設 main。
        if [ -n "$tail_spec" ]; then
          echo "未知 role:$role(可用:main / embedding / reranker / vl)" >&2
          exit 2
        fi
        case "$role" in
          -f|f) tail_spec="$role"; role=main ;;
          *[!0-9]*)
            echo "未知 role:$role(可用:main / embedding / reranker / vl)" >&2
            exit 2
            ;;
          *) tail_spec="$role"; role=main ;;
        esac
        ;;
    esac
    log_file="${{XDG_STATE_HOME:-$HOME/.local/state}}/codetrail/logs/$role.log"
    if [ ! -f "$log_file" ]; then
      echo "找不到 $log_file — 該 role 尚未啟動過(先執行 ~/start.sh)" >&2
      exit 1
    fi
    if [ "$tail_spec" = "-f" ] || [ "$tail_spec" = "f" ]; then
      exec tail -f "$log_file"
    fi
    exec tail -n "${{tail_spec:-120}}" "$log_file"
    ;;
  help|-h|--help)
    cat <<'CODETRAIL_USAGE'
用法:~/start.sh [子命令|啟動器旗標]
  (無參數)                 啟動四個 llama-server(tmux 背景)
  --dry-run                只印出將執行的四條 llama-server 指令(其餘旗標見 scripts/start-all.sh --help)
  status [--strict]        檢查四個 server 狀態
  stop [--force]           全部停止並等到 VRAM 釋放完畢(--force 連孤兒 llama-server 一併處理)
  logs [role] [行數|-f]     看 server log(role 可省略,預設 main;-f 持續追蹤)
  help                     顯示本說明
CODETRAIL_USAGE
    echo "重新設定:cd {REPO_ROOT} && ./set_config.sh"
    exit 0
    ;;
  ""|-*)
    ;;  # 無參數 → 啟動;旗標(如 --dry-run)→ 轉交 start-all.sh
  *)
    echo "未知子命令:$1(可用:status / stop / logs / help;啟動器旗標如 --dry-run 會轉交 start-all.sh)" >&2
    exit 2
    ;;
esac

rc=0
{shlex.quote(str(REPO_ROOT / "scripts" / "start-all.sh"))} "$@" || rc=$?
if [ "$rc" -eq 0 ]; then
  case " $* " in
    *" --dry-run "*) ;;  # 純預覽沒有真的啟動,不需要監控提醒
    *)
      echo ""
      echo "[start.sh] 提醒:set_config 不做容量估算,請用 nvidia-smi 稍微監控 GPU/VRAM 使用狀況(例如:watch -n 1 nvidia-smi);異常時用 ~/start.sh logs <role> 查原因。"
      ;;
  esac
fi
exit "$rc"
"""


# ---------------------------------------------------------------------------
# transaction 寫入 / 備份還原
# ---------------------------------------------------------------------------

def _backup(path: Path, notes: list[str]) -> Path | None:
    if path.exists():
        stamp = time.strftime("%Y%m%d-%H%M%S")
        backup = path.with_name(f"{path.name}.bak-setconfig-{stamp}")
        shutil.copy2(path, backup)
        notes.append(f"已備份原有 {path} → {backup.name}")
        return backup
    return None


def _manifest_path(home: Path) -> Path:
    return home / ".config" / "codetrail" / "setconfig-last-transaction.json"


_SENSITIVE_KEY_RE = re.compile(r"(?i)api[_-]?key|token|secret|password|authorization|credential")
_REDACTED = "***redacted***"


def _redact_for_display(content: str) -> str:
    """dry-run 印出用:JSON 內容中憑證類欄位的值以遮罩取代。

    --dry-run 常被貼進 issue 或跑在 CI log;合併後的 opencode.json 會帶著使用者
    既有 provider 的 apiKey,原文印出等於把憑證寫進 log。只影響顯示,不影響寫入。
    """
    changed = False

    def _walk(node):
        nonlocal changed
        if isinstance(node, dict):
            result = {}
            for key, value in node.items():
                if isinstance(value, str) and value and \
                        isinstance(key, str) and _SENSITIVE_KEY_RE.search(key):
                    result[key] = _REDACTED
                    changed = True
                else:
                    result[key] = _walk(value)
            return result
        if isinstance(node, list):
            return [_walk(item) for item in node]
        return node

    try:
        data = json.loads(content)
    except ValueError:
        return content
    redacted = _walk(data)
    if not changed:
        return content
    return json.dumps(redacted, ensure_ascii=False, indent=2) + "\n"


def commit_files(targets: list[tuple[Path, str, int]], notes: list[str], dry_run: bool,
                 home: Path | None = None) -> None:
    """四個產物的 transaction:全部先寫 staging,備份既有檔,再逐一原子替換;
    任一步失敗 → 還原備份、清掉 staging,不留半套狀態。成功後寫入 transaction
    manifest(同一次設定的備份對應表),讓 --restore-last-backup 能整批一致還原。"""
    if dry_run:
        for path, content, _mode in targets:
            display = _redact_for_display(content)
            suffix = "(憑證類欄位值已遮罩;實際寫入不受影響)" if display != content else ""
            print(f"\n--- [dry-run] 將寫入 {path}{suffix} ---\n{display}", end="")
        return

    def _real_target(path: Path) -> Path:
        # dotfiles 使用者常把 ~/.config 下的檔案做成 symlink;os.replace 會把
        # 連結本身換成一般檔。改寫到連結目標,保留使用者的連結結構。
        if not path.is_symlink():
            return path
        try:
            real = path.resolve()
        except (OSError, RuntimeError):
            return path
        notes.append(f"{path} 是 symlink → 實際寫入 {real}(保留連結)。")
        return real

    staged: list[tuple[Path, Path, Path, int]] = []
    try:
        for path, content, mode in targets:
            real = _real_target(path)
            real.parent.mkdir(parents=True, exist_ok=True)
            tmp = real.with_name(f"{real.name}.setconfig-staging-{os.getpid()}")
            tmp.write_text(content, encoding="utf-8")
            tmp.chmod(mode)
            staged.append((tmp, path, real, mode))
    except BaseException:
        for tmp, _path, _real, _mode in staged:
            tmp.unlink(missing_ok=True)
        raise

    backups: dict[Path, Path | None] = {}
    existed: dict[Path, bool] = {}
    replaced: list[tuple[Path, Path]] = []
    try:
        for _tmp, path, real, _mode in staged:
            existed[path] = path.exists()
            backups[path] = _backup(real, notes)
        for tmp, path, real, _mode in staged:
            os.replace(tmp, real)
            replaced.append((path, real))
    except BaseException:
        for path, real in replaced:
            backup = backups.get(path)
            if backup is not None:
                shutil.copy2(backup, real)
            else:
                real.unlink(missing_ok=True)
        for tmp, _path, _real, _mode in staged:
            Path(tmp).unlink(missing_ok=True)
        raise

    global _COMMITTED
    _COMMITTED = True

    if home is not None:
        manifest = {
            "transaction": time.strftime("%Y%m%d-%H%M%S"),
            "targets": {
                str(path): {
                    "existed": existed.get(path, False),
                    "backup": str(backups[path]) if backups.get(path) else None,
                }
                for _tmp, path, _real, _mode in staged
            },
        }
        try:
            _manifest_path(home).write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        except OSError as exc:
            notes.append(f"⚠ transaction manifest 寫入失敗({exc});--restore-last-backup 會退回逐檔模式。")


def restore_last_backup(home: Path, dry_run: bool = False) -> int:
    """依最近一次 transaction manifest 整批還原:當時存在的檔案還原備份、
    當時不存在的檔案刪除。沒有 manifest 才退回「逐檔最新備份」的舊行為。
    dry_run=True 只列出會做的動作,不動任何檔案(--dry-run 的承諾對這條路也成立)。"""
    prefix = "[dry-run] 會" if dry_run else "已"
    manifest_file = _manifest_path(home)
    if manifest_file.is_file():
        try:
            manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
            targets = manifest.get("targets", {})
        except (OSError, json.JSONDecodeError) as exc:
            print(f"[set_config] manifest 無法解析({exc}),退回逐檔模式。", file=sys.stderr)
            targets = {}
        if targets:
            print(f"[set_config] 依 transaction {manifest.get('transaction')} 整批還原:")
            restored = 0
            for target_str, info in targets.items():
                target = Path(target_str)
                if info.get("existed") and info.get("backup"):
                    backup = Path(info["backup"])
                    if backup.is_file():
                        if not dry_run:
                            shutil.copy2(backup, target)
                        print(f"  {prefix}還原 {target} ← {backup.name}")
                        restored += 1
                    else:
                        print(f"  ⚠ 備份不見了:{backup}(略過 {target.name})")
                else:
                    if not dry_run:
                        target.unlink(missing_ok=True)
                    print(f"  {prefix}移除 {target}(該次設定前不存在)")
                    restored += 1
            if dry_run:
                print(f"[dry-run] 以上 {restored}/{len(targets)} 個動作未執行(拿掉 --dry-run 才會還原)。")
            else:
                print(f"[set_config] 完成:{restored}/{len(targets)} 個檔案回到該次設定前狀態。")
            return 0 if restored else 2

    # 舊備份(無 manifest)的退路:逐檔取最新備份,可能混合不同次設定。
    print("[set_config] 找不到 transaction manifest,退回逐檔最新備份(可能混合不同次設定):")
    targets = [
        home / ".config" / "codetrail" / "models.json",
        home / ".config" / "codetrail" / "deployment.json",
        home / ".config" / "opencode" / "opencode.json",
        home / "start.sh",
    ]
    restored = 0
    for target in targets:
        backups = sorted(target.parent.glob(f"{target.name}.bak-setconfig-*"))
        if not backups:
            print(f"  (略過)沒有 {target.name} 的備份")
            continue
        latest = backups[-1]
        if not dry_run:
            shutil.copy2(latest, target)
        print(f"  {prefix}還原 {target} ← {latest.name}")
        restored += 1
    if restored == 0:
        print("[set_config] 找不到任何 *.bak-setconfig-* 備份,未做任何變更。")
        return 2
    if dry_run:
        print(f"[dry-run] 以上 {restored} 個還原動作未執行(拿掉 --dry-run 才會還原)。")
    else:
        print(f"[set_config] 已還原 {restored} 個檔案。")
    return 0


# ---------------------------------------------------------------------------
# 驗證、預覽、運行中偵測
# ---------------------------------------------------------------------------

def _fresh_env(plan: Plan) -> dict[str, str]:
    env = {key: value for key, value in os.environ.items() if key not in _OVERRIDE_ENV_KEYS}
    env["AICODE_MODEL"] = plan.main_key
    return env


def _sanitized_subprocess_env() -> dict[str, str]:
    """啟停子程序用的乾淨環境:同 ~/start.sh 開頭的 unset(override + session 名)。

    quit.sh / start.sh 必須看到同一組「預設」session 名;桌面環境常見的泛用
    SESSION 變數若流進 stop_servers,會殺錯無關的 tmux session、漏掉真正的
    codetrail-rag,接著重啟就撞 session already exist。
    """
    return {
        key: value for key, value in os.environ.items()
        if key not in _OVERRIDE_ENV_KEYS and key not in _SESSION_ENV_KEYS
    }


def _restart_servers(start_path: Path) -> int:
    """[R] 自動重啟:先 quit 再 start,兩者都用 sanitized env。"""
    env = _sanitized_subprocess_env()
    subprocess.run(["bash", str(REPO_ROOT / "scripts" / "quit.sh")], check=False, env=env)
    print("  已停止舊 server;開始啟動新設定(載入大模型需要幾分鐘)…")
    return subprocess.run(["bash", str(start_path)], check=False, env=env).returncode


def validate_payloads(plan: Plan, deployment_json: str, registry_json: str) -> None:
    """寫入正式檔之前,用 staging 內容跑一次 deployment_profile 完整驗證。"""
    env = _fresh_env(plan)
    env["AICODE_MODEL_REGISTRY"] = registry_json
    tmp = tempfile.NamedTemporaryFile(
        "w", suffix=".json", prefix="codetrail-setconfig-", delete=False, encoding="utf-8"
    )
    try:
        tmp.write(deployment_json)
        tmp.close()
        env["AICODE_DEPLOYMENT_CONFIG"] = tmp.name
        load_effective_profile(env)
    except ProfileError as exc:
        raise SetupError(f"產生的設定未通過 deployment profile 驗證(未寫入任何檔案):{exc}") from exc
    finally:
        Path(tmp.name).unlink(missing_ok=True)


def preview_start_commands(plan: Plan) -> int:
    """跑 start-all.sh --dry-run,把最終 llama-server 指令(推薦參數)印給使用者。"""
    env = _fresh_env(plan)
    env["MAIN_GPU"] = plan.main.gpu.selector
    env["EMBED_GPU"] = plan.embedding.gpu.selector
    env["RERANK_GPU"] = plan.reranker.gpu.selector
    env["VL_GPU"] = plan.vl.gpu.selector
    try:
        proc = subprocess.run(
            ["bash", str(REPO_ROOT / "scripts" / "start-all.sh"), "--dry-run"],
            env=env,
            capture_output=True,
            text=True,
            check=False,
            timeout=120,
        )
    except subprocess.TimeoutExpired:
        print("⚠ 啟動參數預覽逾時(120 秒);設定檔已寫入,可直接用 ~/start.sh --dry-run 重試預覽。",
              file=sys.stderr)
        return 1
    print("\n=== 推薦啟動參數(~/start.sh 實際會執行的指令)===")
    if proc.stdout:
        print(proc.stdout, end="")
    if proc.returncode != 0:
        print(proc.stderr, end="", file=sys.stderr)
        print("⚠ 啟動參數預覽失敗(見上方訊息);請修正後重跑 ./set_config.sh。",
              file=sys.stderr)
    return proc.returncode


def running_codetrail_sessions() -> list[str]:
    if not shutil.which("tmux"):
        return []
    # 探測「env 指定名 ∪ 預設名」:~/start.sh 內部會 unset session env 再啟動,
    # 實際 session 幾乎都是預設名;桌面環境把通用變數 SESSION 設走時,
    # 只看 env 會漏掉真正在跑的 codetrail-rag。
    names: list[str] = []
    for name in (
        os.environ.get("MAIN_SESSION"), "codetrail-main",
        os.environ.get("SESSION"), os.environ.get("AUX_SESSION"), "codetrail-rag",
    ):
        if name and name not in names:
            names.append(name)
    running = []
    for name in names:
        probe = subprocess.run(
            ["tmux", "has-session", "-t", name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if probe.returncode == 0:
            running.append(name)
    return running


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def _n_cpu_moe_arg(raw: str) -> int:
    try:
        value = int(raw)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("必須是整數") from exc
    if not 0 <= value <= MAX_N_CPU_MOE:
        raise argparse.ArgumentTypeError(
            f"必須在 0..{MAX_N_CPU_MOE}(deployment schema 的允許範圍)"
        )
    return value


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="CodeTrail 一鍵設定:偵測 GPU/模型 → 互動問答(只驗證輸入範圍,"
                    "不做容量估算)→ 產生設定檔與 ~/start.sh",
    )
    parser.add_argument("--models-dir", help="模型目錄(未指定時用 $MODELS_DIR 或 ~/models)")
    parser.add_argument(
        "--yes", action="store_true",
        help="非互動:跳過提問與確認頁;所有互動題的值必須由旗標提供,缺哪個就報錯",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--cpu-moe", dest="cpu_moe", action="store_true",
        help="主聊天模型啟用全 CPU-MoE(--cpu-moe;experts 全放 RAM;只對 MoE 主模型有效;"
             "不影響三個附屬模型)",
    )
    mode.add_argument(
        "--no-cpu-moe", dest="cpu_moe", action="store_false",
        help="主聊天模型使用一般模式(不詢問 CPU-MoE)",
    )
    mode.add_argument(
        "--n-cpu-moe", dest="n_cpu_moe", type=_n_cpu_moe_arg, metavar="N",
        help="主聊天模型部分 CPU-MoE:前 N 層 MoE experts 留 RAM、其餘進 GPU"
             f"(蘊含 CPU-MoE 模式;0..{MAX_N_CPU_MOE},超過最大 blk 編號視同 --cpu-moe)",
    )
    parser.set_defaults(cpu_moe=None, n_cpu_moe=None)
    parser.add_argument("--dry-run", action="store_true", help="只顯示會寫入的內容,不動任何檔案")
    parser.add_argument("--allow-remote", action="store_true",
                        help="讓區網其他機器可連線模型 API(未指定只綁 127.0.0.1;llama-server 無認證,慎用)")
    parser.add_argument("--restore-last-backup", action="store_true",
                        help="把四個產物還原到最近一次 *.bak-setconfig-* 備份後離開")
    parser.add_argument("--skip-deps-check", action="store_true", help="跳過 Python 依賴檢查")
    parser.add_argument("--skip-binary-check", action="store_true",
                        help="跳過 llama-server / tmux 檢查(自動化測試用)")
    for role in ("main", "embed", "rerank", "vl"):
        parser.add_argument(f"--{role}-model", help=f"{role} 模型:候選編號(從 1 起)或 .gguf 絕對路徑")
        parser.add_argument(f"--{role}-gpu", help=f"{role} 要綁的 GPU index")
    parser.add_argument("--vl-mmproj", help="VL mmproj .gguf 絕對路徑(同目錄唯一 mmproj 時自動配對)")
    parser.add_argument("--ctx", "--n-ctx", dest="ctx", type=int,
                        help=f"主模型 n_ctx(-c),{MIN_MAIN_CTX}..{MAX_MAIN_CTX}")
    parser.add_argument(
        "--rerank-ctx",
        "--reranker-ctx",
        dest="reranker_ctx",
        type=int,
        help=(
            "進階:覆寫 reranker internal -c/-b/-ub buffer;"
            f"未指定自動 {DEFAULT_RERANKER_CTX}({MIN_RERANKER_CTX}..{MAX_RERANKER_CTX})"
        ),
    )
    parser.add_argument("--threads", type=int, help=f"主模型 CPU threads(-t),1..{MAX_THREADS}")
    parser.add_argument("--no-preview", action="store_true", help="結尾不跑 start-all.sh --dry-run 預覽")
    return parser


def _print_summary_page(plan: Plan, python_bin: str, opencode_changes: list[str],
                        codetrail_dir: Path, opencode_path: Path, start_path: Path) -> None:
    offload = _offload_description(plan)
    print("\n=== 設定摘要(全部來自你的作答;確認一次即可)===")
    print(f"  主聊天    : {plan.main.candidate.describe()}")
    print(f"              → GPU {plan.main.gpu.index}({plan.main.gpu.name})")
    print(f"  embedding : {plan.embedding.candidate.path.name} → GPU {plan.embedding.gpu.index}")
    print(
        f"  reranker  : {plan.reranker.candidate.path.name} → GPU {plan.reranker.gpu.index}"
        f"（internal buffer={plan.reranker_ctx}）"
    )
    print(f"  VL        : {plan.vl.candidate.path.name} + {plan.vl.mmproj.name}"
          f" → GPU {plan.vl.gpu.index}")
    print(f"  參數      : ctx={plan.ctx}、threads={plan.threads}、{offload}")
    bind = "0.0.0.0(區網可連,無認證!)" if plan.allow_remote else "127.0.0.1(僅本機)"
    print(f"  綁定      : {bind}")
    print(f"  MCP Python: {python_bin}")
    print("  產物      :")
    print(f"    {codetrail_dir / 'models.json'} / {codetrail_dir / 'deployment.json'}")
    print(f"    {opencode_path}")
    print(f"    {start_path}")
    if opencode_changes:
        print("  opencode.json 變更:")
        for change in opencode_changes:
            print(f"    - {change}")
    for note in plan.notes:
        print(f"  {note if note.startswith('⚠') else '- ' + note}")


def run(args: argparse.Namespace) -> int:
    home = Path(os.path.expanduser("~"))
    if args.restore_last_backup:
        return restore_last_backup(home, dry_run=args.dry_run)

    # 旗標的早期友善驗證(choose_int 也會擋;這裡在做任何偵測前先給清楚訊息)。
    if args.ctx is not None and not MIN_MAIN_CTX <= args.ctx <= MAX_MAIN_CTX:
        raise SetupError(
            f"--ctx 請設在 {MIN_MAIN_CTX}..{MAX_MAIN_CTX}"
            "(llama-server -c;過小會讓 RAG/工具流程無法運作)。"
        )
    if args.threads is not None and not 1 <= args.threads <= MAX_THREADS:
        raise SetupError(f"--threads 請設在 1..{MAX_THREADS}。")
    if args.reranker_ctx is not None and \
            not MIN_RERANKER_CTX <= args.reranker_ctx <= MAX_RERANKER_CTX:
        raise SetupError(f"--rerank-ctx 請設在 {MIN_RERANKER_CTX}..{MAX_RERANKER_CTX}。")

    # 相對路徑立刻轉絕對(不解 symlink):候選/registry 全存絕對路徑,
    # 否則 --models-dir ./models 會一路活到最後 schema 驗證才爆。
    models_dir = Path(os.path.abspath(
        Path(args.models_dir or os.environ.get("MODELS_DIR") or (home / "models")).expanduser()
    ))

    print("=== CodeTrail set_config ===")
    base_notes: list[str] = []
    python_bin = _detect_python(args.skip_deps_check, base_notes)
    print(f"[1/5] [PASS] Python(MCP server 用):{python_bin}")
    _check_tmux(args.skip_binary_check, base_notes)
    llama_caps = check_llama_binary(args.skip_binary_check, base_notes)
    print(f"[2/5] [PASS] tmux 與 llama-server({_llama_bin()};--fit "
          f"{'支援' if llama_caps.get('fit') else '不支援'})")

    gpus = detect_gpus()
    print(f"[3/5] [PASS] 偵測到 {len(gpus)} 顆 NVIDIA GPU:")
    for gpu in gpus:
        print(f"      {gpu.describe()}")

    candidates, broken = scan_models(models_dir, notes=base_notes)
    print(f"[4/5] [PASS] 掃描 {models_dir}:main={len(candidates['main'])}、"
          f"embedding={len(candidates['embedding'])}、reranker={len(candidates['reranker'])}、"
          f"vl={len(candidates['vl'])} 個候選")

    overrides = {"main": args.main_model, "embedding": args.embed_model,
                 "reranker": args.rerank_model, "vl": args.vl_model}

    warnings = precheck(gpus, candidates, broken, overrides)
    print("[5/5] [PASS] 初步判定 OK:GPU 與四類模型(main / embedding / reranker / vl+mmproj)齊全")
    for warning in warnings:
        print(f"      ⚠ {warning}")

    # deployment/registry 的 env override(文件允許的自訂路徑)只影響 aicode/doctor
    # 等 runtime 讀取;本工具固定寫預設路徑,產生的 ~/start.sh 也刻意 unset 這些變數
    # (防 .bashrc 殘留)。設了卻不提醒,使用者會拿到「aicode 與 start.sh 各讀一份」。
    split_env = [
        key for key in ("AICODE_DEPLOYMENT_CONFIG", "AICODE_PROFILE",
                        "AICODE_MODEL_REGISTRY", "AICODE_MODEL_REGISTRY_FILE")
        if (os.environ.get(key) or "").strip()
    ]
    if split_env:
        base_notes.append(
            "⚠ 偵測到環境變數 " + "、".join(split_env)
            + ":本工具只寫入預設路徑(~/.config/codetrail/*),而 ~/start.sh 啟動時會刻意"
            " unset 這些 override——aicode/doctor 會讀你的自訂檔,~/start.sh 卻讀預設檔,"
            "兩邊將各用一份設定。建議 unset 後重跑;要用自訂檔請自行維護其內容。"
        )

    codetrail_dir = home / ".config" / "codetrail"
    # OpenCode 與本 repo 的 config.py/aicode 都會先讀 OPENCODE_CONFIG;
    # set_config 若寫死預設路徑,設了這個變數的使用者會拿到 PASS 但完全沒生效的設定。
    opencode_env = (os.environ.get("OPENCODE_CONFIG") or "").strip()
    if opencode_env:
        opencode_path = Path(os.path.abspath(Path(opencode_env).expanduser()))
        base_notes.append(
            f"OPENCODE_CONFIG 已設定 → OpenCode 設定寫入 {opencode_path}(非預設路徑)。"
        )
    else:
        opencode_path = home / ".config" / "opencode" / "opencode.json"
    start_path = home / "start.sh"
    if start_path.exists():
        try:
            if GENERATED_MARKER not in start_path.read_text(encoding="utf-8", errors="replace"):
                base_notes.append(
                    f"⚠ {start_path} 已存在且不是 set_config 產生的;原檔會備份後才覆寫"
                    "(不想覆寫請離開,先把該檔改名)。"
                )
        except OSError:
            pass

    def _gather(notes: list[str]) -> dict:
        """一趟互動問答 + 產物組裝(使用者題無預設值,只驗證輸入範圍)。"""
        # 互動也必須明確列出 main 候選,不能靜默拿排序第一顆;否則多顆
        # 大模型並存時,使用者會在不知道模型名稱的情況下替錯誤的模型選模式。
        main_cand = choose_candidate("【主聊天模型】", candidates["main"], args.main_model,
                                     assume_yes=args.yes, flag_name="--main-model")
        main_gpu = choose_gpu("【主聊天模型】", gpus, args.main_gpu,
                              assume_yes=args.yes, flag_name="--main-gpu")

        # 先決定 main 的 CPU-MoE / 一般模式,再詢問任何附屬模型選項。
        # GGUF 只讀 header/tensor table,不讀權重內容,也不執行模型。
        try:
            main_layout: ModelLayout | None = inspect_model_layout(main_cand)
        except SetupError as exc:
            main_layout = None
            notes.append(f"⚠ 主模型 placement metadata 無法分析:{exc}")
        is_moe = main_layout is not None and main_layout.is_moe

        # --n-cpu-moe(部分 offload)蘊含 CPU-MoE 模式;與 --cpu-moe/--no-cpu-moe
        # 在 argparse 層互斥,這裡只需補上模式 override 並驗證輸入對這顆模型合理。
        mode_override = args.cpu_moe
        if args.n_cpu_moe is not None:
            if not is_moe:
                raise SetupError(
                    "--n-cpu-moe 只對 MoE 主模型有意義:未在 "
                    f"{main_cand.path.name} 偵測到 expert tensors(或 GGUF 無法解析)。"
                )
            mode_override = True
        if mode_override is True and main_layout is not None and not main_layout.is_moe:
            raise SetupError(
                f"--cpu-moe 只對 MoE 主模型有意義:{main_cand.path.name} "
                "未偵測到 expert tensors。"
            )
        cpu_moe = choose_cpu_moe_mode(
            mode_override,
            assume_yes=args.yes,
            candidate=main_cand,
            layout=main_layout,
            supported=llama_caps.get("cpu_moe", False),
            notes=notes,
        )
        if cpu_moe and not llama_caps.get("cpu_moe", False):
            raise SetupError(
                "CPU-MoE 模式需要 llama-server 的 --cpu-moe,但目前 build 不支援。\n"
                "  修復:更新並重新 build llama.cpp(README §1.5),或改用 --no-cpu-moe。"
            )

        # 部分 CPU-MoE(--n-cpu-moe)檔位:--cpu-moe 明確代表「全部放 RAM」,不再詢問;
        # 其餘情況(互動答 y / --n-cpu-moe 旗標)由使用者輸入,只驗證範圍。
        n_cpu_moe: int | None = None
        if cpu_moe and is_moe and args.cpu_moe is not True:
            if not llama_caps.get("n_cpu_moe", False):
                if args.n_cpu_moe is not None:
                    raise SetupError(
                        "--n-cpu-moe 需要 llama-server 支援,但目前 build 沒有這個旗標。\n"
                        "  修復:更新並重新 build llama.cpp(README §1.5),或改用 --cpu-moe。"
                    )
                notes.append(
                    "⚠ 這個 llama-server 不支援 --n-cpu-moe(部分 offload)→ "
                    "使用全 CPU-MoE(--cpu-moe);更新並重新 build llama.cpp 後可用。"
                )
            else:
                n_cpu_moe = choose_n_cpu_moe(
                    args.n_cpu_moe, assume_yes=args.yes, layout=main_layout
                )

        embed_cand = choose_candidate("【embedding 模型】", candidates["embedding"],
                                      args.embed_model, assume_yes=args.yes,
                                      flag_name="--embed-model")
        embed_gpu = choose_gpu("【embedding 模型】", gpus, args.embed_gpu,
                               assume_yes=args.yes, flag_name="--embed-gpu")
        rerank_cand = choose_candidate("【reranker 模型】", candidates["reranker"],
                                       args.rerank_model, assume_yes=args.yes,
                                       flag_name="--rerank-model")
        rerank_gpu = choose_gpu("【reranker 模型】", gpus, args.rerank_gpu,
                                assume_yes=args.yes, flag_name="--rerank-gpu")
        reranker_ctx = choose_reranker_ctx(rerank_cand, args.reranker_ctx, assume_yes=args.yes)
        vl_cand = choose_candidate("【VL 模型】", candidates["vl"], args.vl_model,
                                   assume_yes=args.yes, flag_name="--vl-model")
        vl_gpu = choose_gpu("【VL 模型】", gpus, args.vl_gpu,
                            assume_yes=args.yes, flag_name="--vl-gpu")

        # 混放目錄(mmproj 歸屬不明)必然產生多顆 VL 候選:上面的 choose_candidate
        # 已保證互動必答、--yes 必給 --vl-model,不會自動吞排序第一名;
        # 使用者選定後,同目錄唯一 mmproj 由 resolve_vl_mmproj 配對。
        vl_mmproj = resolve_vl_mmproj(vl_cand, args.vl_mmproj, interactive=not args.yes)

        # 綁定是安全 opt-in,不是互動題:未給 --allow-remote 一律只綁 127.0.0.1。
        allow_remote = bool(args.allow_remote)

        ctx = choose_int("主模型 n_ctx(-c)", args.ctx, assume_yes=args.yes,
                         minimum=MIN_MAIN_CTX, maximum=MAX_MAIN_CTX, flag_name="--ctx")
        threads = choose_int("主模型 CPU threads(-t)", args.threads, assume_yes=args.yes,
                             minimum=1, maximum=MAX_THREADS, flag_name="--threads")
        if ctx < 8192:
            notes.append(
                f"⚠ 主模型 ctx={ctx} 偏小:CodeTrail 的 RAG/工具流程需要較大 context,"
                "OpenCode 的 limit.context 也會同步為此值。"
            )
        cores = os.cpu_count() or 0
        if cores and threads > cores:
            notes.append(f"⚠ threads={threads} 超過偵測到的核心數({cores}),通常反而較慢。")

        # 只剩 VL 模型可當 main 時要明確確認(自動排序已保證:有非 VL 候選就不會選到 VL)。
        if main_cand.vl_paired and args.main_model is None and all(
            cand.vl_paired for cand in candidates["main"]
        ):
            if not args.yes:
                while True:
                    raw = _input(
                        f"沒有非 VL 的主聊天模型;要把 VL 模型 {main_cand.path.name} 同時當 main 嗎?"
                        "(工具呼叫行為視模型而定;y/n): "
                    ).strip().lower()
                    if raw in {"y", "yes"}:
                        break
                    if raw in {"n", "no"}:
                        raise SetupError(
                            "已取消:請先下載一顆主聊天模型(README §2.2)再重跑 ./set_config.sh。"
                        )
                    print("  請輸入 y 或 n。")
            notes.append(
                f"⚠ 沒有非 VL 的主聊天模型候選,已把 VL 模型 {main_cand.path.name} 同時當 main"
                "(VL service 會再載一份)。工具呼叫品質視該模型而定;"
                "建議另外下載一顆主聊天模型(README §2.2)。"
                "若這其實是一般聊天模型,把同目錄的 mmproj 移到 VL 模型自己的目錄後重跑即可。"
            )

        plan = Plan(
            gpus=gpus,
            main=Selection("main", main_cand, main_gpu),
            embedding=Selection("embedding", embed_cand, embed_gpu),
            reranker=Selection("reranker", rerank_cand, rerank_gpu),
            vl=Selection("vl", vl_cand, vl_gpu, mmproj=vl_mmproj),
            main_key=sanitize_registry_key(main_cand.path),
            ctx=ctx,
            threads=threads,
            batch=0,
            ubatch=0,
            reranker_ctx=reranker_ctx,
            cpu_moe=cpu_moe,
            n_cpu_moe=n_cpu_moe,
            main_layout=main_layout,
            allow_remote=allow_remote,
            parameters={},
            notes=notes,
        )
        if args.reranker_ctx is not None:
            notes.append(reranker_ctx_effect(reranker_ctx))
        _warn_unverified_aux(plan)

        parameters, batch, ubatch = build_main_parameters(
            main_cand, ctx, threads, llama_caps.get("fit", True), cpu_moe, notes,
            n_cpu_moe=n_cpu_moe,
        )
        plan.parameters = parameters
        plan.batch = batch
        plan.ubatch = ubatch
        notes.append(
            f"附屬服務固定配置:三個服務 -np {AUX_PARALLEL};VL 最後啟動並用"
            f" -ngl auto --fit on --fit-target {VL_FIT_TARGET_MIB},依當下剩餘 VRAM"
            " 自動 offload(llama.cpp 會另計 mmproj worst-case memory)。"
        )
        notes.append(
            "本工具不做容量估算:VRAM/RAM 是否放得下,以 ~/start.sh 啟動後"
            " nvidia-smi 實測為準(啟動結尾會提醒)。"
        )
        if allow_remote:
            notes.append("⚠ --allow-remote:四個 llama-server 會綁 0.0.0.0,同網段任何人都能呼叫模型 API"
                         "(llama-server 無認證)。只在可信內網使用,必要時加防火牆規則。")

        registry = build_models_registry(plan, codetrail_dir / "models.json", notes)
        registry_json = json.dumps(registry, ensure_ascii=False, indent=2) + "\n"
        deployment_config = build_deployment_config(plan)
        merge_existing_deployment(deployment_config, codetrail_dir / "deployment.json", notes)
        deployment_json = json.dumps(deployment_config, ensure_ascii=False, indent=2) + "\n"
        # OpenCode 的 baseURL 必須對齊合併後 deployment 的 main endpoint
        # (使用者手改 port/base_url 時才會出現在 config;否則用預設 8080)。
        main_service = deployment_config["services"]["main"]
        main_base_url = main_service.get("base_url")
        if main_base_url is None and isinstance(main_service.get("port"), int):
            main_base_url = f"http://localhost:{main_service['port']}"
        opencode_config, opencode_changes = build_opencode_config(
            plan, python_bin, opencode_path, main_base_url
        )
        opencode_json = json.dumps(opencode_config, ensure_ascii=False, indent=2) + "\n"

        # 寫入正式檔之前,用 staging 內容跑一次 deployment_profile 完整驗證。
        validate_payloads(plan, deployment_json, registry_json)
        return {
            "plan": plan,
            "registry_json": registry_json,
            "deployment_json": deployment_json,
            "opencode_json": opencode_json,
            "opencode_changes": opencode_changes,
            "start_content": build_start_sh(plan),
        }

    notes = list(base_notes)
    bundle = _gather(notes)
    plan: Plan = bundle["plan"]
    _print_summary_page(plan, python_bin, bundle["opencode_changes"],
                        codetrail_dir, opencode_path, start_path)
    if not args.yes and not args.dry_run:
        while True:
            answer = _input("\n[Enter] 採用並寫入 / [q] 離開: ").strip().lower()
            if answer in {"", "y", "yes"}:
                break
            if answer == "q":
                print("[set_config] 已離開,未寫入任何檔案。")
                return 0
            print(f"  無效輸入 {answer!r}:Enter=採用寫入 / q=離開。")

    commit_mark = len(plan.notes)
    commit_files(
        [
            (codetrail_dir / "models.json", bundle["registry_json"], 0o644),
            (codetrail_dir / "deployment.json", bundle["deployment_json"], 0o644),
            # opencode.json 會保留使用者既有 provider 的 apiKey → 只給擁有者讀寫,
            # 也不能把使用者原本的 0600 重跑成 0644。
            (opencode_path, bundle["opencode_json"], 0o600),
            (start_path, bundle["start_content"], 0o755),
        ],
        plan.notes,
        args.dry_run,
        home=home,
    )
    for note in plan.notes[commit_mark:]:
        print(f"  - {note}")

    print("\n=== 結果 ===")
    if args.dry_run:
        print("[dry-run] 未寫入任何檔案;以上為將寫入的完整內容。")
    else:
        print("[PASS] 第 1 層:設定檔已寫入並通過 schema 驗證(備份:*.bak-setconfig-*)")
        print("[待執行] 第 2 層:實際啟動與模型載入 → ~/start.sh(成功與否以此為準)")
        print("[待執行] 第 3 層:啟動後健檢 → ~/start.sh status(或 ./scripts/check-status.sh --strict)")
        print(f"          與 AICODE_MODEL={plan.main_key} python scripts/doctor.py")

    preview_rc = 0
    if not args.dry_run and not args.no_preview:
        preview_rc = preview_start_commands(plan)

    if not args.dry_run:
        running = running_codetrail_sessions()
        if running:
            print(f"\n⚠ 偵測到 CodeTrail server 正在執行(tmux:{', '.join(running)});"
                  "新設定要重啟才會生效。")
            if args.yes:
                print("  之後執行:~/start.sh stop && ~/start.sh")
            else:
                answer = _input_optional(
                    "  [R] 現在自動重啟 / [S] 稍後自行重啟(Enter=S): ", "s"
                ).strip().lower()
                if answer == "r":
                    rc = _restart_servers(start_path)
                    if rc != 0:
                        return rc

    print("\n下一步:")
    print("  ~/start.sh                        # 啟動四個 llama-server(tmux)")
    print("  ~/start.sh status                 # 確認四個 server 都 ready")
    print("  cd <你要分析的專案> && aicode      # 進 TUI;/status 應顯示 codetrail Connected")
    print("  ~/start.sh stop                   # 收工:關掉全部 tmux server 視窗")
    return 1 if preview_rc != 0 else 0


def main(argv: list[str] | None = None) -> int:
    # C/POSIX locale 的終端印中文會 UnicodeEncodeError;劣化成替代字元,不要當機。
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(errors="replace")
            except (OSError, ValueError):
                pass
    args = _parser().parse_args(argv)
    try:
        return run(args)
    except SetupError as exc:
        print(f"\n[set_config] {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        if _COMMITTED:
            print("\n[set_config] 已中斷:設定檔「已完整寫入」,中斷的只是後續預覽/重啟步驟;"
                  "可直接執行 ~/start.sh。(備份:*.bak-setconfig-*)", file=sys.stderr)
        else:
            print("\n[set_config] 已取消,未寫入任何檔案。(寫入採 transaction:要嘛全套完成、"
                  "要嘛完全未動;若過去跑過,舊檔的 .bak-setconfig-* 備份仍在)", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
